// ============ SCRIPTURES DATA ============

const scripturesData = [
  {
    id: 'veda',
    name: 'वेद',
    nameEn: 'Vedas',
    emoji: '🕉️',
    category: 'श्रुति',
    count: '4 प्रमुख वेद',
    period: 'वैदिक परंपरा',
    focus: 'मंत्र, यज्ञ, ज्ञान और जीवन-दर्शन',
    desc: 'हिंदू धर्म के प्राचीनतम और आधारभूत ग्रंथ, जिन्हें दिव्य ज्ञान का स्रोत माना जाता है।',
    overview:
      'वेद सनातन परंपरा के मूल ग्रंथ माने जाते हैं। इनमें देवताओं की स्तुतियां, यज्ञ-विधि, संगीत, प्रार्थना, औषधीय संकेत और जीवन के मूल सिद्धांत मिलते हैं।',
    topics:
      'ऋग्वेद में सूक्त, यजुर्वेद में यज्ञ-विधि, सामवेद में गान और अथर्ववेद में लोकजीवन, आरोग्य तथा उपासना से जुड़े मंत्र प्रमुख रूप से मिलते हैं।',
    highlights: [
      { id: 'rigveda', label: 'ऋग्वेद' },
      { id: 'yajurveda', label: 'यजुर्वेद' },
      { id: 'samaveda', label: 'सामवेद' },
      { id: 'atharvaveda', label: 'अथर्ववेद' },
    ],
    color: '#5C6BC0',
    gradient:
      'linear-gradient(135deg, rgba(92,107,192,0.16), rgba(48,63,159,0.08))',
  },
  {
    id: 'purana',
    name: 'पुराण',
    nameEn: 'Puranas',
    emoji: '📖',
    category: 'स्मृति',
    count: '18 महापुराण',
    period: 'पुराणकालीन परंपरा',
    focus: 'सृष्टि, अवतार, वंशावली, तीर्थ और धर्मकथाएं',
    desc: 'देवताओं, अवतारों, व्रतों, तीर्थों और लोकधर्म को कथात्मक रूप में समझाने वाला विशाल साहित्य।',
    overview:
      'पुराणों में सृष्टि की उत्पत्ति, मन्वंतर, देव-दानव कथाएं, राजवंश, अवतार, तीर्थ-माहात्म्य और धर्माचरण का विस्तृत वर्णन मिलता है।',
    topics:
      'भक्ति, धर्म, व्रत, पर्व, तीर्थ, अवतार, देवी-देवताओं की महिमा और लोक में प्रचलित आचार-परंपराएं पुराण साहित्य के मुख्य विषय हैं।',
    highlights: [
      { id: 'brahma_purana', label: 'ब्रह्म पुराण' },
      { id: 'padma_purana', label: 'पद्म पुराण' },
      { id: 'vishnu_purana', label: 'विष्णु पुराण' },
      { id: 'shiva_purana', label: 'शिव पुराण' },
      { id: 'bhagavata_purana', label: 'भागवत पुराण' },
      { id: 'narada_purana', label: 'नारद पुराण' },
      { id: 'markandeya_purana', label: 'मार्कण्डेय पुराण' },
      { id: 'agni_purana', label: 'अग्नि पुराण' },
      { id: 'bhavishya_purana', label: 'भविष्य पुराण' },
      { id: 'brahma_vaivarta_purana', label: 'ब्रह्मवैवर्त पुराण' },
      { id: 'linga_purana', label: 'लिंग पुराण' },
      { id: 'varaha_purana', label: 'वराह पुराण' },
      { id: 'skanda_purana', label: 'स्कन्द पुराण' },
      { id: 'vamana_purana', label: 'वामन पुराण' },
      { id: 'kurma_purana', label: 'कुर्म पुराण' },
      { id: 'matsya_purana', label: 'मत्स्य पुराण' },
      { id: 'garuda_purana', label: 'गरुड़ पुराण' },
      { id: 'brahmanda_purana', label: 'ब्रह्माण्ड पुराण' },
    ],
    color: '#EF6C00',
    gradient:
      'linear-gradient(135deg, rgba(239,108,0,0.16), rgba(230,81,0,0.08))',
  },
  {
    id: 'upanishad',
    name: 'उपनिषद',
    nameEn: 'Upanishads',
    emoji: '🪷',
    category: 'श्रुति',
    count: 'मुख्य 10-13 उपनिषद',
    period: 'वैदिक उत्तरभाग',
    focus: 'ब्रह्म, आत्मा, ज्ञान और मोक्ष',
    desc: 'वेदों के दार्शनिक और आध्यात्मिक सार को व्यक्त करने वाले गूढ़ ग्रंथ।',
    overview:
      'उपनिषद गुरु-शिष्य संवाद के रूप में आत्मा, ब्रह्म, जगत, कर्म, ध्यान और मोक्ष जैसे गहन विषयों को स्पष्ट करते हैं। इन्हें वेदांत का आधार माना जाता है।',
    topics:
      'आत्मविद्या, ब्रह्मविद्या, अद्वैत चिंतन, ध्यान, वैराग्य, सत्य की खोज और आंतरिक अनुभूति उपनिषदों के मुख्य विषय हैं।',
    highlights: [
      { id: 'isha_upanishad', label: 'ईश' },
      { id: 'kena_upanishad', label: 'केन' },
      { id: 'katha_upanishad', label: 'कठ' },
      { id: 'prashna_upanishad', label: 'प्रश्न' },
      { id: 'mundaka_upanishad', label: 'मुण्डक' },
      { id: 'mandukya_upanishad', label: 'माण्डूक्य' },
      { id: 'taittiriya_upanishad', label: 'तैत्तिरीय' },
      { id: 'aitareya_upanishad', label: 'ऐतरेय' },
      { id: 'chandogya_upanishad', label: 'छान्दोग्य' },
      { id: 'brihadaranyaka_upanishad', label: 'बृहदारण्यक' },
      { id: 'shvetashvatara_upanishad', label: 'श्वेताश्वतार' },
      { id: 'kaushitaki_upanishad', label: 'कौषीतकी' },
      { id: 'maitrayaniya_upanishad', label: 'मैत्रायणीय' },
    ],
    color: '#00897B',
    gradient:
      'linear-gradient(135deg, rgba(0,137,123,0.16), rgba(0,105,92,0.08))',
  },
  {
    id: 'rigveda',
    parentId: 'veda',
    name: 'ऋग्वेद',
    nameEn: 'Rigveda',
    count: '1028 सूक्त, लगभग 10600 ऋचाएँ',
    period: 'वैदिक काल (लगभग 1500–1200 ईसा पूर्व)',
    focus: 'देवस्तुति, वैदिक मंत्र और दार्शनिक चिंतन',
    desc: 'चारों वेदों में सबसे प्राचीन; देवताओं की स्तुतियों वाले सूक्तों का संग्रह।',
    overview:
      'ऋग्वेद में अग्नि, इंद्र, वरुण, सोम, सूर्य और उषा आदि देवताओं की स्तुतियाँ, यज्ञीय मंत्र और सृष्टि से संबंधित दार्शनिक विचार संहिताबद्ध रूप में मिलते हैं।',
    topics: 'सूक्त, ऋचा, देवस्तुति, यज्ञीय मंत्र, सृष्टि चिंतन',
  },
  {
    id: 'yajurveda',
    parentId: 'veda',
    name: 'यजुर्वेद',
    nameEn: 'Yajurveda',
    count: 'यज्ञ-विधान',
    period: 'वैदिक काल',
    focus: 'कर्मकाण्ड और आहुतियाँ',
    desc: 'यज्ञ-कर्म की विधियाँ और मंत्रों का वेद; कर्मकाण्ड का प्रमुख आधार।',
    overview:
      'यजुर्वेद में यज्ञ की प्रक्रिया, आहुतियाँ और याज्ञिक मंत्र क्रमबद्ध रूप से दिए गए हैं।',
    topics: 'यज्ञ-विधान, कर्मकाण्ड, वेदी, आहुतियाँ।',
  },
  {
    id: 'samaveda',
    parentId: 'veda',
    name: 'सामवेद',
    nameEn: 'Samaveda',
    count: 'सामगान संहिता',
    period: 'वैदिक काल',
    focus: 'गान और उपासना',
    desc: 'मंत्रों का गेय रूप; संगीत परंपरा का आधार माने जाने वाला वेद।',
    overview:
      'सामवेद में ऋग्वेद के मंत्रों का गायन रूप मिलता है जिसे सामगान कहा जाता है।',
    topics: 'संगीत, सामगान, छंद, उपासना।',
  },
  {
    id: 'atharvaveda',
    parentId: 'veda',
    name: 'अथर्ववेद',
    nameEn: 'Atharvaveda',
    count: 'लोक-उपासना मंत्र',
    period: 'वैदिक काल',
    focus: 'आरोग्य और संरक्षण',
    desc: 'लोकजीवन, स्वास्थ्य, शांति और उपासना से जुड़े मंत्रों का संग्रह।',
    overview:
      'अथर्ववेद में गृहस्थ जीवन, रोग-निवारण, सुरक्षा और शांति से जुड़े मंत्रों का उल्लेख मिलता है।',
    topics: 'आरोग्य, संरक्षण, गृहस्थ, शांति उपासना।',
  },
  {
    id: 'brahma_purana',
    parentId: 'purana',
    name: 'ब्रह्म पुराण',
    nameEn: 'Brahma Purana',
    count: 'महापुराण',
    desc: 'सृष्टि-वर्णन और तीर्थ-परंपरा से जुड़ा पुराण।',
  },
  {
    id: 'padma_purana',
    parentId: 'purana',
    name: 'पद्म पुराण',
    nameEn: 'Padma Purana',
    count: 'महापुराण',
    desc: 'धर्म, व्रत और तीर्थ-माहात्म्य की विस्तृत कथाएँ।',
  },
  {
    id: 'vishnu_purana',
    parentId: 'purana',
    name: 'विष्णु पुराण',
    nameEn: 'Vishnu Purana',
    count: 'महापुराण',
    desc: 'विष्णु के अवतारों, वंश और धर्म का वर्णन करने वाला पुराण।',
  },
  {
    id: 'shiva_purana',
    parentId: 'purana',
    name: 'शिव पुराण',
    nameEn: 'Shiva Purana',
    count: 'महापुराण',
    desc: 'शिव के स्वरूप, कथाएँ और भक्ति परंपरा का विस्तृत वर्णन।',
  },
  {
    id: 'bhagavata_purana',
    parentId: 'purana',
    name: 'भागवत पुराण',
    nameEn: 'Bhagavata Purana',
    count: 'महापुराण',
    desc: 'कृष्ण लीलाओं और भक्ति-दर्शन का प्रमुख ग्रंथ।',
  },
  {
    id: 'narada_purana',
    parentId: 'purana',
    name: 'नारद पुराण',
    nameEn: 'Narada Purana',
    count: 'महापुराण',
    desc: 'भक्ति, संगीत, धर्म और पूजा-पद्धति की चर्चा वाला पुराण।',
  },
  {
    id: 'markandeya_purana',
    parentId: 'purana',
    name: 'मार्कण्डेय पुराण',
    nameEn: 'Markandeya Purana',
    count: 'महापुराण',
    desc: 'देवी महात्म्य सहित धर्मकथाओं का महत्वपूर्ण पुराण।',
  },
  {
    id: 'agni_purana',
    parentId: 'purana',
    name: 'अग्नि पुराण',
    nameEn: 'Agni Purana',
    count: 'महापुराण',
    desc: 'यज्ञ, नीति, कला और शास्त्रों का ज्ञान-संग्रह।',
  },
  {
    id: 'bhavishya_purana',
    parentId: 'purana',
    name: 'भविष्य पुराण',
    nameEn: 'Bhavishya Purana',
    count: 'महापुराण',
    desc: 'परंपराएँ, व्रत और कालचक्र से जुड़े प्रसंगों का पुराण।',
  },
  {
    id: 'brahma_vaivarta_purana',
    parentId: 'purana',
    name: 'ब्रह्मवैवर्त पुराण',
    nameEn: 'Brahma Vaivarta Purana',
    count: 'महापुराण',
    desc: 'कृष्ण-राधा और प्रकृति-पुरुष की कथाओं पर केंद्रित पुराण।',
  },
  {
    id: 'linga_purana',
    parentId: 'purana',
    name: 'लिंग पुराण',
    nameEn: 'Linga Purana',
    count: 'महापुराण',
    desc: 'शिवलिंग की महिमा और शिवोपासना पर आधारित पुराण।',
  },
  {
    id: 'varaha_purana',
    parentId: 'purana',
    name: 'वराह पुराण',
    nameEn: 'Varaha Purana',
    count: 'महापुराण',
    desc: 'वराह अवतार और धर्म-उपदेश की कथाओं का पुराण।',
  },
  {
    id: 'skanda_purana',
    parentId: 'purana',
    name: 'स्कन्द पुराण',
    nameEn: 'Skanda Purana',
    count: 'महापुराण',
    desc: 'कार्तिकेय, तीर्थ और कथा-संग्रह का विशाल पुराण।',
  },
  {
    id: 'vamana_purana',
    parentId: 'purana',
    name: 'वामन पुराण',
    nameEn: 'Vamana Purana',
    count: 'महापुराण',
    desc: 'वामन अवतार और धर्म-नियमों की कथाओं का पुराण।',
  },
  {
    id: 'kurma_purana',
    parentId: 'purana',
    name: 'कुर्म पुराण',
    nameEn: 'Kurma Purana',
    count: 'महापुराण',
    desc: 'कूर्म अवतार और धर्म-आचार की चर्चा वाला पुराण।',
  },
  {
    id: 'matsya_purana',
    parentId: 'purana',
    name: 'मत्स्य पुराण',
    nameEn: 'Matsya Purana',
    count: 'महापुराण',
    desc: 'मत्स्य अवतार और सृष्टि-वर्णन से जुड़े प्रसंगों का पुराण।',
  },
  {
    id: 'garuda_purana',
    parentId: 'purana',
    name: 'गरुड़ पुराण',
    nameEn: 'Garuda Purana',
    count: 'महापुराण',
    desc: 'गरुड़ संवाद और कर्म-संस्कार परंपरा की चर्चा वाला पुराण।',
  },
  {
    id: 'brahmanda_purana',
    parentId: 'purana',
    name: 'ब्रह्माण्ड पुराण',
    nameEn: 'Brahmanda Purana',
    count: 'महापुराण',
    desc: 'ब्रह्मांड उत्पत्ति और देवी-विषयक वर्णन वाला पुराण।',
  },
  {
    id: 'isha_upanishad',
    parentId: 'upanishad',
    name: 'ईश उपनिषद',
    nameEn: 'Isha Upanishad',
    count: 'मुख्य उपनिषद',
    desc: 'ईश्वर, त्याग और आत्म-चिंतन पर केंद्रित उपनिषद।',
  },
  {
    id: 'kena_upanishad',
    parentId: 'upanishad',
    name: 'केन उपनिषद',
    nameEn: 'Kena Upanishad',
    count: 'मुख्य उपनिषद',
    desc: 'ज्ञान की प्रेरणा और ब्रह्म की खोज पर प्रश्नोत्तर।',
  },
  {
    id: 'katha_upanishad',
    parentId: 'upanishad',
    name: 'कठ उपनिषद',
    nameEn: 'Katha Upanishad',
    count: 'मुख्य उपनिषद',
    desc: 'नचिकेता-यम संवाद; आत्मा और मृत्यु का ज्ञान।',
  },
  {
    id: 'prashna_upanishad',
    parentId: 'upanishad',
    name: 'प्रश्न उपनिषद',
    nameEn: 'Prashna Upanishad',
    count: 'मुख्य उपनिषद',
    desc: 'छह प्रश्नों के माध्यम से प्राण और ब्रह्म का विवेचन।',
  },
  {
    id: 'mundaka_upanishad',
    parentId: 'upanishad',
    name: 'मुण्डक उपनिषद',
    nameEn: 'Mundaka Upanishad',
    count: 'मुख्य उपनिषद',
    desc: 'परा-अपरा विद्या और ब्रह्मज्ञान की शिक्षा।',
  },
  {
    id: 'mandukya_upanishad',
    parentId: 'upanishad',
    name: 'माण्डूक्य उपनिषद',
    nameEn: 'Mandukya Upanishad',
    count: 'मुख्य उपनिषद',
    desc: 'ॐ और चेतना की चार अवस्थाओं का निरूपण।',
  },
  {
    id: 'taittiriya_upanishad',
    parentId: 'upanishad',
    name: 'तैत्तिरीय उपनिषद',
    nameEn: 'Taittiriya Upanishad',
    count: 'मुख्य उपनिषद',
    desc: 'अन्न, प्राण, मन, विज्ञान और आनंद-कोश की चर्चा।',
  },
  {
    id: 'aitareya_upanishad',
    parentId: 'upanishad',
    name: 'ऐतरेय उपनिषद',
    nameEn: 'Aitareya Upanishad',
    count: 'मुख्य उपनिषद',
    desc: 'आत्मा-चेतना और सृष्टि का दार्शनिक विवेचन।',
  },
  {
    id: 'chandogya_upanishad',
    parentId: 'upanishad',
    name: 'छान्दोग्य उपनिषद',
    nameEn: 'Chandogya Upanishad',
    count: 'मुख्य उपनिषद',
    desc: 'उपासना और महावाक्य \"तत्त्वमसि\" का प्रतिपादन।',
  },
  {
    id: 'brihadaranyaka_upanishad',
    parentId: 'upanishad',
    name: 'बृहदारण्यक उपनिषद',
    nameEn: 'Brihadaranyaka Upanishad',
    count: 'मुख्य उपनिषद',
    desc: 'आत्मा और ब्रह्म पर विस्तृत दार्शनिक विचार।',
  },
  {
    id: 'shvetashvatara_upanishad',
    parentId: 'upanishad',
    name: 'श्वेताश्वतार उपनिषद',
    nameEn: 'Shvetashvatara Upanishad',
    count: 'मुख्य उपनिषद',
    desc: 'ईश्वर, योग और भक्ति पर केंद्रित उपनिषद।',
  },
  {
    id: 'kaushitaki_upanishad',
    parentId: 'upanishad',
    name: 'कौषीतकी उपनिषद',
    nameEn: 'Kaushitaki Upanishad',
    count: 'मुख्य उपनिषद',
    desc: 'प्राण, उपासना और आत्म-ज्ञान का वर्णन।',
  },
  {
    id: 'maitrayaniya_upanishad',
    parentId: 'upanishad',
    name: 'मैत्रायणीय उपनिषद',
    nameEn: 'Maitrayaniya Upanishad',
    count: 'मुख्य उपनिषद',
    desc: 'ध्यान, योग और आत्मानुभूति का विवेचन।',
  },
];
