// ============ DATA ============
const deities = {
  ganesh: {
    name: 'শ্রী গণেশ',
    english: 'Shri Ganesh',
    emoji: '🐘',
    color: '#FF6B00',
    desc: 'বিঘ্ননাশক, প্রথম পূজিত',
    img: 'icons/ganesh.webp',
  },
  shiva: {
    name: 'শ্রী শিব',
    english: 'Shri Shiv',
    emoji: '🔱',
    color: '#4169E1',
    desc: 'মহাদেব, ভোলেনাথ, সংহারক',
    img: 'icons/shiv.webp',
  },
  parvati: {
    name: 'শ্রী পার্বতী',
    english: 'Shri Parvati',
    emoji: '🪷',
    color: '#AD1457',
    desc: 'শিবের অর্ধাঙ্গিনী, শক্তি ও মাতৃত্বের দেবী',
    img: 'icons/parvati.webp',
  },
  vishnu: {
    name: 'শ্রী বিষ্ণু',
    english: 'Shri Vishnu',
    emoji: '✨',
    color: '#0080FF',
    desc: 'পালনকর্তা, নারায়ণ, জগতের রক্ষক',
    img: 'icons/vishnu.webp',
  },
  lakshmi: {
    name: 'শ্রী লক্ষ্মী',
    english: 'Shri Lakshmi',
    emoji: '🪷',
    color: '#FFD700',
    desc: 'ধনদাত্রী, পদ্মবাসিনী, সমৃদ্ধির দেবী',
    img: 'icons/lakshmi.webp',
  },
  durga: {
    name: 'শ্রী দুর্গা',
    english: 'Shri Durga',
    emoji: '🌸',
    color: '#FF1493',
    desc: 'আদিশক্তি, মহামায়া, সিংহবাহিনী',
    img: 'icons/durga.webp',
  },
  kali: {
    name: 'শ্রী কালী',
    english: 'Shri Kali',
    emoji: '⚡',
    color: '#800080',
    desc: 'মহাকালী, তারা, আদ্যশক্তির উগ্র রূপ',
    img: 'icons/kali.webp',
  },
  ram: {
    name: 'শ্রী রাম',
    english: 'Shri Ram',
    emoji: '🏹',
    color: '#00AA00',
    desc: 'মর্যাদা পুরুষোত্তম, রঘুকুলের ভূষণ',
    img: 'icons/ram.webp',
  },
  hanuman: {
    name: 'শ্রী হনুমান',
    english: 'Shri Hanuman',
    emoji: '🙏',
    color: '#FF4500',
    desc: 'পবনপুত্র, বজরংবলী, রামভক্ত শিরোমণি',
    img: 'icons/hanuman.webp',
  },
  balaji: {
    name: 'শ্রী বালাজী',
    english: 'Shri Balaji',
    emoji: '🏹',
    color: '#8D6E63',
    desc: 'সঙ্কটমোচক, পূজ্য স্বরূপ',
    img: 'icons/balaji.webp',
  },
  pretraj_sarkar: {
    name: 'শ্রী প্রেতরাজ সরকার',
    english: 'Shri Pretraj Sarkar',
    emoji: '🔥',
    color: '#4E342E',
    desc: 'নেতিবাচক বাধা দূরকারী',
    img: 'icons/pretraj_sarkar.webp',
  },
  krishna: {
    name: 'শ্রী কৃষ্ণ',
    english: 'Shri Krishna',
    emoji: '🪈',
    color: '#0000CD',
    desc: 'গোবিন্দ, মুরলীমনোহর, ব্রজবিহারী',
    img: 'icons/krishna.webp',
    geeta: typeof geetaData !== 'undefined' ? geetaData.krishna : null,
  },
  khatu_shyam: {
    name: 'শ্রী খাটু শ্যাম',
    english: 'Shri Khatu Shyam',
    emoji: '🏹',
    color: '#FF4500',
    desc: 'হারা মানুষের আশ্রয়, মোরভী নন্দন, কলিযুগের অবতার',
    img: 'icons/khatu_shyam.webp',
  },
  tirupati_balaji: {
    name: 'শ্রী তিরুপতি বালাজী',
    english: 'Tirupati Bala Ji',
    emoji: '🌟',
    color: '#FFD54F',
    desc: 'শ্রী ভেঙ্কটেশ্বর, বিষ্ণুর পূজ্য রূপ',
    img: 'icons/tirupati_balaji.webp',
  },
  jagannath: {
    name: 'শ্রী জগন্নাথ',
    english: 'Jagannath',
    emoji: '🕉️',
    color: '#4CAF50',
    desc: 'পুরীর প্রসিদ্ধ দেবতা, ভগবান বিষ্ণুর রূপ ও ভক্তির প্রতীক',
    img: 'icons/jagannath.webp',
  },
  gopal: {
    name: 'শ্রী গোপাল',
    english: 'Shri Gopal',
    emoji: '🐄',
    color: '#5C6BC0',
    desc: 'বাল গোবিন্দ, গোপালক, করুণাময়',
    img: 'icons/gopal.webp',
  },
  surya: {
    name: 'শ্রী সূর্য',
    english: 'Shri Surya',
    emoji: '☀️',
    color: '#FF8C00',
    desc: 'প্রত্যক্ষ দেব, জগতের নয়ন, শক্তির উৎস',
    img: 'icons/surya.webp',
  },
  shani: {
    name: 'শ্রী শনি দেব',
    english: 'Shri Shani Dev',
    emoji: '⚖️',
    color: '#1a1a1a',
    desc: 'কর্মফলদাতা, সূর্যপুত্র, ন্যায়ের দেবতা',
    img: 'icons/shani.webp',
  },
  brihaspati: {
    name: 'শ্রী বৃহস্পতি দেব',
    english: 'Shri Brihaspati Dev',
    emoji: '📜',
    color: '#EF6C00',
    desc: 'বেদজ্ঞ, গুরু, ন্যায়ের দেবতা',
    img: 'icons/brihaspati.webp',
  },
  brahma: {
    name: 'শ্রী ব্রহ্মা',
    english: 'Shri Brahma',
    emoji: '📜',
    color: '#EF6C00',
    desc: 'সৃষ্টিকর্তা, বেদজ্ঞ, চতুর্মুখ',
    img: 'icons/brahma.webp',
  },
  saraswati: {
    name: 'শ্রী সরস্বতী',
    english: 'Shri Saraswati',
    emoji: '🎵',
    color: '#FFFFFF',
    desc: 'বিদ্যাদায়িনী, বাগদেবী, বীণাবাদিনী',
    img: 'icons/saraswati.webp',
  },
  bhairav: {
    name: 'শ্রী ভৈরব',
    english: 'Shri Bhairav',
    emoji: '🐕',
    color: '#37474F',
    desc: 'ক্ষেত্রপাল, রক্ষক, উগ্র করুণাময়',
    img: 'icons/bhairav.webp',
  },
  batuk_bhairav: {
    name: 'শ্রী বটুক ভৈরব',
    english: 'Shri Batuk Bhairav',
    emoji: '🛡️',
    color: '#455A64',
    desc: 'বাল ভৈরব, দ্রুত রক্ষক',
    img: 'icons/batuk_bhairav.webp',
  },
  parshuram: {
    name: 'শ্রী পরশুরাম',
    english: 'Shri Parshuram',
    emoji: '🪓',
    color: '#5D4037',
    desc: 'বিষ্ণুর অবতার, ধর্মরক্ষক',
    img: 'icons/parshuram.webp',
  },
  giriraj: {
    name: 'শ্রী গিরিরাজ',
    english: 'Shri Giriraj',
    emoji: '⛰️',
    color: '#7CB342',
    desc: 'গোবর্ধন স্বরূপ, আশ্রয়দাতা',
    img: 'icons/giriraj.webp',
  },
  navgrah: {
    name: 'শ্রী নবগ্রহ',
    english: 'Shri Navgrah',
    emoji: '🪐',
    color: '#546E7A',
    desc: 'নয় গ্রহের সমষ্টি পূজা',
    img: 'icons/navgrah.webp',
  },
  vishwakarma: {
    name: 'শ্রী বিশ্বকর্মা',
    english: 'Shri Vishwakarma',
    emoji: '🛠️',
    color: '#6D4C41',
    desc: 'দেবশিল্পী, নির্মাণ দেবতা',
    img: 'icons/vishwakarma.webp',
  },
  sai: {
    name: 'শ্রী সাঁই',
    english: 'Shri Sai',
    emoji: '🕯️',
    color: '#9E9D24',
    desc: 'শ্রদ্ধা ও সবুরির প্রতীক',
    img: 'icons/sai.webp',
  },
  mahavir: {
    name: 'শ্রী মহাবীর',
    english: 'Shri Mahavir',
    emoji: '🪷',
    color: '#26A69A',
    desc: 'অহিংসা, তপ ও সত্যের আদর্শ',
    img: 'icons/mahavir.webp',
  },
  pitar: {
    name: 'শ্রী পিতৃদেব',
    english: 'Shri Pitar',
    emoji: '🕯',
    color: '#6D4C41',
    desc: 'পূর্বজ পূজা, কুলের আশীর্বাদ',
    img: 'icons/pitar.webp',
  },
  vaishno_devi: {
    name: 'শ্রী বৈষ্ণো দেবী',
    english: 'Shri Vaishno Devi',
    emoji: '🛕',
    color: '#C2185B',
    desc: 'ত্রিকূটা বাসিনী, শক্তিস্বরূপা',
    img: 'icons/vaishno_devi.webp',
  },
  sheetla: {
    name: 'শ্রী শীতলা',
    english: 'Shri Sheetla',
    emoji: '🧺',
    color: '#00ACC1',
    desc: 'আরোগ্যদায়িনী মাতা',
    img: 'icons/sheetla.webp',
  },
  mahakali: {
    name: 'শ্রী মহাকালী',
    english: 'Shri Mahakali',
    emoji: '⚔️',
    color: '#283593',
    desc: 'কালবিনাশিনী, অদম্য শক্তি',
    img: 'icons/mahakali.webp',
  },
  baglamukhi: {
    name: 'শ্রী বগলামুখী',
    english: 'Shri Baglamukhi',
    emoji: '🟡',
    color: '#FBC02D',
    desc: 'দশমহাবিদ্যা, স্তম্ভন শক্তি',
    img: 'icons/baglamukhi.webp',
  },
  mahalakshmi: {
    name: 'শ্রী মহালক্ষ্মী',
    english: 'Shri Mahalakshmi',
    emoji: '💰',
    color: '#F9A825',
    desc: 'ঐশ্বর্য, সৌভাগ্য, মঙ্গলময়ী',
    img: 'icons/mahalakshmi.webp',
  },
  gayatri: {
    name: 'শ্রী গায়ত্রী',
    english: 'Shri Gayatri',
    emoji: '📿',
    color: '#FF7043',
    desc: 'বেদমাতা, বুদ্ধি প্রদানকারী',
    img: 'icons/gayatri.webp',
  },
  sharda: {
    name: 'শ্রী শারদা',
    english: 'Shri Sharda',
    emoji: '📖',
    color: '#5E35B1',
    desc: 'জ্ঞান ও বাণীর স্বরূপ',
    img: 'icons/sharda.webp',
  },
  radha: {
    name: 'শ্রী রাধা',
    english: 'Shri Radha',
    emoji: '🌸',
    color: '#EC407A',
    desc: 'ভক্তি ও প্রেমের অধিষ্ঠাত্রী',
    img: 'icons/radha.webp',
  },
  santoshi_maa: {
    name: 'শ্রী সন্তোষী মা',
    english: 'Shri Santoshi Maa',
    emoji: '🍚',
    color: '#F06292',
    desc: 'সন্তোষ, সুখ ও সরল ভক্তি',
    img: 'icons/santoshi_maa.webp',
  },
  vindhyeshwari: {
    name: 'শ্রী বিন্ধ্যেশ্বরী',
    english: 'Shri Vindhyeshwari',
    emoji: '🌺',
    color: '#D81B60',
    desc: 'বিন্ধ্যবাসিনী মাতার স্বরূপ',
    img: 'icons/vindhyeshwari.webp',
  },
  annapurna: {
    name: 'শ্রী অন্নপূর্ণা',
    english: 'Shri Annapurna',
    emoji: '🍲',
    color: '#FF8F00',
    desc: 'অন্ন, পুষ্টি ও করুণার দেবী',
    img: 'icons/annapurna.webp',
  },
  chhathi_maiya: {
    name: 'ছঠি মাইয়া',
    english: 'Chhathi Maiya',
    emoji: '🌅',
    color: '#FF6F00',
    desc: 'সূর্য উপাসনা, সন্তান সুখ ও সমৃদ্ধির দেবী',
    img: 'icons/chhathi_maiya.webp',
  },
  tulsi: {
    name: 'শ্রী তুলসী',
    english: 'Shri Tulsi',
    emoji: '🌿',
    color: '#43A047',
    desc: 'পবিত্রতা, ভক্তি ও সংরক্ষণ',
    img: 'icons/tulsi.webp',
  },
  ganga: {
    name: 'শ্রী গঙ্গা',
    english: 'Shri Ganga',
    emoji: '🌊',
    color: '#1E88E5',
    desc: 'পবিত্র নদী, মোক্ষদায়িনী',
    img: 'icons/ganga.webp',
  },
  narmada: {
    name: 'শ্রী নর্মদা',
    english: 'Shri Narmada',
    emoji: '💧',
    color: '#039BE5',
    desc: 'রেবা মাতা, পুণ্যদায়িনী',
    img: 'icons/narmada.webp',
  },
  shakambhari: {
    name: 'শ্রী শাকম্ভরী',
    english: 'Shri Shakambhari',
    emoji: '🥬',
    color: '#7CB342',
    desc: 'অন্ন ও উদ্ভিদের পোষক দেবী',
    img: 'icons/shakambhari.webp',
  },
  lalita_shakambhari: {
    name: 'শ্রী ললিতা শাকম্ভরী',
    english: 'Shri Lalita Shakambhari',
    emoji: '🌼',
    color: '#8BC34A',
    desc: 'ললিতা ও শাকম্ভরীর সমন্বিত রূপ',
    img: 'icons/lalita_shakambhari.webp',
  },
  rani_sati: {
    name: 'শ্রী রাণী সতী',
    english: 'Shri Rani Sati',
    emoji: '🏵️',
    color: '#8E24AA',
    desc: 'লোকআস্থার পূজ্য মাতৃশক্তি',
    img: 'icons/rani_sati.webp',
  },
  neem_karoli_baba: {
    name: 'নীম করোলি বাবা',
    english: 'Neem Karoli Baba',
    emoji: '🙏',
    color: '#FF9800',
    desc: 'ভক্তি, সেবা ও প্রেমের সাধু',
    img: 'icons/neem_karoli_baba.webp',
  },
  ravidas: {
    name: 'শ্রী রবিদাস',
    english: 'Shri Ravidas',
    emoji: '🙏',
    color: '#8D6E63',
    desc: 'ভক্তি সন্ত, সমতার বার্তা',
    img: 'icons/ravidas.webp',
  },
  baba_gangaram: {
    name: 'শ্রী বাবা গঙ্গারাম',
    english: 'Shri Baba Gangaram',
    emoji: '🛕',
    color: '#6A1B9A',
    desc: 'লোকশ্রদ্ধার পূজ্য সাধু',
    img: 'icons/baba_gangaram.webp',
  },
  ramdev: {
    name: 'শ্রী রামদেব',
    english: 'Shri Ramdev',
    emoji: '🐎',
    color: '#8E24AA',
    desc: 'লোকদেব, জনকল্যাণকারী',
    img: 'icons/ramdev.webp',
  },
  jaharveer: {
    name: 'শ্রী জাহরবীর',
    english: 'Shri Jaharveer',
    emoji: '🏇',
    color: '#795548',
    desc: 'লোকরক্ষক, বীর দেব',
    img: 'icons/jaharveer.webp',
  },
  gorakh_nath: {
    name: 'শ্রী গোরখনাথ',
    english: 'Shri Gorakh Nath',
    emoji: '🧘',
    color: '#607D8B',
    desc: 'নাথ যোগ পরম্পরার আচার্য',
    img: 'icons/gorakh_nath.webp',
  },
};
