// ============ DATA ============
const deities = {
  ganesh: {
    name: 'শ্রী গণেশ',
    english: 'Shri Ganesh',
    emoji: '🐘',
    color: '#FF6B00',
    desc: 'বিঘ্ননাশক, প্রথম পূজিত',
    img: 'ganesh.webp',
  },
  shiva: {
    name: 'শ্রী শিব',
    english: 'Shri Shiv',
    emoji: '🔱',
    color: '#4169E1',
    desc: 'মহাদেব, ভোলেনাথ, সংহারক',
    img: 'shiv.webp',
  },
  parvati: {
    name: 'শ্রী পার্বতী',
    english: 'Shri Parvati',
    emoji: '🪷',
    color: '#AD1457',
    desc: 'শিবের অর্ধাঙ্গিনী, শক্তি ও মাতৃত্বের দেবী',
    img: 'parvati.webp',
  },
  vishnu: {
    name: 'শ্রী বিষ্ণু',
    english: 'Shri Vishnu',
    emoji: '✨',
    color: '#0080FF',
    desc: 'পালনকর্তা, নারায়ণ, জগতের রক্ষক',
    img: 'vishnu.webp',
  },
  lakshmi: {
    name: 'শ্রী লক্ষ্মী',
    english: 'Shri Lakshmi',
    emoji: '🪷',
    color: '#FFD700',
    desc: 'ধনদাত্রী, পদ্মবাসিনী, সমৃদ্ধির দেবী',
    img: 'lakshmi.webp',
  },
  durga: {
    name: 'শ্রী দুর্গা',
    english: 'Shri Durga',
    emoji: '🌸',
    color: '#FF1493',
    desc: 'আদিশক্তি, মহামায়া, সিংহবাহিনী',
    img: 'durga.webp',
  },
  kali: {
    name: 'শ্রী কালী',
    english: 'Shri Kali',
    emoji: '⚡',
    color: '#800080',
    desc: 'মহাকালী, তারা, আদ্যশক্তির উগ্র রূপ',
    img: 'kali.webp',
  },
  ram: {
    name: 'শ্রী রাম',
    english: 'Shri Ram',
    emoji: '🏹',
    color: '#00AA00',
    desc: 'মর্যাদা পুরুষোত্তম, রঘুকুলের ভূষণ',
    img: 'ram.webp',
  },
  hanuman: {
    name: 'শ্রী হনুমান',
    english: 'Shri Hanuman',
    emoji: '🙏',
    color: '#FF4500',
    desc: 'পবনপুত্র, বজরংবলী, রামভক্ত শিরোমণি',
    img: 'hanuman.webp',
  },
  balaji: {
    name: 'শ্রী বালাজী',
    english: 'Shri Balaji',
    emoji: '🏹',
    color: '#8D6E63',
    desc: 'সঙ্কটমোচক, পূজ্য স্বরূপ',
    img: 'balaji.webp',
  },
  pretraj_sarkar: {
    name: 'শ্রী প্রেতরাজ সরকার',
    english: 'Shri Pretraj Sarkar',
    emoji: '🔥',
    color: '#4E342E',
    desc: 'নেতিবাচক বাধা দূরকারী',
    img: 'pretraj_sarkar.webp',
  },
  krishna: {
    name: 'শ্রী কৃষ্ণ',
    english: 'Shri Krishna',
    emoji: '🪈',
    color: '#0000CD',
    desc: 'গোবিন্দ, মুরলীমনোহর, ব্রজবিহারী',
    img: 'krishna.webp',
    geeta: typeof geetaData !== 'undefined' ? geetaData.krishna : null,
  },
  khatu_shyam: {
    name: 'শ্রী খাটু শ্যাম',
    english: 'Shri Khatu Shyam',
    emoji: '🏹',
    color: '#FF4500',
    desc: 'হারা মানুষের আশ্রয়, মোরভী নন্দন, কলিযুগের অবতার',
    img: 'khatu_shyam.webp',
  },
  tirupati_balaji: {
    name: 'শ্রী তিরুপতি বালাজী',
    english: 'Tirupati Bala Ji',
    emoji: '🌟',
    color: '#FFD54F',
    desc: 'শ্রী ভেঙ্কটেশ্বর, বিষ্ণুর পূজ্য রূপ',
    img: 'tirupati_balaji.webp',
  },
  jagannath: {
    name: 'শ্রী জগন্নাথ',
    english: 'Jagannath',
    emoji: '🕉️',
    color: '#4CAF50',
    desc: 'পুরীর প্রসিদ্ধ দেবতা, ভগবান বিষ্ণুর রূপ ও ভক্তির প্রতীক',
    img: 'jagannath.webp',
  },
  gopal: {
    name: 'শ্রী গোপাল',
    english: 'Shri Gopal',
    emoji: '🐄',
    color: '#5C6BC0',
    desc: 'বাল গোবিন্দ, গোপালক, করুণাময়',
    img: 'gopal.webp',
  },
  balarama: {
    name: 'শ্রী বলরাম',
    english: 'Shri Balarama',
    emoji: '🙏',
    color: '#F5F5DC',
    desc: 'শ্রীকৃষ্ণের জ্যেষ্ঠ ভ্রাতা, শেষনাগের অবতার, শক্তি ও ধর্মের প্রতীক',
    img: 'balarama.webp',
  },
  narasimha: {
    name: 'শ্রী নৃসিংহ',
    english: 'Shri Narasimha',
    emoji: '🙏',
    color: '#D84315',
    desc: 'ভগবান বিষ্ণুর উগ্র অবতার, ভক্ত প্রহ্লাদের রক্ষাকর্তা ও অধর্মের সংহারক',
    img: 'narasimha.webp',
  },
  vamana: {
    name: 'শ্রী বামন',
    english: 'Shri Vamana',
    emoji: '🙏',
    color: '#6D4C41',
    desc: 'ভগবান বিষ্ণুর পঞ্চম অবতার, ধর্ম প্রতিষ্ঠাতা ও রাজা বলির উদ্ধারের কর্তা',
    img: 'vamana.webp',
  },
  varaha: {
    name: 'শ্রী বরাহ',
    english: 'Shri Varaha',
    emoji: '🙏',
    color: '#795548',
    desc: 'ভগবান বিষ্ণুর তৃতীয় অবতার, ধরিত্রী মাতার উদ্ধারকর্তা ও অধর্মের সংহারক',
    img: 'varaha.webp',
  },
  matsya: {
    name: 'শ্রী মৎস্য',
    english: 'Shri Matsya',
    emoji: '🙏',
    color: '#0277BD',
    desc: 'ভগবান বিষ্ণুর প্রথম অবতার, বেদের রক্ষাকর্তা ও প্রলয় থেকে জীবনের উদ্ধারকর্তা',
    img: 'matsya.webp',
  },
  kurma: {
    name: 'শ্রী কূর্ম',
    english: 'Shri Kurma',
    emoji: '🙏',
    color: '#5D4037',
    desc: 'ভগবান বিষ্ণুর দ্বিতীয় অবতার, সমুদ্র মন্থনে মন্দর পর্বতের ভিত্তি হয়েছিলেন',
    img: 'kurma.webp',
  },
  hayagriva: {
    name: 'শ্রী হয়গ্রীব',
    english: 'Shri Hayagriva',
    emoji: '🙏',
    color: '#1565C0',
    desc: 'ভগবান বিষ্ণুর দিব্য অশ্বমুখী রূপ, জ্ঞান, বিদ্যা ও বেদের অধিষ্ঠাতা',
    img: 'hayagriva.webp',
  },
  vitthal: {
    name: 'শ্রী বিঠ্ঠল',
    english: 'Shri Vitthal',
    emoji: '🙏',
    color: '#1565C0',
    desc: 'ভগবান বিষ্ণুর ভক্তবৎসল রূপ, পন্ধরপুরের আরাধ্য দেবতা ও ভক্তির প্রতীক',
    img: 'vitthal.webp',
  },
  ranganatha: {
    name: 'শ্রী রঙ্গনাথ',
    english: 'Shri Ranganatha',
    emoji: '🙏',
    color: '#1565C0',
    desc: 'ভগবান বিষ্ণুর শয়ন রূপ, শ্রীরঙ্গমের আরাধ্য দেবতা ও ভক্তদের পালনকর্তা',
    img: 'ranganatha.webp',
  },
  dhanvantari: {
    name: 'শ্রী ধন্বন্তরি',
    english: 'Shri Dhanvantari',
    emoji: '🙏',
    color: '#2E7D32',
    desc: 'ভগবান বিষ্ণুর দিব্য অবতার, আয়ুর্বেদ ও আরোগ্যের অধিষ্ঠাতা দেবতা',
    img: 'dhanvantari.webp',
  },
  kartikeya: {
    name: 'শ্রী কার্তিকেয়',
    english: 'Shri Kartikeya',
    emoji: '🙏',
    color: '#E65100',
    desc: 'দেবসেনাপতি, ভগবান শিব-পার্বতীর পুত্র, যুদ্ধ ও বিজয়ের দেবতা',
    img: 'kartikeya.webp',
  },
  ayyappa: {
    name: 'শ্রী অয়্যাপ্পা',
    english: 'Shri Ayyappa',
    emoji: '🙏',
    color: '#5D4037',
    desc: 'হরিহরপুত্র, ধর্মশাস্ত, ভক্তি ও ধর্মের দেবতা',
    img: 'ayyappa.webp',
  },
  ardhanarishvara: {
    name: 'অর্ধনারীশ্বর',
    english: 'Ardhanarishvara',
    emoji: '🙏',
    color: '#7B1FA2',
    desc: 'শিব ও শক্তির দিব্য রূপ, পুরুষ ও প্রকৃতির ঐক্যের প্রতীক',
    img: 'ardhanarishvara.webp',
  },
  surya: {
    name: 'শ্রী সূর্য',
    english: 'Shri Surya',
    emoji: '☀️',
    color: '#FF8C00',
    desc: 'প্রত্যক্ষ দেব, জগতের নয়ন, শক্তির উৎস',
    img: 'surya.webp',
  },
  shani: {
    name: 'শ্রী শনি দেব',
    english: 'Shri Shani Dev',
    emoji: '⚖️',
    color: '#1a1a1a',
    desc: 'কর্মফলদাতা, সূর্যপুত্র, ন্যায়ের দেবতা',
    img: 'shani.webp',
  },
  brihaspati: {
    name: 'শ্রী বৃহস্পতি দেব',
    english: 'Shri Brihaspati Dev',
    emoji: '📜',
    color: '#EF6C00',
    desc: 'বেদজ্ঞ, গুরু, ন্যায়ের দেবতা',
    img: 'brihaspati.webp',
  },
  brahma: {
    name: 'শ্রী ব্রহ্মা',
    english: 'Shri Brahma',
    emoji: '📜',
    color: '#EF6C00',
    desc: 'সৃষ্টিকর্তা, বেদজ্ঞ, চতুর্মুখ',
    img: 'brahma.webp',
  },
  saraswati: {
    name: 'শ্রী সরস্বতী',
    english: 'Shri Saraswati',
    emoji: '🎵',
    color: '#FFFFFF',
    desc: 'বিদ্যাদায়িনী, বাগদেবী, বীণাবাদিনী',
    img: 'saraswati.webp',
  },
  bhairav: {
    name: 'শ্রী ভৈরব',
    english: 'Shri Bhairav',
    emoji: '🐕',
    color: '#37474F',
    desc: 'ক্ষেত্রপাল, রক্ষক, উগ্র করুণাময়',
    img: 'bhairav.webp',
  },
  batuk_bhairav: {
    name: 'শ্রী বটুক ভৈরব',
    english: 'Shri Batuk Bhairav',
    emoji: '🛡️',
    color: '#455A64',
    desc: 'বাল ভৈরব, দ্রুত রক্ষক',
    img: 'batuk_bhairav.webp',
  },
  veerabhadra: {
    name: 'শ্রী বীরভদ্র',
    english: 'Shri Veerabhadra',
    emoji: '🙏',
    color: '#8B0000',
    desc: 'ভগবান শিবের উগ্র রূপ, ধর্ম ও ন্যায়ের রক্ষক',
    img: 'veerabhadra.webp',
  },
  parshuram: {
    name: 'শ্রী পরশুরাম',
    english: 'Shri Parshuram',
    emoji: '🪓',
    color: '#5D4037',
    desc: 'বিষ্ণুর অবতার, ধর্মরক্ষক',
    img: 'parshuram.webp',
  },
  giriraj: {
    name: 'শ্রী গিরিরাজ',
    english: 'Shri Giriraj',
    emoji: '⛰️',
    color: '#7CB342',
    desc: 'গোবর্ধন স্বরূপ, আশ্রয়দাতা',
    img: 'giriraj.webp',
  },
  navgrah: {
    name: 'শ্রী নবগ্রহ',
    english: 'Shri Navgrah',
    emoji: '🪐',
    color: '#546E7A',
    desc: 'নয় গ্রহের সমষ্টি পূজা',
    img: 'navgrah.webp',
  },
  vishwakarma: {
    name: 'শ্রী বিশ্বকর্মা',
    english: 'Shri Vishwakarma',
    emoji: '🛠️',
    color: '#6D4C41',
    desc: 'দেবশিল্পী, নির্মাণ দেবতা',
    img: 'vishwakarma.webp',
  },
  sai: {
    name: 'শ্রী সাঁই',
    english: 'Shri Sai',
    emoji: '🕯️',
    color: '#9E9D24',
    desc: 'শ্রদ্ধা ও সবুরির প্রতীক',
    img: 'sai.webp',
  },
  mahavir: {
    name: 'শ্রী মহাবীর',
    english: 'Shri Mahavir',
    emoji: '🪷',
    color: '#26A69A',
    desc: 'অহিংসা, তপ ও সত্যের আদর্শ',
    img: 'mahavir.webp',
  },
  pitar: {
    name: 'শ্রী পিতৃদেব',
    english: 'Shri Pitar',
    emoji: '🕯',
    color: '#6D4C41',
    desc: 'পূর্বজ পূজা, কুলের আশীর্বাদ',
    img: 'pitar.webp',
  },
  vaishno_devi: {
    name: 'শ্রী বৈষ্ণো দেবী',
    english: 'Shri Vaishno Devi',
    emoji: '🛕',
    color: '#C2185B',
    desc: 'ত্রিকূটা বাসিনী, শক্তিস্বরূপা',
    img: 'vaishno_devi.webp',
  },
  sheetla: {
    name: 'শ্রী শীতলা',
    english: 'Shri Sheetla',
    emoji: '🧺',
    color: '#00ACC1',
    desc: 'আরোগ্যদায়িনী মাতা',
    img: 'sheetla.webp',
  },
  mahakali: {
    name: 'শ্রী মহাকালী',
    english: 'Shri Mahakali',
    emoji: '⚔️',
    color: '#283593',
    desc: 'কালবিনাশিনী, অদম্য শক্তি',
    img: 'mahakali.webp',
  },
  baglamukhi: {
    name: 'শ্রী বগলামুখী',
    english: 'Shri Baglamukhi',
    emoji: '🟡',
    color: '#FBC02D',
    desc: 'দশমহাবিদ্যা, স্তম্ভন শক্তি',
    img: 'baglamukhi.webp',
  },
  mahalakshmi: {
    name: 'শ্রী মহালক্ষ্মী',
    english: 'Shri Mahalakshmi',
    emoji: '💰',
    color: '#F9A825',
    desc: 'ঐশ্বর্য, সৌভাগ্য, মঙ্গলময়ী',
    img: 'mahalakshmi.webp',
  },
  gayatri: {
    name: 'শ্রী গায়ত্রী',
    english: 'Shri Gayatri',
    emoji: '📿',
    color: '#FF7043',
    desc: 'বেদমাতা, বুদ্ধি প্রদানকারী',
    img: 'gayatri.webp',
  },
  sharda: {
    name: 'শ্রী শারদা',
    english: 'Shri Sharda',
    emoji: '📖',
    color: '#5E35B1',
    desc: 'জ্ঞান ও বাণীর স্বরূপ',
    img: 'sharda.webp',
  },
  radha: {
    name: 'শ্রী রাধা',
    english: 'Shri Radha',
    emoji: '🌸',
    color: '#EC407A',
    desc: 'ভক্তি ও প্রেমের অধিষ্ঠাত্রী',
    img: 'radha.webp',
  },
  santoshi_maa: {
    name: 'শ্রী সন্তোষী মা',
    english: 'Shri Santoshi Maa',
    emoji: '🍚',
    color: '#F06292',
    desc: 'সন্তোষ, সুখ ও সরল ভক্তি',
    img: 'santoshi_maa.webp',
  },
  vindhyeshwari: {
    name: 'শ্রী বিন্ধ্যেশ্বরী',
    english: 'Shri Vindhyeshwari',
    emoji: '🌺',
    color: '#D81B60',
    desc: 'বিন্ধ্যবাসিনী মাতার স্বরূপ',
    img: 'vindhyeshwari.webp',
  },
  annapurna: {
    name: 'শ্রী অন্নপূর্ণা',
    english: 'Shri Annapurna',
    emoji: '🍲',
    color: '#FF8F00',
    desc: 'অন্ন, পুষ্টি ও করুণার দেবী',
    img: 'annapurna.webp',
  },
  chhathi_maiya: {
    name: 'ছঠি মাইয়া',
    english: 'Chhathi Maiya',
    emoji: '🌅',
    color: '#FF6F00',
    desc: 'সূর্য উপাসনা, সন্তান সুখ ও সমৃদ্ধির দেবী',
    img: 'chhathi_maiya.webp',
  },
  tulsi: {
    name: 'শ্রী তুলসী',
    english: 'Shri Tulsi',
    emoji: '🌿',
    color: '#43A047',
    desc: 'পবিত্রতা, ভক্তি ও সংরক্ষণ',
    img: 'tulsi.webp',
  },
  ganga: {
    name: 'শ্রী গঙ্গা',
    english: 'Shri Ganga',
    emoji: '🌊',
    color: '#1E88E5',
    desc: 'পবিত্র নদী, মোক্ষদায়িনী',
    img: 'ganga.webp',
  },
  narmada: {
    name: 'শ্রী নর্মদা',
    english: 'Shri Narmada',
    emoji: '💧',
    color: '#039BE5',
    desc: 'রেবা মাতা, পুণ্যদায়িনী',
    img: 'narmada.webp',
  },
  shakambhari: {
    name: 'শ্রী শাকম্ভরী',
    english: 'Shri Shakambhari',
    emoji: '🥬',
    color: '#7CB342',
    desc: 'অন্ন ও উদ্ভিদের পোষক দেবী',
    img: 'shakambhari.webp',
  },
  lalita_shakambhari: {
    name: 'শ্রী ললিতা শাকম্ভরী',
    english: 'Shri Lalita Shakambhari',
    emoji: '🌼',
    color: '#8BC34A',
    desc: 'ললিতা ও শাকম্ভরীর সমন্বিত রূপ',
    img: 'lalita_shakambhari.webp',
  },
  rani_sati: {
    name: 'শ্রী রাণী সতী',
    english: 'Shri Rani Sati',
    emoji: '🏵️',
    color: '#8E24AA',
    desc: 'লোকআস্থার পূজ্য মাতৃশক্তি',
    img: 'rani_sati.webp',
  },
  neem_karoli_baba: {
    name: 'নীম করোলি বাবা',
    english: 'Neem Karoli Baba',
    emoji: '🙏',
    color: '#FF9800',
    desc: 'ভক্তি, সেবা ও প্রেমের সাধু',
    img: 'neem_karoli_baba.webp',
  },
  ravidas: {
    name: 'শ্রী রবিদাস',
    english: 'Shri Ravidas',
    emoji: '🙏',
    color: '#8D6E63',
    desc: 'ভক্তি সন্ত, সমতার বার্তা',
    img: 'ravidas.webp',
  },
  baba_gangaram: {
    name: 'শ্রী বাবা গঙ্গারাম',
    english: 'Shri Baba Gangaram',
    emoji: '🛕',
    color: '#6A1B9A',
    desc: 'লোকশ্রদ্ধার পূজ্য সাধু',
    img: 'baba_gangaram.webp',
  },
  ramdev: {
    name: 'শ্রী রামদেব',
    english: 'Shri Ramdev',
    emoji: '🐎',
    color: '#8E24AA',
    desc: 'লোকদেব, জনকল্যাণকারী',
    img: 'ramdev.webp',
  },
  jaharveer: {
    name: 'শ্রী জাহরবীর',
    english: 'Shri Jaharveer',
    emoji: '🏇',
    color: '#795548',
    desc: 'লোকরক্ষক, বীর দেব',
    img: 'jaharveer.webp',
  },
  gorakh_nath: {
    name: 'শ্রী গোরখনাথ',
    english: 'Shri Gorakh Nath',
    emoji: '🧘',
    color: '#607D8B',
    desc: 'নাথ যোগ পরম্পরার আচার্য',
    img: 'gorakh_nath.webp',
  },
};
