// ============ DATA ============
const deities = {
  ganesh: {
    name: 'ಶ್ರೀ ಗಣೇಶ',
    english: 'Shri Ganesh',
    emoji: '🐘',
    color: '#FF6B00',
    desc: 'ವಿಘ್ನಹರ್ತಾ, ಪ್ರಥಮ ಪೂಜ್ಯ',
    img: 'icons/ganesh.webp',
  },
  shiva: {
    name: 'ಶ್ರೀ ಶಿವ',
    english: 'Shri Shiv',
    emoji: '🔱',
    color: '#4169E1',
    desc: 'ಮಹಾದೇವ, ಭೋಲನಾಥ, ಸಂಹಾರಕ',
    img: 'icons/shiv.webp',
  },
  parvati: {
    name: 'ಶ್ರೀ ಪಾರ್ವತೀ ದೇವಿ',
    english: 'Shri Parvati',
    emoji: '🪷',
    color: '#AD1457',
    desc: 'ಶಿವನ ಅರ್ಧಾಂಗಿನಿ, ಶಕ್ತಿ ಮತ್ತು ಮಾತೃತ್ವದ ದೇವಿ',
    img: 'icons/parvati.webp',
  },
  vishnu: {
    name: 'ಶ್ರೀ ವಿಷ್ಣು',
    english: 'Shri Vishnu',
    emoji: '✨',
    color: '#0080FF',
    desc: 'ಪಾಲನಹಾರ, ನಾರಾಯಣ, ಜಗತ್ತಿನ ಪಾಲಕ',
    img: 'icons/vishnu.webp',
  },
  lakshmi: {
    name: 'ಶ್ರೀ ಲಕ್ಷ್ಮೀ',
    english: 'Shri Lakshmi',
    emoji: '🪷',
    color: '#FFD700',
    desc: 'ಧನದಾತ್ರೀ, ಕಮಲವಾಸಿನಿ, ಸಮೃದ್ಧಿಯ ದೇವಿ',
    img: 'icons/lakshmi.webp',
  },
  durga: {
    name: 'ಶ್ರೀ ದುರ್ಗೆ',
    english: 'Shri Durga',
    emoji: '🌸',
    color: '#FF1493',
    desc: 'ಆದಿಶಕ್ತಿ, ಮಹಾಮಾಯೆ, ಸಿಂಹವಾಹಿನಿ',
    img: 'icons/durga.webp',
  },
  kali: {
    name: 'ಶ್ರೀ ಕಾಳಿ',
    english: 'Shri Kali',
    emoji: '⚡',
    color: '#800080',
    desc: 'ಮಹಾಕಾಳಿ, ತಾರಾ, ಆದ್ಯಶಕ್ತಿಯ ಉಗ್ರ ರೂಪ',
    img: 'icons/kali.webp',
  },
  ram: {
    name: 'ಶ್ರೀ ರಾಮ',
    english: 'Shri Ram',
    emoji: '🏹',
    color: '#00AA00',
    desc: 'ಮರ್ಯಾದಾ ಪುರುಷೋತ್ತಮ, ರಘುಕುಲದ ಭೂಷಣ',
    img: 'icons/ram.webp',
  },
  hanuman: {
    name: 'ಶ್ರೀ ಹನುಮಾನ್',
    english: 'Shri Hanuman',
    emoji: '🙏',
    color: '#FF4500',
    desc: 'ಪವನಪುತ್ರ, ಬಜರಂಗಬಲಿ, ರಾಮಭಕ್ತ ಶಿರೋಮಣಿ',
    img: 'icons/hanuman.webp',
  },
  balaji: {
    name: 'ಶ್ರೀ ಬಾಲಾಜಿ',
    english: 'Shri Balaji',
    emoji: '🏹',
    color: '#8D6E63',
    desc: 'ಸಂಕಟಮೋಚಕ, ಪೂಜ್ಯ ಸ್ವರೂಪ',
    img: 'icons/balaji.webp',
  },
  pretraj_sarkar: {
    name: 'ಶ್ರೀ ಪ್ರೇತರಾಜ ಸರ್ಕಾರ್',
    english: 'Shri Pretraj Sarkar',
    emoji: '🔥',
    color: '#4E342E',
    desc: 'ನಕಾರಾತ್ಮಕ ಅಡ್ಡಿಗಳನ್ನು ನಿವಾರಿಸುವವರು',
    img: 'icons/pretraj_sarkar.webp',
  },
  krishna: {
    name: 'ಶ್ರೀ ಕೃಷ್ಣ',
    english: 'Shri Krishna',
    emoji: '🪈',
    color: '#0000CD',
    desc: 'ಗೋವಿಂದ, ಮುರಳೀಮನೋಹರ, ವೃಂದಾವನದ ವಿಹಾರಿ',
    img: 'icons/krishna.webp',
    geeta: typeof geetaData !== 'undefined' ? geetaData.krishna : null,
  },
  khatu_shyam: {
    name: 'ಶ್ರೀ ಖಾಟು ಶ್ಯಾಮ್',
    english: 'Shri Khatu Shyam',
    emoji: '🏹',
    color: '#FF4500',
    desc: 'ಪರಾಭವಗೊಂಡವರಿಗೆ ಆಸರೆ, ಮೋರ್ವಿ ನಂದನ, ಕಲಿಯುಗದ ಅವತಾರ',
    img: 'icons/khatu_shyam.webp',
  },
  tirupati_balaji: {
    name: 'ಶ್ರೀ ತಿರುಪತಿ ಬಾಲಾಜಿ',
    english: 'Tirupati Bala Ji',
    emoji: '🌟',
    color: '#FFD54F',
    desc: 'ಶ್ರೀ ವೆಂಕಟೇಶ್ವರ, ವಿಷ್ಣುವಿನ ಪೂಜ್ಯ ಸ್ವರೂಪ',
    img: 'icons/tirupati_balaji.webp',
  },
  jagannath: {
    name: 'ಶ್ರೀ ಜಗನ್ನಾಥ',
    english: 'Jagannath',
    emoji: '🕉️',
    color: '#4CAF50',
    desc: 'ಪುರಿಯ ಪ್ರಸಿದ್ಧ ದೇವತೆ, ಭಗವಾನ್ ವಿಷ್ಣುವಿನ ರೂಪ ಮತ್ತು ಭಕ್ತಿಯ ಪ್ರತೀಕ',
    img: 'icons/jagannath.webp',
  },
  gopal: {
    name: 'ಶ್ರೀ ಗೋಪಾಲ',
    english: 'Shri Gopal',
    emoji: '🐄',
    color: '#5C6BC0',
    desc: 'ಬಾಲ ಗೋವಿಂದ, ಗೋಪಾಲಕ, ಕರುಣಾಮಯ',
    img: 'icons/gopal.webp',
  },
  surya: {
    name: 'ಶ್ರೀ ಸೂರ್ಯ',
    english: 'Shri Surya',
    emoji: '☀️',
    color: '#FF8C00',
    desc: 'ಪ್ರತ್ಯಕ್ಷ ದೇವ, ಜಗತ್ತಿನ ನೇತ್ರ, ಶಕ್ತಿಯ ಮೂಲ',
    img: 'icons/surya.webp',
  },
  shani: {
    name: 'ಶ್ರೀ ಶನಿ ದೇವರು',
    english: 'Shri Shani Dev',
    emoji: '⚖️',
    color: '#1a1a1a',
    desc: 'ಕರ್ಮಫಲದಾತ, ಸೂರ್ಯಪುತ್ರ, ನ್ಯಾಯದ ದೇವರು',
    img: 'icons/shani.webp',
  },
  brihaspati: {
    name: 'ಶ್ರೀ ಬೃಹಸ್ಪತಿ ದೇವರು',
    english: 'Shri Brihaspati Dev',
    emoji: '📜',
    color: '#EF6C00',
    desc: 'ವೇದಜ್ಞ, ಗುರು, ನ್ಯಾಯದ ದೇವರು',
    img: 'icons/brihaspati.webp',
  },
  brahma: {
    name: 'ಶ್ರೀ ಬ್ರಹ್ಮಾ',
    english: 'Shri Brahma',
    emoji: '📜',
    color: '#EF6C00',
    desc: 'ಸೃಷ್ಟಿಕರ್ತ, ವೇದಜ್ಞ, ಚತುರ್ಮುಖ',
    img: 'icons/brahma.webp',
  },
  saraswati: {
    name: 'ಶ್ರೀ ಸರಸ್ವತಿ',
    english: 'Shri Saraswati',
    emoji: '🎵',
    color: '#FFFFFF',
    desc: 'ವಿದ್ಯಾದಾಯಿನಿ, ವಾಗ್ದೇವಿ, ವೀಣಾವಾದಿನಿ',
    img: 'icons/saraswati.webp',
  },
  bhairav: {
    name: 'ಶ್ರೀ ಭೈರವ',
    english: 'Shri Bhairav',
    emoji: '🐕',
    color: '#37474F',
    desc: 'ಕ್ಷೇತ್ರಪಾಲ, ರಕ್ಷಕ, ಉಗ್ರ ಕರುಣಾಮಯ',
    img: 'icons/bhairav.webp',
  },
  batuk_bhairav: {
    name: 'ಶ್ರೀ ಬಟುಕ ಭೈರವ',
    english: 'Shri Batuk Bhairav',
    emoji: '🛡️',
    color: '#455A64',
    desc: 'ಬಾಲ ಭೈರವ, ತ್ವರಿತ ರಕ್ಷಕ',
    img: 'icons/batuk_bhairav.webp',
  },
  parshuram: {
    name: 'ಶ್ರೀ ಪರಶುರಾಮ',
    english: 'Shri Parshuram',
    emoji: '🪓',
    color: '#5D4037',
    desc: 'ವಿಷ್ಣುವಿನ ಅವತಾರ, ಧರ್ಮರಕ್ಷಕ',
    img: 'icons/parshuram.webp',
  },
  giriraj: {
    name: 'ಶ್ರೀ ಗಿರಿರಾಜ',
    english: 'Shri Giriraj',
    emoji: '⛰️',
    color: '#7CB342',
    desc: 'ಗೋವರ್ಧನ ಸ್ವರೂಪ, ಶರಣದಾತ',
    img: 'icons/giriraj.webp',
  },
  navgrah: {
    name: 'ಶ್ರೀ ನವಗ್ರಹ',
    english: 'Shri Navgrah',
    emoji: '🪐',
    color: '#546E7A',
    desc: 'ಒಂಬತ್ತು ಗ್ರಹಗಳ ಸಮಷ್ಟಿ ಪೂಜೆ',
    img: 'icons/navgrah.webp',
  },
  vishwakarma: {
    name: 'ಶ್ರೀ ವಿಶ್ವಕರ್ಮ',
    english: 'Shri Vishwakarma',
    emoji: '🛠️',
    color: '#6D4C41',
    desc: 'ದೇವ ಶಿಲ್ಪಿ, ನಿರ್ಮಾಣದ ದೇವರು',
    img: 'icons/vishwakarma.webp',
  },
  sai: {
    name: 'ಶ್ರೀ ಸಾಯಿ',
    english: 'Shri Sai',
    emoji: '🕯️',
    color: '#9E9D24',
    desc: 'ಶ್ರದ್ಧೆ ಮತ್ತು ಸಬೂರಿಯ ಪ್ರತೀಕ',
    img: 'icons/sai.webp',
  },
  mahavir: {
    name: 'ಶ್ರೀ ಮಹಾವೀರ',
    english: 'Shri Mahavir',
    emoji: '🪷',
    color: '#26A69A',
    desc: 'ಅಹಿಂಸೆ, ತಪಸ್ಸು ಮತ್ತು ಸತ್ಯದ ಆದರ್ಶ',
    img: 'icons/mahavir.webp',
  },
  pitar: {
    name: 'ಶ್ರೀ ಪಿತೃದೇವ',
    english: 'Shri Pitar',
    emoji: '🕯',
    color: '#6D4C41',
    desc: 'ಪೂರ್ವಜ ಪೂಜೆ, ಕುಲ ಆಶೀರ್ವಾದ',
    img: 'icons/pitar.webp',
  },
  vaishno_devi: {
    name: 'ಶ್ರೀ ವೈಷ್ಣೋ ದೇವಿ',
    english: 'Shri Vaishno Devi',
    emoji: '🛕',
    color: '#C2185B',
    desc: 'ತ್ರಿಕೂಟ ವಾಸಿನಿ, ಶಕ್ತಿಸ್ವರೂಪಿಣಿ',
    img: 'icons/vaishno_devi.webp',
  },
  sheetla: {
    name: 'ಶ್ರೀ ಶೀತಲಾ',
    english: 'Shri Sheetla',
    emoji: '🧺',
    color: '#00ACC1',
    desc: 'ಆರೋಗ್ಯದಾಯಿನಿ ಮಾತೆ',
    img: 'icons/sheetla.webp',
  },
  mahakali: {
    name: 'ಶ್ರೀ ಮಹಾಕಾಳಿ',
    english: 'Shri Mahakali',
    emoji: '⚔️',
    color: '#283593',
    desc: 'ಕಾಲವಿನಾಶಿನಿ, ಅಜೇಯ ಶಕ್ತಿ',
    img: 'icons/mahakali.webp',
  },
  baglamukhi: {
    name: 'ಶ್ರೀ ಬಗಲಾಮುಖಿ',
    english: 'Shri Baglamukhi',
    emoji: '🟡',
    color: '#FBC02D',
    desc: 'ದಶಮಹಾವಿದ್ಯೆ, ಸ್ತಂಭನ ಶಕ್ತಿ',
    img: 'icons/baglamukhi.webp',
  },
  mahalakshmi: {
    name: 'ಶ್ರೀ ಮಹಾಲಕ್ಷ್ಮೀ',
    english: 'Shri Mahalakshmi',
    emoji: '💰',
    color: '#F9A825',
    desc: 'ಐಶ್ವರ್ಯ, ಸೌಭಾಗ್ಯ, ಮಂಗಳಮಯಿ',
    img: 'icons/mahalakshmi.webp',
  },
  gayatri: {
    name: 'ಶ್ರೀ ಗಾಯತ್ರಿ',
    english: 'Shri Gayatri',
    emoji: '📿',
    color: '#FF7043',
    desc: 'ವೇದಮಾತೆ, ಬುದ್ಧಿ ಪ್ರದಾಯಿನಿ',
    img: 'icons/gayatri.webp',
  },
  sharda: {
    name: 'ಶ್ರೀ ಶಾರದಾ',
    english: 'Shri Sharda',
    emoji: '📖',
    color: '#5E35B1',
    desc: 'ಜ್ಞಾನ ಮತ್ತು ವಾಣಿಯ ಸ್ವರೂಪ',
    img: 'icons/sharda.webp',
  },
  radha: {
    name: 'ಶ್ರೀ ರಾಧಾ',
    english: 'Shri Radha',
    emoji: '🌸',
    color: '#EC407A',
    desc: 'ಭಕ್ತಿ ಮತ್ತು ಪ್ರೀತಿಯ ಅಧಿಷ್ಠಾತ್ರಿ',
    img: 'icons/radha.webp',
  },
  santoshi_maa: {
    name: 'ಶ್ರೀ ಸಂತೋಷಿ ಮಾತೆ',
    english: 'Shri Santoshi Maa',
    emoji: '🍚',
    color: '#F06292',
    desc: 'ಸಂತೋಷ, ಸುಖ ಮತ್ತು ಸರಳ ಭಕ್ತಿ',
    img: 'icons/santoshi_maa.webp',
  },
  vindhyeshwari: {
    name: 'ಶ್ರೀ ವಿಂಧ್ಯೇಶ್ವರಿ',
    english: 'Shri Vindhyeshwari',
    emoji: '🌺',
    color: '#D81B60',
    desc: 'ವಿಂಧ್ಯವಾಸಿನಿ ಮಾತೆಯ ಸ್ವರೂಪ',
    img: 'icons/vindhyeshwari.webp',
  },
  annapurna: {
    name: 'ಶ್ರೀ ಅನ್ನಪೂರ್ಣಾ',
    english: 'Shri Annapurna',
    emoji: '🍲',
    color: '#FF8F00',
    desc: 'ಅನ್ನ, ಪೋಷಣೆ ಮತ್ತು ಕರುಣೆಯ ದೇವಿ',
    img: 'icons/annapurna.webp',
  },
  chhathi_maiya: {
    name: 'ಛಠಿ ಮೈಯಾ',
    english: 'Chhathi Maiya',
    emoji: '🌅',
    color: '#FF6F00',
    desc: 'ಸೂರ್ಯ ಆರಾಧನೆ, ಸಂತಾನ ಸುಖ ಮತ್ತು ಸಮೃದ್ಧಿಯ ದೇವತೆ',
    img: 'icons/chhathi_maiya.webp',
  },
  tulsi: {
    name: 'ಶ್ರೀ ತುಳಸಿ',
    english: 'Shri Tulsi',
    emoji: '🌿',
    color: '#43A047',
    desc: 'ಪವಿತ್ರತೆ, ಭಕ್ತಿ ಮತ್ತು ರಕ್ಷಣೆ',
    img: 'icons/tulsi.webp',
  },
  ganga: {
    name: 'ಶ್ರೀ ಗಂಗಾ',
    english: 'Shri Ganga',
    emoji: '🌊',
    color: '#1E88E5',
    desc: 'ಪವಿತ್ರ ನದಿ, ಮೋಕ್ಷದಾಯಿನಿ',
    img: 'icons/ganga.webp',
  },
  narmada: {
    name: 'ಶ್ರೀ ನರ್ಮದಾ',
    english: 'Shri Narmada',
    emoji: '💧',
    color: '#039BE5',
    desc: 'ರೇವಾ ಮಾತೆ, ಪುಣ್ಯದಾಯಿನಿ',
    img: 'icons/narmada.webp',
  },
  shakambhari: {
    name: 'ಶ್ರೀ ಶಾಕಂಭರಿ',
    english: 'Shri Shakambhari',
    emoji: '🥬',
    color: '#7CB342',
    desc: 'ಅನ್ನ ಮತ್ತು ಸಸ್ಯಗಳ ಪೋಷಕಿ ದೇವಿ',
    img: 'icons/shakambhari.webp',
  },
  lalita_shakambhari: {
    name: 'ಶ್ರೀ ಲಲಿತಾ ಶಾಕಂಭರಿ',
    english: 'Shri Lalita Shakambhari',
    emoji: '🌼',
    color: '#8BC34A',
    desc: 'ಲಲಿತಾ ಮತ್ತು ಶಾಕಂಭರಿಯ ಸಂಯುಕ್ತ ರೂಪ',
    img: 'icons/lalita_shakambhari.webp',
  },
  rani_sati: {
    name: 'ಶ್ರೀ ರಾಣಿ ಸತಿ',
    english: 'Shri Rani Sati',
    emoji: '🏵️',
    color: '#8E24AA',
    desc: 'ಜನಆಸ್ಥೆಯ ಪೂಜ್ಯ ಮಾತೃಶಕ್ತಿ',
    img: 'icons/rani_sati.webp',
  },
  neem_karoli_baba: {
    name: 'ನೀಮ್ ಕರೋಲಿ ಬಾಬಾ',
    english: 'Neem Karoli Baba',
    emoji: '🙏',
    color: '#FF9800',
    desc: 'ಭಕ್ತಿ, ಸೇವೆ ಮತ್ತು ಪ್ರೀತಿಯ ಸಂತ',
    img: 'icons/neem_karoli_baba.webp',
  },
  ravidas: {
    name: 'ಶ್ರೀ ರವಿದಾಸ',
    english: 'Shri Ravidas',
    emoji: '🙏',
    color: '#8D6E63',
    desc: 'ಭಕ್ತ ಸಂತ, ಸಮತೆಯ ಸಂದೇಶ',
    img: 'icons/ravidas.webp',
  },
  baba_gangaram: {
    name: 'ಶ್ರೀ ಬಾಬಾ ಗಂಗಾರಾಮ',
    english: 'Shri Baba Gangaram',
    emoji: '🛕',
    color: '#6A1B9A',
    desc: 'ಜನಶ್ರದ್ಧೆಯ ಪೂಜ್ಯ ಸಂತ',
    img: 'icons/baba_gangaram.webp',
  },
  ramdev: {
    name: 'ಶ್ರೀ ರಾಮದೇವ್',
    english: 'Shri Ramdev',
    emoji: '🐎',
    color: '#8E24AA',
    desc: 'ಜನದೇವರು, ಜನಕಲ್ಯಾಣಕಾರಿ',
    img: 'icons/ramdev.webp',
  },
  jaharveer: {
    name: 'ಶ್ರೀ ಜಹಾರವೀರ್',
    english: 'Shri Jaharveer',
    emoji: '🏇',
    color: '#795548',
    desc: 'ಜನರಕ್ಷಕ, ವೀರ ದೇವ',
    img: 'icons/jaharveer.webp',
  },
  gorakh_nath: {
    name: 'ಶ್ರೀ ಗೋರಖನಾಥ',
    english: 'Shri Gorakh Nath',
    emoji: '🧘',
    color: '#607D8B',
    desc: 'ನಾಥ ಯೋಗ ಪರಂಪರೆಯ ಆಚಾರ್ಯ',
    img: 'icons/gorakh_nath.webp',
  },
};
