// ============ TEMPLES DATA ============

const templesData = [
  {
    id: 'kedarnath',
    name: 'केदारनाथ मंदिर',
    nameEn: 'Kedarnath Temple',
    state: 'उत्तराखंड',
    deity: 'शिव',
    type: 'Jyotirlinga',
    emoji: '🏔️',
    desc: 'हिमालय की गोद में स्थित 12 ज्योतिर्लिंगों में एक, 3,583 मीटर की ऊँचाई पर।',
    history:
      "उत्तराखण्ड के गढ़वाल हिमालय में मंदाकिनी नदी के किनारे समुद्र तल से लगभग 3,580 मीटर (लगभग 11,750 फीट) की ऊँचाई पर स्थित एक प्राचीन और अत्यंत पवित्र शिव मंदिर है, जो हिंदुओं के लिए महत्त्वपूर्ण तीर्थ स्थलों में से एक माना जाता है। यह मंदिर मुख्यतः भगवान शिव को समर्पित है और हिंदू धर्म में इसका गहरा धार्मिक व सांस्कृतिक महत्त्व है। केदारनाथ मंदिर का इतिहास बहुत पुराना है और इसे पौराणिक कथाओं से जोड़ा जाता है। कहा जाता है कि यह मंदिर भगवान शिव के बारह ज्योतिर्लिंगों में से एक है, जो कि शिव के दिव्य रूपों को दर्शाते हैं। केदारनाथ का नाम 'केदार' शब्द से आया है, जिसका अर्थ होता है 'काले रंग का' और यह भगवान शिव के काले रंग के रूप को दर्शाता है।<br/><br/>🕉️ पौराणिक कथा और प्रारंभिक मान्यता<br/>महाभारत से जुड़ी कथा: प्रचलित मान्यता के अनुसार, महाभारत युद्ध के बाद पांडव भाइयों ने अपने पापों के प्रायश्चित के लिए भगवान शिव की खोज की। जब शिव उनसे बचते हुए हिमालय में केदार पहुँचे, तब उन्होंने भैंसे का रूप धारण कर लिया। पांडवों ने शिव को पहचान कर प्रार्थना की, और शिव ने प्रसन्न होकर यहाँ स्वयंभू (स्वतः प्रकट) शिवलिंग के रूप में वास करने का वरदान दिया। इसी स्थान पर केदारनाथ मंदिर का मौलिक पवित्र स्थल माना जाता है।<br/>इस कथा के अनुसार, इस स्थान पर भगवान विष्णु के अवतार नर और नारायण की तपस्या से शिव प्रसन्न हुए और उन्होंने यहीं ज्योतिर्लिंग के रूप में वास करने का निर्णय लिया।<br/><br/>🛕 मंदिर का निर्माण और इतिहास<br/>मूल मंदिर: कुछ मान्यताओं के अनुसार मंदिर का मूल रूप पांडवों द्वारा बनाया गया था, लेकिन इसका कोई ठोस लिखित ऐतिहासिक प्रमाण उपलब्ध नहीं है।<br/>आदि शंकराचार्य का योगदान: इतिहासकारों और पुराण कथाओं के अनुसार वर्तमान मंदिर की आज दिखाई देने वाली संरचना ८वीं सदी (लगभग 1200 साल पहले) में महान दार्शनिक और संत आदि शंकराचार्य ने पुन: बनवाई या जीर्णोद्धार कराया था। इससे यह प्रमुख तीर्थ स्थल बना और उसकी प्रतिष्ठा बनी।<br/><br/>🔱 ज्योतिर्लिंग और धार्मिक महत्व<br/>केदारनाथ मंदिर को भगवान शिव के 12 ज्योतिर्लिंगों में से एक माना जाता है — यह हिंदू धर्म में शिव के सबसे पवित्र स्वरूपों में से एक है।<br/>यह छोटा चारधाम यात्रा का एक महत्वपूर्ण हिस्सा भी है, जहाँ उत्तर भारत से लाखों श्रद्धालु हर साल आते हैं।<br/><br/>🏔️ प्राकृतिक और मानव इतिहास - यह मंदिर हिमालय की ऊँचाइयों में स्थित है और 2013 में आई भीषण उत्तराखंड बाढ़ में मंदिर को वहीँ अचल खड़ा पाया गया था, जबकि आसपास का समुदाय भारी विनाश का सामना कर रहा था। इसने उसके प्रति श्रद्धा और अटूट विश्वास को और भी मजबूत किया।",
    timings: 'अप्रैल-नवंबर: 6AM – 3PM, 5PM – 9PM',
    bestTime: 'मई–जून, सितंबर–अक्टूबर',
    location: 'रुद्रप्रयाग, उत्तराखंड',
    mapQuery: 'Kedarnath+Temple+Uttarakhand',
    color: '#4FC3F7',
    gradient:
      'linear-gradient(135deg, rgba(79,195,247,0.15), rgba(30,136,229,0.08))',
  },
  {
    id: 'somnath',
    name: 'सोमनाथ मंदिर',
    nameEn: 'Somnath Temple',
    state: 'गुजरात',
    deity: 'शिव',
    type: 'Jyotirlinga',
    emoji: '🌊',
    desc: '12 ज्योतिर्लिंगों में प्रथम, अरब सागर के तट पर स्थित शिवजी का पवित्र धाम।',
    history:
      'सोमनाथ मंदिर को कई बार आक्रमणकारियों ने नष्ट किया और हर बार इसे पुनर्निर्मित किया गया।',
    timings: '6AM – 10PM (आरती: 7AM, 12PM, 7PM)',
    bestTime: 'अक्टूबर–मार्च',
    location: 'प्रभास पाटन, सोमनाथ, गुजरात',
    mapQuery: 'Somnath+Temple+Gujarat',
    color: '#81C784',
    gradient:
      'linear-gradient(135deg, rgba(129,199,132,0.15), rgba(56,142,60,0.08))',
  },
  {
    id: 'vaishno_devi',
    name: 'वैष्णो देवी मंदिर',
    nameEn: 'Vaishno Devi Temple',
    state: 'जम्मू & कश्मीर',
    deity: 'दुर्गा',
    type: 'Shakti Peeth',
    emoji: '⛰️',
    desc: 'त्रिकुट पर्वत पर स्थित माँ वैष्णो देवी का पवित्र गुफा मंदिर।',
    history:
      'यह मंदिर त्रेतायुग से पूजित है। माँ वैष्णो देवी ने यहाँ तपस्या की थी।',
    timings: '24 घंटे खुला (यात्रा पास अनिवार्य)',
    bestTime: 'मार्च–मई, अक्टूबर–नवंबर',
    location: 'कटरा, जम्मू, J&K',
    mapQuery: 'Vaishno+Devi+Temple+Katra',
    color: '#F48FB1',
    gradient:
      'linear-gradient(135deg, rgba(244,143,177,0.15), rgba(194,24,91,0.08))',
  },
  {
    id: 'tirupati',
    name: 'तिरुपति बालाजी',
    nameEn: 'Tirupati Balaji',
    state: 'आंध्र प्रदेश',
    deity: 'विष्णु',
    type: 'Vaishnava',
    emoji: '🌟',
    desc: 'विश्व का सबसे अमीर और सर्वाधिक दर्शनार्थियों वाला मंदिर — भगवान वेंकटेश्वर का धाम।',
    history:
      'यह मंदिर 300 ई. के आसपास बना। यहाँ प्रकाश के देवता वेंकटेश्वर की पूजा होती है।',
    timings: '2:30AM – 1:30AM (22 घंटे खुला)',
    bestTime: 'सितंबर–फरवरी (ब्रह्मोत्सव में)',
    location: 'तिरुमाला, चित्तूर, आंध्र प्रदेश',
    mapQuery: 'Tirupati+Balaji+Temple+Andhra+Pradesh',
    color: '#FFD54F',
    gradient:
      'linear-gradient(135deg, rgba(255,213,79,0.15), rgba(255,160,0,0.08))',
  },
  {
    id: 'rameshwaram',
    name: 'रामेश्वरम मंदिर',
    nameEn: 'Rameshwaram Temple',
    state: 'तमिलनाडु',
    deity: 'शिव',
    type: 'Jyotirlinga',
    emoji: '🏝️',
    desc: 'चार धाम में से एक, रामनाथस्वामी मंदिर – भगवान राम द्वारा स्थापित शिवलिंग।',
    history:
      'रावण वध के पाप से मुक्ति के लिए भगवान राम ने यहाँ शिवलिंग स्थापित किया था।',
    timings: '5AM – 1PM, 3PM – 9PM',
    bestTime: 'अक्टूबर–मार्च',
    location: 'रामनाथपुरम, तमिलनाडु',
    mapQuery: 'Ramanathaswamy+Temple+Rameswaram',
    color: '#80DEEA',
    gradient:
      'linear-gradient(135deg, rgba(128,222,234,0.15), rgba(0,151,167,0.08))',
  },
  {
    id: 'kashi_vishwanath',
    name: 'काशी विश्वनाथ',
    nameEn: 'Kashi Vishwanath',
    state: 'उत्तर प्रदेश',
    deity: 'शिव',
    type: 'Jyotirlinga',
    emoji: '🪔',
    desc: 'वाराणसी में गंगा तट पर स्थित 12 ज्योतिर्लिंगों में से एक।',
    history:
      'मूल मंदिर औरंगज़ेब ने नष्ट किया था। 1780 में अहिल्याबाई होलकर ने वर्तमान मंदिर बनवाया।',
    timings: '3AM – 11PM',
    bestTime: 'नवंबर–मार्च, देव दीपावली',
    location: 'वाराणसी, उत्तर प्रदेश',
    mapQuery: 'Kashi+Vishwanath+Temple+Varanasi',
    color: '#FFAB91',
    gradient:
      'linear-gradient(135deg, rgba(255,171,145,0.15), rgba(230,74,25,0.08))',
  },
  {
    id: 'jagannath',
    name: 'जगन्नाथ पुरी',
    nameEn: 'Jagannath Puri',
    state: 'ओडिशा',
    deity: 'कृष्ण और जगन्नाथ',
    type: 'Vaishnava',
    emoji: '🛕',
    desc: 'चार धामों में से एक — भगवान जगन्नाथ, बलभद्र और सुभद्रा का प्रसिद्ध मंदिर।',
    history:
      'यह मंदिर 12वीं शताब्दी में राजा अनंतवर्मन् चोडगंग देव ने बनवाया था।',
    timings: '5AM – 11PM (गैर-हिंदुओं को अनुमति नहीं)',
    bestTime: 'जुलाई में रथयात्रा, अक्टूबर–फरवरी',
    location: 'पुरी, ओडिशा',
    mapQuery: 'Jagannath+Temple+Puri+Odisha',
    color: '#CE93D8',
    gradient:
      'linear-gradient(135deg, rgba(206,147,216,0.15), rgba(106,27,154,0.08))',
  },
  {
    id: 'dwarka',
    name: 'द्वारकाधीश मंदिर',
    nameEn: 'Dwarkadhish Temple',
    state: 'गुजरात',
    deity: 'कृष्ण',
    type: 'Vaishnava',
    emoji: '🌅',
    desc: 'चार धामों में से एक — भगवान कृष्ण की द्वारका नगरी में जगत मंदिर।',
    history:
      'यह मंदिर 2,500 वर्ष पुराना माना जाता है। भगवान कृष्ण ने यहाँ अपनी राजधानी स्थापित की थी।',
    timings: '6:30AM – 1PM, 5PM – 9:30PM',
    bestTime: 'अक्टूबर–मार्च, जन्माष्टमी',
    location: 'द्वारका, गुजरात',
    mapQuery: 'Dwarkadhish+Temple+Dwarka+Gujarat',
    color: '#A5D6A7',
    gradient:
      'linear-gradient(135deg, rgba(165,214,167,0.15), rgba(27,94,32,0.08))',
  },
  {
    id: 'krishna_janmabhoomi',
    name: 'श्री कृष्ण जन्मभूमि मंदिर',
    nameEn: 'Shri Krishna Janmabhoomi Temple',
    state: 'उत्तर प्रदेश',
    deity: 'कृष्ण',
    type: 'Vaishnava',
    emoji: '🪷',
    desc: 'भगवान कृष्ण का जन्मस्थान — मथुरा का अत्यंत पवित्र तीर्थ।',
    history:
      'यह स्थल प्राचीन काल से कृष्ण जन्मस्थली के रूप में पूजित है और समय-समय पर मंदिर का पुनर्निर्माण हुआ।',
    timings: '5AM – 12PM, 4PM – 9:30PM',
    bestTime: 'जन्माष्टमी, अक्टूबर–मार्च',
    location: 'मथुरा, उत्तर प्रदेश',
    mapQuery: 'Shri+Krishna+Janmabhoomi+Temple+Mathura',
    color: '#64B5F6',
    gradient:
      'linear-gradient(135deg, rgba(100,181,246,0.15), rgba(25,118,210,0.08))',
  },
  {
    id: 'banke_bihari',
    name: 'बांके बिहारी मंदिर',
    nameEn: 'Banke Bihari Temple',
    state: 'उत्तर प्रदेश',
    deity: 'कृष्ण',
    type: 'Vaishnava',
    emoji: '🎵',
    desc: 'वृंदावन का अत्यंत प्रसिद्ध राधा-कृष्ण मंदिर।',
    history:
      'यह मंदिर स्वामी हरिदास की परंपरा से जुड़ा है और ठाकुरजी की मनमोहक सेवा-परंपरा के लिए प्रसिद्ध है।',
    timings: '7:45AM – 12PM, 5:30PM – 9:30PM',
    bestTime: 'जन्माष्टमी, होली, कार्तिक मास',
    location: 'वृंदावन, उत्तर प्रदेश',
    mapQuery: 'Banke+Bihari+Temple+Vrindavan',
    color: '#9575CD',
    gradient:
      'linear-gradient(135deg, rgba(149,117,205,0.15), rgba(81,45,168,0.08))',
  },
  {
    id: 'udupi_krishna',
    name: 'उडुपी श्री कृष्ण मंदिर',
    nameEn: 'Udupi Sri Krishna Temple',
    state: 'कर्नाटक',
    deity: 'कृष्ण',
    type: 'Vaishnava',
    emoji: '🌺',
    desc: 'दक्षिण भारत का प्रमुख कृष्ण मंदिर और माध्व परंपरा का महत्वपूर्ण केंद्र।',
    history:
      '13वीं शताब्दी में श्री माध्वाचार्य से जुड़ी परंपरा में यह मंदिर विशेष महत्व रखता है।',
    timings: '5AM – 9PM',
    bestTime: 'नवंबर–फरवरी, कृष्ण जन्माष्टमी',
    location: 'उडुपी, कर्नाटक',
    mapQuery: 'Udupi+Sri+Krishna+Temple+Karnataka',
    color: '#4DB6AC',
    gradient:
      'linear-gradient(135deg, rgba(77,182,172,0.15), rgba(0,121,107,0.08))',
  },
  {
    id: 'guruvayur_krishna',
    name: 'गुरुवायूर श्री कृष्ण मंदिर',
    nameEn: 'Guruvayur Sri Krishna Temple',
    state: 'केरल',
    deity: 'कृष्ण',
    type: 'Vaishnava',
    emoji: '🪔',
    desc: '“दक्षिण का द्वारका” कहलाने वाला प्राचीन और विख्यात कृष्ण धाम।',
    history:
      'गुरुवायूरप्पन की पूजा-परंपरा के कारण यह मंदिर सदियों से भक्ति का प्रमुख केंद्र रहा है।',
    timings: '3AM – 1:30PM, 4:30PM – 9:15PM',
    bestTime: 'नवंबर–फरवरी, एकादशी उत्सव',
    location: 'गुरुवायूर, त्रिशूर, केरल',
    mapQuery: 'Guruvayur+Sri+Krishna+Temple+Kerala',
    color: '#AED581',
    gradient:
      'linear-gradient(135deg, rgba(174,213,129,0.15), rgba(85,139,47,0.08))',
  },
  {
    id: 'iskcon_bengaluru',
    name: 'इस्कॉन मंदिर बेंगलुरु',
    nameEn: 'ISKCON Bangalore',
    state: 'कर्नाटक',
    deity: 'कृष्ण',
    type: 'Vaishnava',
    emoji: '🏙️',
    desc: 'आधुनिक और भव्य कृष्ण मंदिर, बेंगलुरु का प्रमुख आध्यात्मिक स्थल।',
    history:
      'ISKCON द्वारा विकसित यह मंदिर आधुनिक वास्तुशैली और भक्तिमय गतिविधियों के लिए प्रसिद्ध है।',
    timings: '4:15AM – 1PM, 4:15PM – 8:20PM',
    bestTime: 'जन्माष्टमी, वर्ष भर',
    location: 'राजाजीनगर, बेंगलुरु, कर्नाटक',
    mapQuery: 'ISKCON+Temple+Bangalore',
    color: '#90CAF9',
    gradient:
      'linear-gradient(135deg, rgba(144,202,249,0.15), rgba(21,101,192,0.08))',
  },
  {
    id: 'iskcon_london',
    name: 'ISKCON श्री श्री राधा लंदन मंदिर',
    nameEn: 'ISKCON Sri Sri Radha London Temple',
    state: 'UK',
    deity: 'Krishna',
    type: 'Vaishnava',
    emoji: '🇬🇧',
    desc: 'लंदन क्षेत्र का प्रसिद्ध कृष्ण मंदिर और वैश्विक ISKCON केंद्रों में प्रमुख।',
    history:
      'यूरोप में कृष्ण भक्ति के प्रसार में इस मंदिर की महत्वपूर्ण भूमिका रही है।',
    timings: 'Daily: 4:30AM – 8:30PM',
    bestTime: 'Janmashtami, Sunday festivals',
    location: 'London, United Kingdom',
    mapQuery: 'ISKCON+Sri+Sri+Radha+London+Temple',
    color: '#F48FB1',
    gradient:
      'linear-gradient(135deg, rgba(244,143,177,0.15), rgba(173,20,87,0.08))',
  },
  {
    id: 'bhaktivedanta_manor',
    name: 'भक्तिवेदांत मैनर',
    nameEn: 'Bhaktivedanta Manor',
    state: 'England',
    deity: 'Krishna',
    type: 'Vaishnava',
    emoji: '🏰',
    desc: 'इंग्लैंड का प्रमुख कृष्ण धाम, यूरोप में कृष्ण भक्तों का महत्वपूर्ण केंद्र।',
    history:
      'यह परिसर यूरोप में गौड़ीय वैष्णव परंपरा के विस्तार में ऐतिहासिक रूप से अत्यंत महत्वपूर्ण रहा है।',
    timings: 'Daily: 4:30AM – 8:30PM',
    bestTime: 'Janmashtami, summer festivals',
    location: 'Watford, England',
    mapQuery: 'Bhaktivedanta+Manor+Watford',
    color: '#CE93D8',
    gradient:
      'linear-gradient(135deg, rgba(206,147,216,0.15), rgba(123,31,162,0.08))',
  },
  {
    id: 'iskcon_usa',
    name: 'ISKCON श्री श्री राधा कृष्ण मंदिर',
    nameEn: 'ISKCON Sri Sri Radha Krishna Temple (USA)',
    state: 'USA',
    deity: 'Krishna',
    type: 'Vaishnava',
    emoji: '🇺🇸',
    desc: 'अमेरिका में प्रसिद्ध ISKCON राधा-कृष्ण मंदिर परंपरा का प्रतिनिधि केंद्र।',
    history:
      'USA में ISKCON केंद्रों ने श्रीकृष्ण भक्ति, कीर्तन और गीता प्रचार को व्यापक रूप से स्थापित किया।',
    timings: 'Daily: varies by center',
    bestTime: 'Janmashtami, weekend festivals',
    location: 'Spanish Fork, Utah, USA',
    mapQuery: 'ISKCON+Sri+Sri+Radha+Krishna+Temple+Spanish+Fork+Utah',
    color: '#81D4FA',
    gradient:
      'linear-gradient(135deg, rgba(129,212,250,0.15), rgba(2,136,209,0.08))',
  },
  {
    id: 'radha_radhanath_sa',
    name: 'श्री श्री राधा राधानाथ मंदिर',
    nameEn: 'Sri Sri Radha Radhanath Temple',
    state: 'South Africa',
    deity: 'Krishna',
    type: 'Vaishnava',
    emoji: '🇿🇦',
    desc: 'दक्षिण अफ्रीका का प्रसिद्ध राधा-कृष्ण मंदिर।',
    history:
      'दक्षिण अफ्रीका में वैष्णव भक्ति और कीर्तन परंपरा के प्रसार में इस केंद्र का उल्लेखनीय योगदान है।',
    timings: 'Daily: 4:30AM – 8:30PM',
    bestTime: 'Janmashtami, major Vaishnava festivals',
    location: 'Durban, South Africa',
    mapQuery: 'Sri+Sri+Radha+Radhanath+Temple+Durban',
    color: '#FFAB91',
    gradient:
      'linear-gradient(135deg, rgba(255,171,145,0.15), rgba(216,67,21,0.08))',
  },
  {
    id: 'wat_kanchanapisek',
    name: 'श्री कृष्ण मंदिर (वाट कंचनापिसेक)',
    nameEn: 'Sri Krishna Mandir (Wat Kanchanapisek)',
    state: 'Thailand',
    deity: 'Krishna',
    type: 'Vaishnava',
    emoji: '🇹🇭',
    desc: 'थाईलैंड में स्थित प्रसिद्ध कृष्ण मंदिर, अंतरराष्ट्रीय भक्त समुदाय का केंद्र।',
    history:
      'यह मंदिर दक्षिण-पूर्व एशिया में कृष्ण भक्ति के प्रसार का महत्वपूर्ण स्थल माना जाता है।',
    timings: 'Daily: 5AM – 8:30PM',
    bestTime: 'Janmashtami, major festival days',
    location: 'Bangkok, Thailand',
    mapQuery: 'Sri+Krishna+Mandir+Wat+Kanchanapisek+Thailand',
    color: '#FFCC80',
    gradient:
      'linear-gradient(135deg, rgba(255,204,128,0.15), rgba(239,108,0,0.08))',
  },
  {
    id: 'iskcon_australia',
    name: 'ISKCON श्री श्री राधा कृष्ण मंदिर',
    nameEn: 'ISKCON Sri Sri Radha Krishna Temple (Australia)',
    state: 'Australia',
    deity: 'Krishna',
    type: 'Vaishnava',
    emoji: '🇦🇺',
    desc: 'ऑस्ट्रेलिया का प्रमुख ISKCON राधा-कृष्ण मंदिर।',
    history:
      'ऑस्ट्रेलिया में कृष्ण भक्ति, संकीर्तन और वैदिक संस्कृति के प्रसार में ISKCON मंदिरों की महत्वपूर्ण भूमिका रही है।',
    timings: 'Daily: varies by center',
    bestTime: 'Janmashtami, Gaura Purnima',
    location: 'Sydney, New South Wales, Australia',
    mapQuery: 'ISKCON+Sri+Sri+Radha+Krishna+Temple+Sydney',
    color: '#B39DDB',
    gradient:
      'linear-gradient(135deg, rgba(179,157,219,0.15), rgba(94,53,177,0.08))',
  },
  {
    id: 'shirdi',
    name: 'साईं बाबा शिर्डी',
    nameEn: 'Shirdi Sai Baba Temple',
    state: 'महाराष्ट्र',
    deity: 'साईं',
    type: 'Saint Shrine',
    emoji: '✨',
    desc: 'साईं बाबा की समाधि — लाखों भक्तों की आस्था का केंद्र।',
    history:
      'साईं बाबा 1918 में शिर्डी में समाधि लिए। उनकी समाधि के ऊपर मंदिर बनाया गया।',
    timings: '4AM – 11:15PM',
    bestTime: 'सितंबर–मार्च, गुरु पूर्णिमा पर',
    location: 'शिर्डी, अहमदनगर, महाराष्ट्र',
    mapQuery: 'Shirdi+Sai+Baba+Temple+Maharashtra',
    color: '#FFE082',
    gradient:
      'linear-gradient(135deg, rgba(255,224,130,0.15), rgba(245,127,23,0.08))',
  },
  {
    id: 'meenakshi',
    name: 'मीनाक्षी अम्मन मंदिर',
    nameEn: 'Meenakshi Amman Temple',
    state: 'तमिलनाडु',
    deity: 'दुर्गा',
    type: 'Shakti Peeth',
    emoji: '🏛️',
    desc: 'मदुरई की देवी मीनाक्षी को समर्पित विशाल द्रविड़ वास्तुकला का अद्भुत मंदिर।',
    history:
      '14 गोपुरम और 33,000 मूर्तियों वाला यह मंदिर 2,500 वर्ष पुराना है।',
    timings: '5AM – 12:30PM, 4PM – 10PM',
    bestTime: 'अक्टूबर–मार्च, मीनाक्षी तिरुकल्याणम उत्सव',
    location: 'मदुरई, तमिलनाडु',
    mapQuery: 'Meenakshi+Amman+Temple+Madurai',
    color: '#F48FB1',
    gradient:
      'linear-gradient(135deg, rgba(244,143,177,0.15), rgba(136,14,79,0.08))',
  },
  {
    id: 'siddhivinayak',
    name: 'सिद्धिविनायक मंदिर',
    nameEn: 'Siddhivinayak Temple',
    state: 'महाराष्ट्र',
    deity: 'गणेश',
    type: 'Ganesh Temple',
    emoji: '🐘',
    desc: 'मुंबई का प्रसिद्ध गणेश मंदिर — सिद्धि–बुद्धि दाता भगवान गणपति का धाम।',
    history:
      '1801 में लक्ष्मण विठू और देउबाई पाटिल ने इसे बनवाया। मूर्ति की सूड दाईं ओर है।',
    timings: '5:30AM – 10PM',
    bestTime: 'पूरे वर्ष, गणेश चतुर्थी पर',
    location: 'प्रभादेवी, मुंबई, महाराष्ट्र',
    mapQuery: 'Siddhivinayak+Temple+Mumbai',
    color: '#FFCC80',
    gradient:
      'linear-gradient(135deg, rgba(255,204,128,0.15), rgba(230,81,0,0.08))',
  },
  {
    id: 'badrinath',
    name: 'बद्रीनाथ धाम',
    nameEn: 'Badrinath Temple',
    state: 'उत्तराखंड',
    deity: 'विष्णु',
    type: 'Char Dham',
    emoji: '🏔️',
    desc: 'चार धामों में से एक — अलकनंदा नदी के तट पर भगवान विष्णु का पावन धाम।',
    history: 'आदि शंकराचार्य ने 8वीं शताब्दी में इस मंदिर की स्थापना की थी।',
    timings: 'मई–नवंबर: 4:30AM – 9PM',
    bestTime: 'मई–जून, सितंबर–अक्टूबर',
    location: 'चमोली, उत्तराखंड',
    mapQuery: 'Badrinath+Temple+Uttarakhand',
    color: '#B39DDB',
    gradient:
      'linear-gradient(135deg, rgba(179,157,219,0.15), rgba(69,39,160,0.08))',
  },
  {
    id: 'khajuraho',
    name: 'खजुराहो मंदिर',
    nameEn: 'Khajuraho Temples',
    state: 'मध्य प्रदेश',
    deity: 'शिव',
    type: 'Heritage',
    emoji: '🏯',
    desc: 'चंदेल राजाओं द्वारा निर्मित यूनेस्को विश्व धरोहर — अद्भुत मूर्तिकला का खजाना।',
    history: '950-1050 ई. में बने इन 85 मंदिरों में से 25 आज भी सुरक्षित हैं।',
    timings: 'सूर्योदय से सूर्यास्त',
    bestTime: 'अक्टूबर–मार्च, फरवरी में नृत्य महोत्सव',
    location: 'छतरपुर, मध्य प्रदेश',
    mapQuery: 'Khajuraho+Temples+Madhya+Pradesh',
    color: '#BCAAA4',
    gradient:
      'linear-gradient(135deg, rgba(188,170,164,0.15), rgba(78,52,46,0.08))',
  },
  {
    id: 'konark',
    name: 'कोणार्क सूर्य मंदिर',
    nameEn: 'Konark Sun Temple',
    state: 'ओडिशा',
    deity: 'सूर्य',
    type: 'Heritage',
    emoji: '☀️',
    desc: 'यूनेस्को विश्व धरोहर — सूर्यदेव को समर्पित 13वीं शताब्दी का विशाल रथाकार मंदिर।',
    history:
      '1250 ई. में राजा नरसिम्हदेव प्रथम ने बनवाया। 12 जोड़ी पहियों वाला विशाल रथ।',
    timings: '6AM – 8PM',
    bestTime: 'नवंबर–फरवरी, कोणार्क नृत्य महोत्सव',
    location: 'पुरी, ओडिशा',
    mapQuery: 'Konark+Sun+Temple+Odisha',
    color: '#FFAB40',
    gradient:
      'linear-gradient(135deg, rgba(255,171,64,0.15), rgba(230,81,0,0.08))',
  },
  {
    id: 'dagdusheth',
    name: 'दगडूशेठ हलवाई गणपति मंदिर',
    nameEn: 'Dagdusheth Halwai Ganapati Temple',
    state: 'महाराष्ट्र',
    deity: 'गणेश',
    type: 'Ganesh Temple',
    emoji: '🐘',
    desc: 'पुणे का अत्यंत प्रसिद्ध गणपति मंदिर, भव्य उत्सव और सजावट के लिए विख्यात।',
    history:
      '19वीं शताब्दी में स्थापित यह मंदिर गणेश भक्तों की प्रमुख आस्था स्थली है।',
    timings: '6AM – 10:30PM',
    bestTime: 'गणेशोत्सव, अगस्त–सितंबर',
    location: 'पुणे, महाराष्ट्र',
    mapQuery: 'Dagdusheth+Halwai+Ganapati+Temple+Pune',
    color: '#FFCC80',
    gradient:
      'linear-gradient(135deg, rgba(255,204,128,0.15), rgba(230,81,0,0.08))',
  },
  {
    id: 'mayureshwar_morgaon',
    name: 'श्री मयूरेश्वर मंदिर',
    nameEn: 'Shri Mayureshwar Temple',
    state: 'महाराष्ट्र',
    deity: 'गणेश',
    type: 'Ganesh Temple',
    emoji: '🦚',
    desc: 'मोरगांव का अष्टविनायक में प्रमुख मयूरेश्वर गणपति मंदिर।',
    history: 'अष्टविनायक परंपरा में यह मंदिर अत्यंत महत्वपूर्ण माना जाता है।',
    timings: '5AM – 10PM',
    bestTime: 'गणेश चतुर्थी, वर्ष भर',
    location: 'मोरगांव, पुणे, महाराष्ट्र',
    mapQuery: 'Mayureshwar+Temple+Morgaon',
    color: '#FFE082',
    gradient:
      'linear-gradient(135deg, rgba(255,224,130,0.15), rgba(245,127,23,0.08))',
  },
  {
    id: 'maha_vallabha_ny',
    name: 'श्री महा वल्लभ गणपति देवस्थानम',
    nameEn: 'Sri Maha Vallabha Ganapati Devasthanam',
    state: 'USA',
    deity: 'गणेश',
    type: 'Ganesh Temple',
    emoji: '🇺🇸',
    desc: 'न्यूयॉर्क का प्रसिद्ध गणपति मंदिर और उत्तर अमेरिका का प्रमुख गणेश धाम।',
    history: 'अमेरिका में गणेश भक्ति के प्रमुख केंद्रों में से एक।',
    timings: 'Daily: 8AM – 8PM',
    bestTime: 'Ganesh Chaturthi, weekend darshan',
    location: 'Flushing, New York, USA',
    mapQuery: 'Sri+Maha+Vallabha+Ganapati+Devasthanam+New+York',
    color: '#90CAF9',
    gradient:
      'linear-gradient(135deg, rgba(144,202,249,0.15), rgba(21,101,192,0.08))',
  },
  {
    id: 'pashupatinath',
    name: 'पशुपतिनाथ मंदिर',
    nameEn: 'Pashupatinath Temple',
    state: 'नेपाल',
    deity: 'शिव',
    type: 'Heritage',
    emoji: '🔱',
    desc: 'काठमांडू में बागमती नदी तट पर स्थित विश्वप्रसिद्ध शिव मंदिर।',
    history:
      'यह प्राचीन मंदिर यूनेस्को धरोहर क्षेत्र का हिस्सा है और शैव परंपरा में अत्यंत पूजनीय है।',
    timings: '4AM – 9PM',
    bestTime: 'महाशिवरात्रि, अक्टूबर–मार्च',
    location: 'काठमांडू, नेपाल',
    mapQuery: 'Pashupatinath+Temple+Kathmandu',
    color: '#B39DDB',
    gradient:
      'linear-gradient(135deg, rgba(179,157,219,0.15), rgba(94,53,177,0.08))',
  },
  {
    id: 'kamakhya',
    name: 'कामाख्या मंदिर',
    nameEn: 'Kamakhya Temple',
    state: 'असम',
    deity: 'दुर्गा',
    type: 'Shakti Peeth',
    emoji: '🌺',
    desc: 'नीलकंठ पहाड़ी पर स्थित भारत के प्रमुख शक्ति पीठों में से एक।',
    history:
      'कामाख्या देवी का यह मंदिर तांत्रिक साधना और शक्ति उपासना का प्राचीन केंद्र है।',
    timings: '5:30AM – 10PM',
    bestTime: 'अंबुबाची मेला, अक्टूबर–मार्च',
    location: 'गुवाहाटी, असम',
    mapQuery: 'Kamakhya+Temple+Guwahati+Assam',
    color: '#F06292',
    gradient:
      'linear-gradient(135deg, rgba(240,98,146,0.15), rgba(173,20,87,0.08))',
  },
  {
    id: 'durgiana',
    name: 'दुर्गियाना मंदिर',
    nameEn: 'Durgiana Temple',
    state: 'पंजाब',
    deity: 'दुर्गा',
    type: 'Shakti Peeth',
    emoji: '🪷',
    desc: 'अमृतसर का प्रसिद्ध दुर्गा मंदिर, सरोवर और स्वर्णिम वास्तु शैली के लिए प्रसिद्ध।',
    history:
      'यह मंदिर हिंदू श्रद्धालुओं के लिए पंजाब का महत्वपूर्ण शक्तिपीठ स्थल माना जाता है।',
    timings: '5AM – 10PM',
    bestTime: 'नवरात्रि, अक्टूबर–मार्च',
    location: 'अमृतसर, पंजाब',
    mapQuery: 'Durgiana+Temple+Amritsar',
    color: '#FF8A80',
    gradient:
      'linear-gradient(135deg, rgba(255,138,128,0.15), rgba(198,40,40,0.08))',
  },
  {
    id: 'mahalaxmi_kolhapur',
    name: 'महालक्ष्मी मंदिर',
    nameEn: 'Mahalaxmi Temple Kolhapur',
    state: 'महाराष्ट्र',
    deity: 'लक्ष्मी',
    type: 'Vaishnava',
    emoji: '💰',
    desc: 'कोल्हापुर की अंबाबाई महालक्ष्मी का प्राचीन और अत्यंत पूजनीय मंदिर।',
    history:
      'यह मंदिर करवीर क्षेत्र का प्रमुख तीर्थ है और शक्ति-वैष्णव दोनों परंपराओं में मान्य है।',
    timings: '4AM – 10:30PM',
    bestTime: 'नवरात्रि, वर्ष भर',
    location: 'कोल्हापुर, महाराष्ट्र',
    mapQuery: 'Mahalaxmi+Temple+Kolhapur',
    color: '#FFD54F',
    gradient:
      'linear-gradient(135deg, rgba(255,213,79,0.15), rgba(255,160,0,0.08))',
  },
  {
    id: 'ashtalakshmi_chennai',
    name: 'अष्टलक्ष्मी मंदिर',
    nameEn: 'Ashtalakshmi Temple',
    state: 'तमिलनाडु',
    deity: 'लक्ष्मी',
    type: 'Vaishnava',
    emoji: '🪙',
    desc: 'चेन्नई का समुद्र तट स्थित अष्ट रूपों वाली देवी लक्ष्मी को समर्पित मंदिर।',
    history:
      'अष्ट लक्ष्मी की उपासना के लिए यह आधुनिक काल का प्रसिद्ध मंदिर है।',
    timings: '6:30AM – 12PM, 4PM – 9PM',
    bestTime: 'शुक्रवार, त्योहार और वर्ष भर',
    location: 'बेसेंट नगर, चेन्नई, तमिलनाडु',
    mapQuery: 'Ashtalakshmi+Temple+Chennai',
    color: '#FFCC80',
    gradient:
      'linear-gradient(135deg, rgba(255,204,128,0.15), rgba(239,108,0,0.08))',
  },
  {
    id: 'basara_saraswati',
    name: 'बसरा सरस्वती मंदिर',
    nameEn: 'Basara Saraswati Temple',
    state: 'तेलंगाना',
    deity: 'सरस्वती',
    type: 'Shakti Peeth',
    emoji: '📚',
    desc: 'ज्ञान की देवी सरस्वती का प्रसिद्ध मंदिर, बच्चों के अक्षरारंभ संस्कार के लिए विख्यात।',
    history:
      'गोदावरी तट पर स्थित यह मंदिर विद्यारंभ परंपरा के कारण अत्यधिक लोकप्रिय है।',
    timings: '4AM – 8:30PM',
    bestTime: 'वसंत पंचमी, नवंबर–फरवरी',
    location: 'बसरा, निर्मल, तेलंगाना',
    mapQuery: 'Gnana+Saraswati+Temple+Basar+Telangana',
    color: '#80DEEA',
    gradient:
      'linear-gradient(135deg, rgba(128,222,234,0.15), rgba(0,151,167,0.08))',
  },
  {
    id: 'srirangam',
    name: 'श्री रंगनाथस्वामी मंदिर',
    nameEn: 'Sri Ranganathaswamy Temple',
    state: 'तमिलनाडु',
    deity: 'विष्णु',
    type: 'Vaishnava',
    emoji: '🐚',
    desc: 'श्रीरंगम का विश्वप्रसिद्ध वैष्णव मंदिर और श्रीवैष्णव परंपरा का प्रमुख केंद्र।',
    history:
      'यह मंदिर भारत के सबसे बड़े क्रियाशील मंदिर परिसरों में से एक माना जाता है।',
    timings: '6AM – 9PM',
    bestTime: 'दिसंबर–फरवरी, वैकुंठ एकादशी',
    location: 'श्रीरंगम, तिरुचिरापल्ली, तमिलनाडु',
    mapQuery: 'Sri+Ranganathaswamy+Temple+Srirangam',
    color: '#A5D6A7',
    gradient:
      'linear-gradient(135deg, rgba(165,214,167,0.15), rgba(46,125,50,0.08))',
  },
  {
    id: 'ram_janmabhoomi',
    name: 'श्री राम जन्मभूमि मंदिर',
    nameEn: 'Shri Ram Janmabhoomi Mandir',
    state: 'उत्तर प्रदेश',
    deity: 'राम',
    type: 'Char Dham',
    emoji: '🏹',
    desc: 'अयोध्या में स्थित भगवान श्रीराम जन्मभूमि पर निर्मित भव्य मंदिर।',
    history:
      'यह स्थल रामायण परंपरा में प्रभु श्रीराम का जन्मस्थान माना जाता है।',
    timings: '6AM – 10PM',
    bestTime: 'राम नवमी, अक्टूबर–मार्च',
    location: 'अयोध्या, उत्तर प्रदेश',
    mapQuery: 'Shri+Ram+Janmabhoomi+Mandir+Ayodhya',
    color: '#FFAB91',
    gradient:
      'linear-gradient(135deg, rgba(255,171,145,0.15), rgba(230,74,25,0.08))',
  },
  {
    id: 'kalaram_nashik',
    name: 'काला राम मंदिर',
    nameEn: 'Kala Ram Temple',
    state: 'महाराष्ट्र',
    deity: 'राम',
    type: 'Heritage',
    emoji: '🏛️',
    desc: 'नासिक का प्रसिद्ध राम मंदिर, काले पाषाण की श्रीराम प्रतिमा के लिए विख्यात।',
    history:
      '18वीं शताब्दी में निर्मित यह मंदिर रामभक्ति परंपरा का प्रमुख स्थल है।',
    timings: '5AM – 10PM',
    bestTime: 'राम नवमी, वर्ष भर',
    location: 'पंचवटी, नासिक, महाराष्ट्र',
    mapQuery: 'Kala+Ram+Temple+Nashik',
    color: '#BCAAA4',
    gradient:
      'linear-gradient(135deg, rgba(188,170,164,0.15), rgba(78,52,46,0.08))',
  },
  {
    id: 'hanumangarhi_ayodhya',
    name: 'हनुमानगढ़ी मंदिर',
    nameEn: 'Hanumangarhi Temple',
    state: 'उत्तर प्रदेश',
    deity: 'हनुमान',
    type: 'Heritage',
    emoji: '🐒',
    desc: 'अयोध्या का प्रमुख हनुमान मंदिर, रामनगरी का महत्वपूर्ण तीर्थ।',
    history:
      'परंपरा के अनुसार अयोध्या की रक्षा हनुमानगढ़ी से होती है; यह सदियों पुराना श्रद्धा केंद्र है।',
    timings: '5AM – 10PM',
    bestTime: 'हनुमान जयंती, अक्टूबर–मार्च',
    location: 'अयोध्या, उत्तर प्रदेश',
    mapQuery: 'Hanumangarhi+Temple+Ayodhya',
    color: '#FFCC80',
    gradient:
      'linear-gradient(135deg, rgba(255,204,128,0.15), rgba(230,81,0,0.08))',
  },
  {
    id: 'salasar_balaji',
    name: 'सालासर बालाजी मंदिर',
    nameEn: 'Salasar Balaji Temple',
    state: 'राजस्थान',
    deity: 'हनुमान',
    type: 'Heritage',
    emoji: '🛕',
    desc: 'राजस्थान का प्रसिद्ध बालाजी (हनुमान) मंदिर, दूर-दूर से भक्त दर्शन हेतु आते हैं।',
    history: 'सालासर धाम हनुमान भक्ति की अनूठी लोक परंपरा के लिए जाना जाता है।',
    timings: '4AM – 10PM',
    bestTime: 'हनुमान जयंती, आश्विन/चैत्र मेले',
    location: 'सालासर, चूरू, राजस्थान',
    mapQuery: 'Salasar+Balaji+Temple+Rajasthan',
    color: '#FFE082',
    gradient:
      'linear-gradient(135deg, rgba(255,224,130,0.15), rgba(245,127,23,0.08))',
  },
  {
    id: 'sankatmochan_varanasi',
    name: 'श्री संकटमोचन हनुमान मंदिर',
    nameEn: 'Sankat Mochan Hanuman Temple',
    state: 'उत्तर प्रदेश',
    deity: 'हनुमान',
    type: 'Heritage',
    emoji: '🚩',
    desc: 'वाराणसी का विख्यात संकटमोचन मंदिर, हनुमान भक्तों का प्रमुख तीर्थ।',
    history:
      'मान्यता है कि गोस्वामी तुलसीदास जी से जुड़ी परंपरा में यह मंदिर स्थापित हुआ।',
    timings: '5AM – 10PM',
    bestTime: 'मंगलवार-शनिवार, हनुमान जयंती',
    location: 'वाराणसी, उत्तर प्रदेश',
    mapQuery: 'Sankat+Mochan+Hanuman+Temple+Varanasi',
    color: '#FFAB91',
    gradient:
      'linear-gradient(135deg, rgba(255,171,145,0.15), rgba(216,67,21,0.08))',
  },
  {
    id: 'modhera_sun',
    name: 'मोडेरा सूर्य मंदिर',
    nameEn: 'Modhera Sun Temple',
    state: 'गुजरात',
    deity: 'सूर्य',
    type: 'Heritage',
    emoji: '☀️',
    desc: 'गुजरात का ऐतिहासिक सूर्य मंदिर, सोलंकी युग की अद्भुत वास्तुकला का उदाहरण।',
    history:
      '11वीं शताब्दी में राजा भीमदेव प्रथम द्वारा निर्मित यह मंदिर स्थापत्य कला के लिए प्रसिद्ध है।',
    timings: '6AM – 6PM',
    bestTime: 'अक्टूबर–फरवरी, मोढेरा नृत्य महोत्सव',
    location: 'मोडेरा, गुजरात',
    mapQuery: 'Modhera+Sun+Temple+Gujarat',
    color: '#FFB74D',
    gradient:
      'linear-gradient(135deg, rgba(255,183,77,0.15), rgba(230,81,0,0.08))',
  },
  {
    id: 'kalighat_kali',
    name: 'कालीघाट काली मंदिर',
    nameEn: 'Kalighat Kali Temple',
    state: 'पश्चिम बंगाल',
    deity: 'काली',
    type: 'Shakti Peeth',
    emoji: '⚫',
    desc: 'कोलकाता का प्रसिद्ध काली मंदिर और प्रमुख शक्तिपीठों में से एक।',
    history:
      'काली उपासना की बंगाल परंपरा में कालीघाट का ऐतिहासिक महत्व अत्यंत गहरा है।',
    timings: '5AM – 2PM, 5PM – 10:30PM',
    bestTime: 'काली पूजा, नवरात्रि',
    location: 'कोलकाता, पश्चिम बंगाल',
    mapQuery: 'Kalighat+Kali+Temple+Kolkata',
    color: '#BA68C8',
    gradient:
      'linear-gradient(135deg, rgba(186,104,200,0.15), rgba(106,27,154,0.08))',
  },
  {
    id: 'dakshineswar_kali',
    name: 'दक्षिणेश्वर काली मंदिर',
    nameEn: 'Dakshineswar Kali Temple',
    state: 'पश्चिम बंगाल',
    deity: 'काली',
    type: 'Shakti Peeth',
    emoji: '🌙',
    desc: 'हुगली तट पर स्थित विख्यात काली मंदिर, रामकृष्ण परमहंस से जुड़ा पावन स्थल।',
    history:
      'रानी रासमणि द्वारा स्थापित यह मंदिर बंगाल की भक्ति परंपरा में विशिष्ट स्थान रखता है।',
    timings: '6AM – 12:30PM, 3PM – 8:30PM',
    bestTime: 'काली पूजा, सर्दियों में दर्शन',
    location: 'दक्षिणेश्वर, कोलकाता, पश्चिम बंगाल',
    mapQuery: 'Dakshineswar+Kali+Temple+Kolkata',
    color: '#9575CD',
    gradient:
      'linear-gradient(135deg, rgba(149,117,205,0.15), rgba(81,45,168,0.08))',
  },
  {
    id: 'khatu_shyam',
    name: 'खाटू श्याम मंदिर',
    nameEn: 'Khatu Shyam Temple',
    state: 'राजस्थान',
    deity: 'खाटू श्याम',
    type: 'Vaishnava',
    emoji: '🎠',
    desc: 'राजस्थान का प्रसिद्ध खाटू श्याम धाम, लाखों श्रद्धालुओं की आस्था का केंद्र।',
    history:
      'बर्बरीक रूप में पूजित खाटू श्याम जी का यह धाम फाल्गुन मेले के लिए विशेष प्रसिद्ध है।',
    timings: '4:30AM – 10PM',
    bestTime: 'फाल्गुन मेला, वर्ष भर',
    location: 'खाटू, सीकर, राजस्थान',
    mapQuery: 'Khatu+Shyam+Ji+Temple+Rajasthan',
    color: '#CE93D8',
    gradient:
      'linear-gradient(135deg, rgba(206,147,216,0.15), rgba(123,31,162,0.08))',
  },
  {
    id: 'shani_shingnapur',
    name: 'शनि शिंगणापुर मंदिर',
    nameEn: 'Shani Shingnapur Temple',
    state: 'महाराष्ट्र',
    deity: 'शनि',
    type: 'Heritage',
    emoji: '🪐',
    desc: 'महाराष्ट्र का प्रसिद्ध शनि धाम, खुले शनि शिला स्वरूप के लिए विख्यात।',
    history:
      'यह स्थल शनि उपासना की अनूठी परंपरा और ग्राम-आस्था के लिए प्रसिद्ध है।',
    timings: '24 घंटे खुला',
    bestTime: 'शनिवार, शनि अमावस्या',
    location: 'शिंगणापुर, अहमदनगर, महाराष्ट्र',
    mapQuery: 'Shani+Shingnapur+Temple+Maharashtra',
    color: '#90A4AE',
    gradient:
      'linear-gradient(135deg, rgba(144,164,174,0.15), rgba(55,71,79,0.08))',
  },
  {
    id: 'shani_kokilavan',
    name: 'शनि मंदिर (कोकिलावन)',
    nameEn: 'Shani Temple Kokilavan',
    state: 'उत्तर प्रदेश',
    deity: 'शनि',
    type: 'Heritage',
    emoji: '⚫',
    desc: 'कोकिलावन धाम का प्रसिद्ध शनि मंदिर, ब्रज क्षेत्र का महत्वपूर्ण तीर्थ।',
    history:
      'यह धाम शनि और राधा-कृष्ण भक्ति परंपरा से जुड़े दर्शन हेतु श्रद्धालुओं में लोकप्रिय है।',
    timings: '5AM – 9PM',
    bestTime: 'शनिवार, अमावस्या',
    location: 'कोकिलावन, मथुरा, उत्तर प्रदेश',
    mapQuery: 'Shani+Temple+Kokilavan+Mathura',
    color: '#78909C',
    gradient:
      'linear-gradient(135deg, rgba(120,144,156,0.15), rgba(38,50,56,0.08))',
  },
  {
    id: 'maihar-sharda',
    name: 'मैहर शारदा मंदिर',
    nameEn: 'Maihar Sharda Temple',
    state: 'मध्य प्रदेश',
    deity: 'माता शारदा (दुर्गा)',
    type: 'Shakti Peeth',
    emoji: '🛕',
    desc: 'त्रिकूट पर्वत पर स्थित माँ शारदा का प्रसिद्ध शक्तिपीठ, जहाँ 1063 सीढ़ियाँ चढ़कर दर्शन किए जाते हैं।',
    history:
      'माना जाता है कि यहाँ सती माता का हार (माला) गिरा था, इसलिए इस स्थान का नाम "मैहर" पड़ा। यह मंदिर प्राचीन काल से शक्ति उपासना का महत्वपूर्ण केंद्र रहा है और आल्हा-उदल की कथा से भी जुड़ा हुआ है।',
    timings: '5:00AM – 10:00PM',
    bestTime: 'नवरात्रि (चैत्र और शारदीय), अक्टूबर–मार्च',
    location: 'मैहर, सतना जिला, मध्य प्रदेश',
    mapQuery: 'Maihar+Sharda+Temple+Madhya+Pradesh',
    color: '#FF7043',
    gradient:
      'linear-gradient(135deg, rgba(255,112,67,0.15), rgba(191,54,12,0.08))',
  },
  {
    id: 'sringeri-sharadamba',
    name: 'शारदाम्बा मंदिर',
    nameEn: 'Sringeri Sharadamba Temple',
    state: 'कर्नाटक',
    deity: 'माता शारदाम्बा (सरस्वती)',
    type: 'Peetham / Math',
    emoji: '📿',
    desc: 'कर्नाटक के श्रृंगेरी में स्थित माँ शारदाम्बा का प्रसिद्ध मंदिर, जो अद्वैत वेदांत परंपरा का प्रमुख केंद्र है।',
    history:
      'यह मंदिर कर्नाटक के श्रृंगेरी में स्थित है। इसे आदि शंकराचार्य द्वारा स्थापित चार प्रमुख मठों में से एक माना जाता है। यहाँ माँ शारदाम्बा की पूजा ज्ञान और विद्या की देवी के रूप में की जाती है।',
    timings: '6:00AM – 2:00PM, 4:00PM – 9:00PM',
    bestTime: 'नवरात्रि, अक्टूबर–फरवरी',
    location: 'श्रृंगेरी, चिकमंगलूर जिला, कर्नाटक',
    mapQuery: 'Sringeri+Sharadamba+Temple+Karnataka',
    color: '#7E57C2',
    gradient:
      'linear-gradient(135deg, rgba(126,87,194,0.15), rgba(49,27,146,0.08))',
  },
  {
    id: 'sharda-peeth',
    name: 'शारदा पीठ',
    nameEn: 'Sharda Peeth',
    state: 'कश्मीर क्षेत्र',
    deity: 'माता शारदा (सरस्वती)',
    type: 'Ancient Peeth / Temple',
    emoji: '📖',
    desc: 'कश्मीर क्षेत्र में स्थित प्राचीन शारदा पीठ, जो ऐतिहासिक रूप से ज्ञान और विद्या का महान केंद्र माना जाता था।',
    history:
      'यह प्राचीन मंदिर कश्मीर क्षेत्र में स्थित था और ऐतिहासिक रूप से ज्ञान का बड़ा केंद्र माना जाता था। प्राचीन काल में विद्वान यहाँ आकर शास्त्रार्थ करते थे और इसे विद्या की देवी माँ शारदा का प्रमुख पीठ माना जाता था।',
    timings: 'ऐतिहासिक स्थल (नियमित दर्शन उपलब्ध नहीं)',
    bestTime: 'मई–अक्टूबर (अनुकूल मौसम)',
    location: 'नीलम घाटी, कश्मीर क्षेत्र',
    mapQuery: 'Sharda+Peeth+Neelum+Valley+Kashmir',
    color: '#5C6BC0',
    gradient:
      'linear-gradient(135deg, rgba(92,107,192,0.15), rgba(26,35,126,0.08))',
  },
  {
    id: 'rani-sati',
    name: 'रानी सती मंदिर',
    nameEn: 'Rani Sati Temple',
    state: 'राजस्थान',
    deity: 'माता रानी सती',
    type: 'Hindu Temple',
    emoji: '🛕',
    desc: 'झुंझुनू शहर में स्थित प्रसिद्ध हिंदू तीर्थ स्थल, जहां माता रानी सती की पूजा होती है।',
    history:
      'रानी सती मंदिर झुंझुनू, राजस्थान में स्थित है और यह माताजी रानी सती के सम्मान में स्थापित एक प्रमुख धार्मिक केंद्र है। श्रद्धालु यहां माता रानी सती की भक्ति और चमत्कारों के लिए आते हैं।',
    timings: '5:00AM – 9:00PM',
    bestTime: 'नवरात्रि, दीपावली',
    location: 'झुंझुनू, राजस्थान',
    mapQuery: 'Rani+Sati+Temple+Jhunjhunu+Rajasthan',
    color: '#FFB300',
    gradient:
      'linear-gradient(135deg, rgba(255,179,0,0.15), rgba(255,143,0,0.08))',
  },
  {
    id: 'shakambhari-devi',
    name: 'श्री शाकम्भरी देवी मंदिर',
    nameEn: 'Shakambhari Devi Temple',
    state: 'उत्तर प्रदेश',
    deity: 'माता शाकम्भरी देवी (पार्वती का अवतार)',
    type: 'Shakti Peeth',
    emoji: '🌿',
    desc: 'सहारनपुर के पास शिवालिक पहाड़ियों में स्थित अत्यंत प्राचीन और सिद्ध शक्तिपीठ, जो शाक-सब्जी और पोषण की देवी को समर्पित है।',
    history:
      'यह मंदिर माता पार्वती के शाकम्भरी अवतार को समर्पित है और 51 शक्तिपीठों में से एक माना जाता है। प्राचीन काल से यह स्थान भक्तों के लिए आस्था और पोषण का प्रतीक रहा है।',
    timings: '5:00AM – 8:00PM',
    bestTime: 'नवरात्रि (मार्च–अप्रैल और अक्टूबर–नवंबर)',
    location: 'सहारनपुर, उत्तर प्रदेश',
    mapQuery: 'Shakambhari+Devi+Temple+Saharanpur+UP',
    color: '#66BB6A',
    gradient:
      'linear-gradient(135deg, rgba(102,187,106,0.15), rgba(56,142,60,0.08))',
  },
  {
    id: 'sambar-devi',
    name: 'सांभर देवी मंदिर',
    nameEn: 'Sambar Devi Temple',
    state: 'राजस्थान',
    deity: 'माता शाकम्भरी देवी',
    type: 'Shakti Peeth',
    emoji: '🛕',
    desc: 'राजस्थान के सांभर क्षेत्र में स्थित माता शाकम्भरी का प्राचीन मंदिर।',
    history:
      'सांभर देवी मंदिर शाकम्भरी देवी को समर्पित एक प्राचीन शक्तिपीठ है। यह स्थान स्थानीय लोगों के लिए आस्था और भक्तिभाव का केंद्र रहा है।',
    timings: '6:00AM – 8:00PM',
    bestTime: 'नवरात्रि, अक्टूबर–मार्च',
    location: 'सांभर, राजस्थान',
    mapQuery: 'Sambar+Devi+Temple+Rajasthan',
    color: '#FFA726',
    gradient:
      'linear-gradient(135deg, rgba(255,167,38,0.15), rgba(255,112,67,0.08))',
  },
  {
    id: 'omkareshwar',
    name: 'ओंकारेश्वर ज्योतिर्लिंग',
    nameEn: 'Omkareshwar Jyotirlinga',
    state: 'मध्य प्रदेश',
    deity: 'भगवान शिव',
    type: 'Jyotirlinga',
    emoji: '🕉️',
    desc: 'नर्मदा नदी के द्वीप पर स्थित पवित्र ज्योतिर्लिंग, जो भगवान शिव को समर्पित है।',
    history:
      'ओंकारेश्वर ज्योतिर्लिंग भारत के 12 ज्योतिर्लिंगों में से एक है। यह स्थान प्राचीन काल से शिव भक्तों के लिए तीर्थ स्थल रहा है और इसे विशेष रूप से नर्मदा नदी के किनारे स्थित ओंकार द्वीप पर पूजा जाता है।',
    timings: '6:00AM – 9:00PM',
    bestTime: 'महाशिवरात्रि, श्रावण मास',
    location: 'ओंकारेश्वर, मध्य प्रदेश',
    mapQuery: 'Omkareshwar+Jyotirlinga+Madhya+Pradesh',
    color: '#4DB6AC',
    gradient:
      'linear-gradient(135deg, rgba(77,182,172,0.15), rgba(0,105,92,0.08))',
  },
  {
    id: 'maheshwar',
    name: 'महेश्वर',
    nameEn: 'Maheshwar Temple',
    state: 'मध्य प्रदेश',
    deity: 'भगवान शिव',
    type: 'Temple / Town',
    emoji: '🛕',
    desc: 'नर्मदा नदी के किनारे स्थित प्राचीन शहर और मंदिर, भगवान शिव को समर्पित।',
    history:
      'महेश्वर मध्य प्रदेश का प्राचीन धार्मिक स्थल है। यहाँ की महेश्वर की प्राचीन शिव मंदिरें और नर्मदा नदी के किनारे स्थित घाट इसे ऐतिहासिक और आध्यात्मिक दृष्टि से महत्वपूर्ण बनाते हैं। यह स्थान प्राचीन काल से शिव भक्ति का केंद्र रहा है।',
    timings: 'सभी समय खुला (घाट और मंदिर दर्शन)',
    bestTime: 'अक्टूबर–मार्च',
    location: 'महेश्वर, खंडवा जिला, मध्य प्रदेश',
    mapQuery: 'Maheshwar+Temple+Madhya+Pradesh',
    color: '#7986CB',
    gradient:
      'linear-gradient(135deg, rgba(121,134,203,0.15), rgba(48,63,159,0.08))',
  },
  {
    id: 'hoshangabad',
    name: 'होशंगाबाद (नर्मदापुरम)',
    nameEn: 'Hoshangabad (Narmadapuram)',
    state: 'मध्य प्रदेश',
    deity: 'नर्मदा देवी (स्थानीय पूजा)',
    type: 'City / Pilgrimage',
    emoji: '🏞️',
    desc: 'नर्मदा नदी के किनारे स्थित शहर, जो धार्मिक और सांस्कृतिक दृष्टि से महत्वपूर्ण है।',
    history:
      'होशंगाबाद, जिसे नर्मदापुरम भी कहा जाता है, नर्मदा नदी के तट पर स्थित एक प्राचीन शहर है। यहाँ का क्षेत्र धार्मिक अनुष्ठानों और घाटों के लिए प्रसिद्ध है, विशेषकर नर्मदा नदी की पूजा और तीर्थ यात्राओं के लिए।',
    timings: 'सार्वजनिक स्थल, सभी समय खुला',
    bestTime: 'अक्टूबर–मार्च',
    location: 'होशंगाबाद, मध्य प्रदेश',
    mapQuery: 'Hoshangabad+Narmadapuram+Madhya+Pradesh',
    color: '#4FC3F7',
    gradient:
      'linear-gradient(135deg, rgba(79,195,247,0.15), rgba(2,136,209,0.08))',
  },
  {
    id: 'mandla',
    name: 'मंडला',
    nameEn: 'Mandla',
    state: 'मध्य प्रदेश',
    deity: 'स्थानीय देवी-देवता',
    type: 'City / Pilgrimage',
    emoji: '🏛️',
    desc: 'मध्य प्रदेश का ऐतिहासिक शहर, जो धार्मिक और सांस्कृतिक दृष्टि से महत्वपूर्ण है।',
    history:
      'मंडला मध्य प्रदेश का प्राचीन और ऐतिहासिक शहर है। यह क्षेत्र मंदिरों, घाटों और सांस्कृतिक उत्सवों के लिए जाना जाता है। स्थानीय देवी-देवताओं की पूजा यहाँ की धार्मिक परंपरा का मुख्य हिस्सा है।',
    timings: 'सार्वजनिक स्थल, सभी समय खुला',
    bestTime: 'अक्टूबर–मार्च',
    location: 'मंडला, मध्य प्रदेश',
    mapQuery: 'Mandla+Madhya+Pradesh',
    color: '#BA68C8',
    gradient:
      'linear-gradient(135deg, rgba(186,104,200,0.15), rgba(123,31,162,0.08))',
  },
  {
    id: 'baglamukhi-datia',
    name: 'बगलामुखी मंदिर',
    nameEn: 'Baglamukhi Temple',
    state: 'मध्य प्रदेश',
    deity: 'माता बगलामुखी',
    type: 'Shakti Peeth',
    emoji: '🔱',
    desc: 'दतिया में स्थित प्रसिद्ध शक्तिपीठ, जो माता बगलामुखी को समर्पित है।',
    history:
      'बगलामुखी मंदिर दतिया, मध्य प्रदेश में स्थित है और यह शक्ति पूजा का महत्वपूर्ण केंद्र माना जाता है। यहाँ भक्त बुरी शक्तियों को रोकने और विजय प्राप्त करने के लिए देवी बगलामुखी की पूजा करते हैं।',
    timings: '5:00AM – 8:00PM',
    bestTime: 'नवरात्रि, चैत्र और शारदीय',
    location: 'दतिया, मध्य प्रदेश',
    mapQuery: 'Baglamukhi+Temple+Datia+Madhya+Pradesh',
    color: '#FF8A65',
    gradient:
      'linear-gradient(135deg, rgba(255,138,101,0.15), rgba(191,54,12,0.08))',
  },
  {
    id: 'baglamukhi-kangra',
    name: 'बगलामुखी मंदिर',
    nameEn: 'Baglamukhi Temple',
    state: 'हिमाचल प्रदेश',
    deity: 'माता बगलामुखी',
    type: 'Shakti Peeth',
    emoji: '🔱',
    desc: 'कांगड़ा में स्थित प्राचीन शक्तिपीठ, जो माता बगलामुखी को समर्पित है।',
    history:
      'बगलामुखी मंदिर कांगड़ा, हिमाचल प्रदेश में स्थित है। यह मंदिर शक्ति उपासना का प्राचीन केंद्र है और यहाँ भक्त बुरी शक्तियों और नकारात्मक ऊर्जा से मुक्ति पाने के लिए माता बगलामुखी की पूजा करते हैं।',
    timings: '5:00AM – 7:00PM',
    bestTime: 'नवरात्रि, मार्च–अप्रैल और अक्टूबर–नवंबर',
    location: 'कांगड़ा, हिमाचल प्रदेश',
    mapQuery: 'Baglamukhi+Temple+Kangra+Himachal+Pradesh',
    color: '#FF7043',
    gradient:
      'linear-gradient(135deg, rgba(255,112,67,0.15), rgba(191,54,12,0.08))',
  },
  {
    id: 'baglamukhi-nalkheda',
    name: 'बगलामुखी मंदिर',
    nameEn: 'Baglamukhi Temple',
    state: 'मध्य प्रदेश',
    deity: 'माता बगलामुखी',
    type: 'Shakti Peeth',
    emoji: '🔱',
    desc: 'नलखेड़ा में स्थित शक्तिपीठ, जो माता बगलामुखी को समर्पित है।',
    history:
      'बगलामुखी मंदिर नलखेड़ा, मध्य प्रदेश में स्थित है और यह शक्ति उपासना का प्राचीन केंद्र माना जाता है। भक्त यहाँ बुरी शक्तियों से मुक्ति और विजय प्राप्ति के लिए देवी बगलामुखी की पूजा करते हैं।',
    timings: '5:00AM – 8:00PM',
    bestTime: 'नवरात्रि, चैत्र और शारदीय',
    location: 'नलखेड़ा, मध्य प्रदेश',
    mapQuery: 'Baglamukhi+Temple+Nalkheda+Madhya+Pradesh',
    color: '#FF8A65',
    gradient:
      'linear-gradient(135deg, rgba(255,138,101,0.15), rgba(191,54,12,0.08))',
  },
  {
    id: 'annapurna-temple',
    name: 'अन्नपूर्णा मंदिर',
    nameEn: 'Annapurna Temple',
    state: 'उत्तर प्रदेश',
    deity: 'माता अन्नपूर्णा (पार्वती)',
    type: 'Hindu Temple',
    emoji: '🍛',
    desc: 'वाराणसी (काशी) में स्थित प्रसिद्ध हिंदू मंदिर, जो भोजन की देवी माता अन्नपूर्णा को समर्पित है।',
    history:
      'अन्नपूर्णा मंदिर वाराणसी में स्थित है और यह देवी अन्नपूर्णा, जो भोजन और पोषण की देवी हैं, को समर्पित है। यह मंदिर भक्तों के बीच अत्यंत प्रसिद्ध है और यहाँ भिक्षु और श्रद्धालु अन्नदान के लिए आते हैं।',
    timings: '5:30AM – 9:00PM',
    bestTime: 'नवरात्रि, कार्तिक मास',
    location: 'वाराणसी, उत्तर प्रदेश',
    mapQuery: 'Annapurna+Temple+Varanasi+UP',
    color: '#FFB74D',
    gradient:
      'linear-gradient(135deg, rgba(255,183,77,0.15), rgba(255,143,0,0.08))',
  },
  {
    id: 'santoshi-maa',
    name: 'संतोषी माता मंदिर',
    nameEn: 'Santoshi Maa Temple',
    state: 'राजस्थान',
    deity: 'माता संतोषी',
    type: 'Hindu Temple',
    emoji: '🌸',
    desc: 'जोधपुर, राजस्थान में स्थित प्रसिद्ध हिंदू मंदिर, जो माता संतोषी को समर्पित है।',
    history:
      'संतोषी माता मंदिर जोधपुर में स्थित है और यह माता संतोषी की पूजा का प्रमुख केंद्र है। भक्त यहाँ प्रसन्नता, सुख और संतोष की प्राप्ति के लिए आते हैं।',
    timings: '6:00AM – 8:00PM',
    bestTime: 'शुक्रवार, नवरात्रि',
    location: 'जोधपुर, राजस्थान',
    mapQuery: 'Santoshi+Maa+Temple+Jodhpur+Rajasthan',
    color: '#FFCDD2',
    gradient:
      'linear-gradient(135deg, rgba(255,205,210,0.15), rgba(239,83,80,0.08))',
  },
  {
    id: 'annapurna-temple-indore',
    name: 'अन्नपूर्णा मंदिर',
    nameEn: 'Annapurna Temple',
    state: 'मध्य प्रदेश',
    deity: 'माता अन्नपूर्णा (पार्वती)',
    type: 'Hindu Temple',
    emoji: '🍛',
    desc: 'इंदौर में स्थित प्रसिद्ध मंदिर, जो भोजन की देवी माता अन्नपूर्णा को समर्पित है।',
    history:
      'अन्नपूर्णा मंदिर इंदौर में स्थित है और यह देवी अन्नपूर्णा को समर्पित है। यहाँ भक्त पोषण और अन्नदान के लिए आते हैं। यह मंदिर शहर के प्रमुख धार्मिक स्थलों में से एक है।',
    timings: '5:30AM – 9:00PM',
    bestTime: 'नवरात्रि, कार्तिक मास',
    location: 'इंदौर, मध्य प्रदेश',
    mapQuery: 'Annapurna+Temple+Indore+Madhya+Pradesh',
    color: '#FFB74D',
    gradient:
      'linear-gradient(135deg, rgba(255,183,77,0.15), rgba(255,143,0,0.08))',
  },
  {
    id: 'santoshi-maa-jaipur',
    name: 'संतोषी माता मंदिर',
    nameEn: 'Santoshi Maa Temple',
    state: 'राजस्थान',
    deity: 'माता संतोषी',
    type: 'Hindu Temple',
    emoji: '🌸',
    desc: 'जयपुर में स्थित प्रमुख संतोषी माता का मंदिर, जो भक्तों के लिए प्रसन्नता और संतोष की प्राप्ति का केंद्र है।',
    history:
      'संतोषी माता मंदिर जयपुर में स्थित है और यह माता संतोषी की पूजा का प्रमुख केंद्र माना जाता है। यहाँ विशेष रूप से शुक्रवार और नवरात्रि के अवसर पर बड़ी संख्या में श्रद्धालु आते हैं।',
    timings: '6:00AM – 8:00PM',
    bestTime: 'शुक्रवार, नवरात्रि',
    location: 'जयपुर, राजस्थान',
    mapQuery: 'Santoshi+Maa+Temple+Jaipur+Rajasthan',
    color: '#FFCDD2',
    gradient:
      'linear-gradient(135deg, rgba(255,205,210,0.15), rgba(239,83,80,0.08))',
  },
  {
    id: 'radha-rani-barsana',
    name: 'श्री राधा रानी मंदिर',
    nameEn: 'Shri Radha Rani Temple',
    state: 'उत्तर प्रदेश',
    deity: 'श्री राधा रानी',
    type: 'Hindu Temple',
    emoji: '💖',
    desc: 'बरसाना में स्थित प्रसिद्ध मंदिर, जो श्री राधा रानी को समर्पित है और वैष्णव धर्म के लिए महत्वपूर्ण स्थल है।',
    history:
      'श्री राधा रानी मंदिर, बरसाना में स्थित है। यह मंदिर भगवान कृष्ण की प्रिय राधा रानी को समर्पित है। यहाँ बरसाना की लीलाओं और राधा-कृष्ण भक्ति की परंपरा का अनुभव किया जा सकता है।',
    timings: '5:00AM – 8:00PM',
    bestTime: 'होली, राधाष्टमी, अक्टूबर–मार्च',
    location: 'बरसाना, मथुरा जिला, उत्तर प्रदेश',
    mapQuery: 'Shri+Radha+Rani+Temple+Barsana+UP',
    color: '#F06292',
    gradient:
      'linear-gradient(135deg, rgba(240,98,146,0.15), rgba(173,20,87,0.08))',
  },
  {
    id: 'radha-damodar-vrindavan',
    name: 'राधा दामोदर मंदिर',
    nameEn: 'Radha Damodar Temple',
    state: 'उत्तर प्रदेश',
    deity: 'श्री राधा और दामोदर कृष्ण',
    type: 'Hindu Temple',
    emoji: '💖🕉️',
    desc: 'वृंदावन में स्थित प्राचीन मंदिर, जो राधा और दामोदर कृष्ण को समर्पित है।',
    history:
      'राधा दामोदर मंदिर वृंदावन में स्थित है। यह मंदिर 16वीं सदी में बना था और इसे श्रीमद्भागवतम के अनुसार कृष्ण और राधा की भक्ति का केंद्र माना जाता है। यहाँ भक्त विशेष रूप से राधा-दामोदर की पूजा करते हैं।',
    timings: '5:00AM – 8:00PM',
    bestTime: 'होली, जन्माष्टमी, राधाष्टमी',
    location: 'वृंदावन, मथुरा जिला, उत्तर प्रदेश',
    mapQuery: 'Radha+Damodar+Temple+Vrindavan+UP',
    color: '#BA68C8',
    gradient:
      'linear-gradient(135deg, rgba(186,104,200,0.15), rgba(123,31,162,0.08))',
  },
  {
    id: 'prem-temple-vrindavan',
    name: 'प्रेम मंदिर',
    nameEn: 'Prem Mandir',
    state: 'उत्तर प्रदेश',
    deity: 'श्री राधा-कृष्ण',
    type: 'Hindu Temple',
    emoji: '❤️🕉️',
    desc: 'वृंदावन में स्थित भव्य मंदिर, जो राधा-कृष्ण के प्रेम और भक्ति को समर्पित है।',
    history:
      'प्रेम मंदिर वृंदावन में स्थित है। इसे वर्ष 2001 में निर्मित किया गया था और यह पूरे विश्व में राधा-कृष्ण भक्ति का प्रमुख केंद्र माना जाता है। मंदिर का निर्माण संगमरमर और चित्रकारी से किया गया है।',
    timings: '5:00AM – 9:00PM',
    bestTime: 'होली, जन्माष्टमी, राधाष्टमी',
    location: 'वृंदावन, मथुरा जिला, उत्तर प्रदेश',
    mapQuery: 'Prem+Mandir+Vrindavan+UP',
    color: '#F48FB1',
    gradient:
      'linear-gradient(135deg, rgba(244,143,177,0.15), rgba(194,24,91,0.08))',
  },
  {
    id: 'sheetla-mata-gurugram',
    name: 'शीतला माता मंदिर',
    nameEn: 'Sheetla Mata Temple',
    state: 'हरियाणा',
    deity: 'माता शीतला',
    type: 'Hindu Temple',
    emoji: '❄️',
    desc: 'गुरुग्राम में स्थित प्रसिद्ध मंदिर, जो माता शीतला को समर्पित है।',
    history:
      'शीतला माता मंदिर गुरुग्राम में स्थित है और यह रोगों, विशेषकर चेचक और संक्रामक रोगों से मुक्ति पाने के लिए पूजा का प्रमुख स्थल माना जाता है। भक्त यहाँ विशेष रूप से मंगलवार और शुक्रवार को आते हैं।',
    timings: '5:30AM – 8:30PM',
    bestTime: 'मंगलवार, नवरात्रि',
    location: 'गुरुग्राम, हरियाणा',
    mapQuery: 'Sheetla+Mata+Temple+Gurugram+Haryana',
    color: '#4DB6AC',
    gradient:
      'linear-gradient(135deg, rgba(77,182,172,0.15), rgba(0,105,92,0.08))',
  },
  {
    id: 'sheetla-mata-jaipur',
    name: 'शीतला माता मंदिर',
    nameEn: 'Sheetla Mata Temple',
    state: 'राजस्थान',
    deity: 'माता शीतला',
    type: 'Hindu Temple',
    emoji: '❄️',
    desc: 'जयपुर में स्थित प्रसिद्ध शीतला माता मंदिर, जहां माता शीतला की पूजा होती है।',
    history:
      'शीतला माता मंदिर जयपुर में स्थित है और यह रोगों और संक्रामक बीमारियों से मुक्ति के लिए प्रसिद्ध है। यहाँ विशेष रूप से शनिवार और मंगलवार को भक्त बड़ी संख्या में आते हैं।',
    timings: '5:30AM – 8:30PM',
    bestTime: 'नवरात्रि, शनिवार और मंगलवार',
    location: 'जयपुर, राजस्थान',
    mapQuery: 'Sheetla+Mata+Temple+Jaipur+Rajasthan',
    color: '#4DB6AC',
    gradient:
      'linear-gradient(135deg, rgba(77,182,172,0.15), rgba(0,105,92,0.08))',
  },
  {
    id: 'sheetla-mata-varanasi',
    name: 'शीतला माता मंदिर',
    nameEn: 'Sheetla Mata Temple',
    state: 'उत्तर प्रदेश',
    deity: 'माता शीतला',
    type: 'Hindu Temple',
    emoji: '❄️',
    desc: 'वाराणसी में स्थित प्रसिद्ध शीतला माता मंदिर, जो माता शीतला को समर्पित है।',
    history:
      'शीतला माता मंदिर वाराणसी में स्थित है और यह विशेष रूप से संक्रामक रोगों और चेचक से मुक्ति पाने के लिए पूजा का प्रमुख स्थल माना जाता है। भक्त यहाँ मंगलवार और शनिवार को बड़े पैमाने पर आते हैं।',
    timings: '5:30AM – 8:30PM',
    bestTime: 'मंगलवार, शनिवार, नवरात्रि',
    location: 'वाराणसी, उत्तर प्रदेश',
    mapQuery: 'Sheetla+Mata+Temple+Varanasi+UP',
    color: '#4DB6AC',
    gradient:
      'linear-gradient(135deg, rgba(77,182,172,0.15), rgba(0,105,92,0.08))',
  },
  {
    id: 'kalika-mata-ujjain',
    name: 'कालिका माता मंदिर',
    nameEn: 'Kalika Mata Temple',
    state: 'मध्य प्रदेश',
    deity: 'माता महाकाली (दुर्गा)',
    type: 'Hindu Temple',
    emoji: '🌺',
    desc: 'उज्जैन में स्थित प्रसिद्ध मंदिर, जो माता कालिका को समर्पित है।',
    history:
      'कालिका माता मंदिर उज्जैन में स्थित है और यह शक्ति और दुर्गा उपासना का प्रमुख केंद्र माना जाता है। यहाँ भक्त विशेष रूप से नवरात्रि के दौरान बड़ी संख्या में आते हैं।',
    timings: '5:00AM – 9:00PM',
    bestTime: 'नवरात्रि, अक्टूबर–मार्च',
    location: 'उज्जैन, मध्य प्रदेश',
    mapQuery: 'Kalika+Mata+Temple+Ujjain+Madhya+Pradesh',
    color: '#E57373',
    gradient:
      'linear-gradient(135deg, rgba(229,115,115,0.15), rgba(198,40,40,0.08))',
  },
  {
    id: 'mahakali-kashi',
    name: 'महाकाली मंदिर',
    nameEn: 'Mahakali Temple',
    state: 'उत्तर प्रदेश',
    deity: 'माता महाकाली (दुर्गा)',
    type: 'Hindu Temple',
    emoji: '🕉️',
    desc: 'काशी (वाराणसी) में स्थित प्रसिद्ध मंदिर, जो माता महाकाली को समर्पित है।',
    history:
      'महाकाली मंदिर काशी में स्थित है और इसे शक्ति और दुर्गा उपासना का प्रमुख केंद्र माना जाता है। यहाँ भक्त विशेष रूप से नवरात्रि और महाकाली महोत्सव के दौरान आते हैं।',
    timings: '5:30AM – 9:00PM',
    bestTime: 'नवरात्रि, अक्टूबर–मार्च',
    location: 'वाराणसी, उत्तर प्रदेश',
    mapQuery: 'Mahakali+Temple+Varanasi+UP',
    color: '#D32F2F',
    gradient:
      'linear-gradient(135deg, rgba(211,47,47,0.15), rgba(183,28,28,0.08))',
  },
  {
    id: 'kalika-dham-ambikapur',
    name: 'कालिका धाम',
    nameEn: 'Kalika Dham',
    state: 'छत्तीसगढ़',
    deity: 'माता महाकाली (दुर्गा)',
    type: 'Hindu Temple / Dham',
    emoji: '🌺',
    desc: 'अंबिकापुर में स्थित प्रमुख धार्मिक स्थल, जो माता कालिका को समर्पित है।',
    history:
      'कालिका धाम अंबिकापुर में स्थित है और यह शक्ति उपासना और दुर्गा पूजा का महत्वपूर्ण केंद्र है। यहाँ श्रद्धालु विशेष रूप से नवरात्रि के दौरान बड़ी संख्या में आते हैं।',
    timings: '5:00AM – 8:00PM',
    bestTime: 'नवरात्रि, अक्टूबर–मार्च',
    location: 'अंबिकापुर, छत्तीसगढ़',
    mapQuery: 'Kalika+Dham+Ambikapur+Chhattisgarh',
    color: '#E57373',
    gradient:
      'linear-gradient(135deg, rgba(229,115,115,0.15), rgba(198,40,40,0.08))',
  },
  {
    id: 'gayatri-dham-haridwar',
    name: 'गायत्री तीर्थ',
    nameEn: 'Gayatri Teerth',
    state: 'उत्तराखंड',
    deity: 'गायत्री माता',
    type: 'Hindu Temple / Teerth',
    emoji: '🕉️',
    desc: 'हरिद्वार में स्थित पवित्र गायत्री धाम, जो गायत्री माता को समर्पित है।',
    history:
      'गायत्री तीर्थ हरिद्वार में स्थित है और यह गायत्री माता की पूजा और ध्यान का प्रमुख केंद्र है। यहाँ भक्त विशेष रूप से गायत्री मंत्र जाप और धार्मिक अनुष्ठानों के लिए आते हैं।',
    timings: '5:00AM – 8:00PM',
    bestTime: 'नवरात्रि, गंगा दशहरा, अप्रैल–अक्टूबर',
    location: 'हरिद्वार, उत्तराखंड',
    mapQuery: 'Gayatri+Teerth+Haridwar+Uttarakhand',
    color: '#FFB74D',
    gradient:
      'linear-gradient(135deg, rgba(255,183,77,0.15), rgba(255,143,0,0.08))',
  },
  {
    id: 'panch-gayatri-dham',
    name: 'पंचगायत्री धाम',
    nameEn: 'Panch Gayatri Dham',
    state: 'हिमाचल प्रदेश',
    deity: 'गायत्री माता',
    type: 'Hindu Temple / Dham',
    emoji: '🕉️🏔️',
    desc: 'हिमाचल प्रदेश के पर्वतीय क्षेत्र में स्थित प्रसिद्ध पंचगायत्री धाम, जो गायत्री माता को समर्पित है।',
    history:
      'पंचगायत्री धाम हिमाचल प्रदेश में पर्वतीय क्षेत्र में स्थित है और यह गायत्री माता की पूजा का प्रमुख स्थल माना जाता है। यहाँ भक्त ध्यान, गायत्री मंत्र जाप और नवरात्रि पर्व के दौरान आते हैं।',
    timings: '5:30AM – 7:30PM',
    bestTime: 'नवरात्रि, अप्रैल–अक्टूबर',
    location: 'हिमाचल प्रदेश, भारत',
    mapQuery: 'Panch+Gayatri+Dham+Himachal+Pradesh',
    color: '#4DB6AC',
    gradient:
      'linear-gradient(135deg, rgba(77,182,172,0.15), rgba(0,105,92,0.08))',
  },
  {
    id: 'mahalakshmi-mumbai',
    name: 'महालक्ष्मी मंदिर',
    nameEn: 'Mahalakshmi Temple',
    state: 'महाराष्ट्र',
    deity: 'माता महालक्ष्मी',
    type: 'Hindu Temple',
    emoji: '💰🌺',
    desc: 'मुंबई में स्थित प्रसिद्ध मंदिर, जो माता महालक्ष्मी को समर्पित है।',
    history:
      'महालक्ष्मी मंदिर मुंबई में स्थित है और यह शहर के सबसे पुराने और प्रसिद्ध पूजा स्थलों में से एक है। यहाँ भक्त धन, समृद्धि और सुख-शांति की प्राप्ति के लिए माता महालक्ष्मी की आराधना करते हैं।',
    timings: '6:00AM – 10:00PM',
    bestTime: 'नवरात्रि, दिवाली, अक्टूबर–मार्च',
    location: 'मुंबई, महाराष्ट्र',
    mapQuery: 'Mahalakshmi+Temple+Mumbai+Maharashtra',
    color: '#FFD54F',
    gradient:
      'linear-gradient(135deg, rgba(255,213,79,0.15), rgba(255,179,0,0.08))',
  },
  {
    id: 'vindhyachal-dham',
    name: 'विंध्याचल धाम',
    nameEn: 'Vindhyachal Dham',
    state: 'उत्तर प्रदेश',
    deity: 'माता विन्ध्येश्वरी देवी (दुर्गा)',
    type: 'Shakti Peeth / Dham',
    emoji: '🌺',
    desc: 'मिर्जापुर जिले, उत्तर प्रदेश में स्थित प्रसिद्ध शक्ति पीठ, जो माता विंध्याचल देवी को समर्पित है।',
    history:
      'विंध्याचल धाम मिर्जापुर, उत्तर प्रदेश में स्थित है और इसे शक्ति और दुर्गा उपासना का प्रमुख केंद्र माना जाता है। यहाँ भक्त विशेष रूप से नवरात्रि के दौरान बड़ी संख्या में आते हैं।',
    timings: '5:00AM – 9:00PM',
    bestTime: 'नवरात्रि, चैत्र और शारदीय',
    location: 'मिर्जापुर, उत्तर प्रदेश',
    mapQuery: 'Vindhyachal+Dham+Mirzapur+UP',
    color: '#E57373',
    gradient:
      'linear-gradient(135deg, rgba(229,115,115,0.15), rgba(198,40,40,0.08))',
  },
  {
    id: 'baba-gangaram-dham',
    name: 'बाबा गंगाराम धाम',
    nameEn: 'Baba Gangaram Dham',
    state: 'राजस्थान',
    deity: 'बाबा गंगाराम',
    type: 'Hindu Temple / Dham',
    emoji: '🛕',
    desc: 'झुंझुनू में स्थित श्री पञ्चदेव मंदिर, जिसमें बाबा गंगाराम की प्रतिष्ठित मूर्ति है।',
    history:
      'यह मंदिर झुंझुनू, राजस्थान में स्थित है और इसे बाबा गंगाराम धाम के नाम से भी जाना जाता है। यहाँ भक्त बाबा गंगाराम की पूजा और आशीर्वाद प्राप्त करने के लिए आते हैं।',
    timings: '5:00AM – 8:00PM',
    bestTime: 'नवरात्रि, विशेष धार्मिक उत्सव',
    location: 'झुंझुनू, राजस्थान',
    mapQuery: 'Baba+Gangaram+Dham+Jhunjhunu+Rajasthan',
    color: '#FFB74D',
    gradient:
      'linear-gradient(135deg, rgba(255,183,77,0.15), rgba(255,143,0,0.08))',
  },
  {
    id: 'ramdevra-temple',
    name: 'रामदेवरा मंदिर',
    nameEn: 'Ramdevra Temple',
    state: 'राजस्थान',
    deity: 'रामदेव बाबा',
    type: 'Hindu Temple / Pilgrimage',
    emoji: '🛕',
    desc: 'रामदेव बाबा की समाधिस्थली पर स्थित प्रमुख तीर्थ स्थल और मंदिर।',
    history:
      'रामदेवरा मंदिर राजस्थान में स्थित है और यह रामदेव बाबा की समाधि पर बना प्रमुख तीर्थ स्थल है। यहाँ श्रद्धालु बाबा की भक्ति और चमत्कारों के लिए आते हैं।',
    timings: '5:00AM – 9:00PM',
    bestTime: 'तीर्थ यात्रा, विशेष उत्सव',
    location: 'Ramdevra, राजस्थान',
    mapQuery: 'Ramdevra+Temple+Rajasthan',
    color: '#FF7043',
    gradient:
      'linear-gradient(135deg, rgba(255,112,67,0.15), rgba(191,54,12,0.08))',
  },
  {
    id: 'parshuram-temple-bihar',
    name: 'परशुराम मंदिर',
    nameEn: 'Parshuram Temple',
    state: 'बिहार',
    deity: 'भगवान परशुराम',
    type: 'Hindu Temple',
    emoji: '🪓🛕',
    desc: 'बिहार में स्थित प्रसिद्ध मंदिर, जो भगवान परशुराम को समर्पित है।',
    history:
      'परशुराम मंदिर बिहार में स्थित है और यह भगवान परशुराम की पूजा का प्रमुख स्थल माना जाता है। यहाँ भक्त विशेष रूप से धार्मिक अनुष्ठान और भक्ति के लिए आते हैं।',
    timings: '5:00AM – 8:00PM',
    bestTime: 'नवरात्रि, विशेष धार्मिक उत्सव',
    location: 'बिहार, भारत',
    mapQuery: 'Parshuram+Temple+Bihar',
    color: '#81C784',
    gradient:
      'linear-gradient(135deg, rgba(129,199,132,0.15), rgba(56,142,60,0.08))',
  },
  {
    id: 'govardhan-parvat',
    name: 'गोवर्धन पर्वत',
    nameEn: 'Govardhan Parvat',
    state: 'उत्तर प्रदेश',
    deity: 'गोवर्धन',
    type: 'Pilgrimage / Sacred Hill',
    emoji: '⛰️🕉️',
    desc: 'ब्रज क्षेत्र में स्थित पवित्र गोवर्धन पर्वत, जो भगवान कृष्ण से संबंधित है।',
    history:
      'गोवर्धन पर्वत ब्रज क्षेत्र में स्थित है और इसे भगवान कृष्ण द्वारा गोवर्धन पूजा की परंपरा के लिए प्रसिद्ध माना जाता है। यहाँ भक्त विशेष रूप से गोवर्धन अष्टमी और अन्य धार्मिक अवसरों पर आते हैं।',
    timings: 'सार्वजनिक स्थल, सभी समय खुला',
    bestTime: 'गोवर्धन अष्टमी, अक्टूबर–मार्च',
    location: 'ब्रज क्षेत्र, उत्तर प्रदेश',
    mapQuery: 'Govardhan+Parvat+Braja+UP',
    color: '#FFB74D',
    gradient:
      'linear-gradient(135deg, rgba(255,183,77,0.15), rgba(255,143,0,0.08))',
  },
  {
    id: 'mehndipur-balaji',
    name: 'मेहंदीपुर बालाजी मंदिर',
    nameEn: 'Mehandipur Balaji Temple',
    state: 'राजस्थान',
    deity: 'हनुमान जी (बालाजी)',
    type: 'Hindu Temple',
    emoji: '🛕🙌',
    desc: 'दौसा जिले, राजस्थान में स्थित प्रसिद्ध हनुमान जी का मंदिर।',
    history:
      'मेहंदीपुर बालाजी मंदिर राजस्थान के दौसा जिले में स्थित है और यह हनुमान जी की पूजा का प्रमुख स्थल माना जाता है। भक्त यहाँ विशेष रूप से संकट मुक्ति और मनोवांछित फल की प्राप्ति के लिए आते हैं।',
    timings: '5:00AM – 9:00PM',
    bestTime: 'हनुमान जयंती, मंगलवार, शनिवार',
    location: 'मेहंदीपुर, दौसा जिला, राजस्थान',
    mapQuery: 'Mehandipur+Balaji+Temple+Dausa+Rajasthan',
    color: '#FF7043',
    gradient:
      'linear-gradient(135deg, rgba(255,112,67,0.15), rgba(191,54,12,0.08))',
  },
  {
    id: 'hanuman-karolbagh',
    name: 'हनुमान मंदिर',
    nameEn: 'Hanuman Temple',
    state: 'दिल्ली',
    deity: 'हनुमान जी',
    type: 'Hindu Temple',
    emoji: '🛕🙌',
    desc: 'दिल्ली के करोलबाग में स्थित प्रसिद्ध हनुमान मंदिर।',
    history:
      'हनुमान मंदिर करोलबाग, दिल्ली में स्थित है और यह हनुमान जी की पूजा और भक्तिभाव का प्रमुख स्थल है। भक्त संकट मुक्ति और आशीर्वाद प्राप्ति के लिए यहाँ आते हैं।',
    timings: '5:00AM – 9:00PM',
    bestTime: 'मंगलवार, शनिवार, हनुमान जयंती',
    location: 'करोलबाग, दिल्ली',
    mapQuery: 'Hanuman+Temple+Karolbagh+Delhi',
    color: '#FF7043',
    gradient:
      'linear-gradient(135deg, rgba(255,112,67,0.15), rgba(191,54,12,0.08))',
  },
  {
    id: 'gorakhnath-temple',
    name: 'गोरखनाथ मंदिर',
    nameEn: 'Gorakhnath Temple',
    state: 'उत्तर प्रदेश',
    deity: 'गोरखनाथ जी (नाथ संप्रदाय)',
    type: 'Hindu Temple / Monastery',
    emoji: '🛕🕉️',
    desc: 'गोरखपुर में स्थित प्रसिद्ध गोरखनाथ मंदिर, जो गोरखनाथ जी और नाथ संप्रदाय को समर्पित है।',
    history:
      'गोरखनाथ मंदिर उत्तर प्रदेश के गोरखपुर में स्थित है। यह नाथ संप्रदाय का प्रमुख केंद्र है और यहाँ भक्त योग, साधना और गोरखनाथ जी की भक्ति के लिए आते हैं।',
    timings: '5:00AM – 8:00PM',
    bestTime: 'नवरात्रि, माघ पूर्णिमा',
    location: 'गोरखपुर, उत्तर प्रदेश',
    mapQuery: 'Gorakhnath+Temple+Gorakhpur+UP',
    color: '#8D6E63',
    gradient:
      'linear-gradient(135deg, rgba(141,110,99,0.15), rgba(93,64,55,0.08))',
  },
  {
    id: 'kal-bhairav-varanasi',
    name: 'काल भैरव मंदिर',
    nameEn: 'Kal Bhairav Temple',
    state: 'उत्तर प्रदेश',
    deity: 'काल भैरव और बटुक भैरव',
    type: 'Hindu Temple',
    emoji: '🕉️🛕',
    desc: 'वाराणसी में स्थित प्रसिद्ध काल भैरव मंदिर, जहाँ काल भैरव और बटुक भैरव की पूजा होती है।',
    history:
      'काल भैरव मंदिर वाराणसी में स्थित है और यह भैरव उपासना का प्रमुख स्थल माना जाता है। भक्त यहाँ विशेष रूप से भय निवारण और संकट मुक्ति के लिए आते हैं। बटुक भैरव की भी विशेष पूजा यहाँ की जाती है।',
    timings: '5:30AM – 9:00PM',
    bestTime: 'नवरात्रि, शनि जयंती',
    location: 'वाराणसी, उत्तर प्रदेश',
    mapQuery: 'Kal+Bhairav+Temple+Varanasi+UP',
    color: '#6D4C41',
    gradient:
      'linear-gradient(135deg, rgba(109,76,65,0.15), rgba(62,39,35,0.08))',
  },
  {
    id: 'brahma-temple-pushkar',
    name: 'ब्रह्मा मंदिर',
    nameEn: 'Brahma Temple',
    state: 'राजस्थान',
    deity: 'भगवान ब्रह्मा',
    type: 'Hindu Temple',
    emoji: '🛕🕉️',
    desc: 'पुष्कर, राजस्थान में स्थित प्रसिद्ध ब्रह्मा मंदिर, जो भगवान ब्रह्मा को समर्पित है।',
    history:
      'ब्रह्मा मंदिर पुष्कर में स्थित है और इसे ब्रह्मा जी की पूजा का प्रमुख केंद्र माना जाता है। यह भारत का एकमात्र प्रसिद्ध ब्रह्मा मंदिर है, जहाँ श्रद्धालु विशेष रूप से ब्रह्मा पूजा और पुष्कर मेले के दौरान आते हैं।',
    timings: '6:00AM – 8:00PM',
    bestTime: 'अक्तूबर–नवंबर (पुष्कर मेला), नवरात्रि',
    location: 'पुष्कर, अजमेर जिला, राजस्थान',
    mapQuery: 'Brahma+Temple+Pushkar+Rajasthan',
    color: '#FFB74D',
    gradient:
      'linear-gradient(135deg, rgba(255,183,77,0.15), rgba(255,143,0,0.08))',
  },
  {
    id: 'tryambakeshwar-shani-temple',
    name: 'त्र्यंबकेश्वर शनि मंदिर',
    nameEn: 'Tryambakeshwar Shani Temple',
    state: 'महाराष्ट्र',
    deity: 'शनि देव',
    type: 'Hindu Temple',
    emoji: '🛕🌑',
    desc: 'त्र्यंबकेश्वर में स्थित प्रसिद्ध शनि मंदिर, जो शनि देव को समर्पित है।',
    history:
      'त्र्यंबकेश्वर शनि मंदिर महाराष्ट्र में स्थित है और यह शनि देव की पूजा का प्रमुख केंद्र माना जाता है। यहाँ भक्त विशेष रूप से शनि दोष और ग्रह प्रभाव से मुक्ति पाने के लिए आते हैं।',
    timings: '6:00AM – 8:00PM',
    bestTime: 'शनिवार, विशेष शनि व्रत',
    location: 'त्र्यंबकेश्वर, नासिक जिला, महाराष्ट्र',
    mapQuery: 'Tryambakeshwar+Shani+Temple+Nashik+Maharashtra',
    color: '#455A64',
    gradient:
      'linear-gradient(135deg, rgba(69,90,100,0.15), rgba(38,50,56,0.08))',
  },
  {
    id: 'gogaji-temple-gogameri',
    name: 'गोगाजी मंदिर',
    nameEn: 'Gogaji Temple',
    state: 'राजस्थान',
    deity: 'श्री जाहरवीर गोगाजी महाराज',
    type: 'Hindu Temple / Pilgrimage',
    emoji: '🐍🛕',
    desc: 'हनुमानगढ़ जिले के गोगामेड़ी में स्थित प्रसिद्ध मंदिर, जो गोगाजी महाराज को समर्पित है।',
    history:
      'गोगाजी मंदिर हनुमानगढ़ जिले के गोगामेड़ी में स्थित है और इसे गोगामेड़ी के नाम से भी जाना जाता है। यहाँ भक्त विशेष रूप से गोगाजी महाराज की पूजा और आशीर्वाद प्राप्त करने के लिए आते हैं। यह क्षेत्र सांपों और नाग देवता की पूजा के लिए भी प्रसिद्ध है।',
    timings: '5:00AM – 8:00PM',
    bestTime: 'विशेष पर्व और मेले, मार्च–अक्टूबर',
    location: 'गोगामेड़ी, हनुमानगढ़ जिला, राजस्थान',
    mapQuery: 'Gogaji+Temple+Gogameri+Hanumangarh+Rajasthan',
    color: '#FF7043',
    gradient:
      'linear-gradient(135deg, rgba(255,112,67,0.15), rgba(191,54,12,0.08))',
  },
  {
    id: 'vishwakarma-temple-jalor',
    name: 'विश्वकर्मा मंदिर',
    nameEn: 'Vishwakarma Temple',
    state: 'राजस्थान',
    deity: 'भगवान विश्वकर्मा',
    type: 'Hindu Temple',
    emoji: '🛠️🛕',
    desc: 'जालोर जिले, हरजी में स्थित प्रसिद्ध मंदिर, जो भगवान विश्वकर्मा को समर्पित है।',
    history:
      'विश्वकर्मा मंदिर हरजी, जालोर जिले में स्थित है और यह भगवान विश्वकर्मा की पूजा का प्रमुख केंद्र है। यहाँ भक्त विशेष रूप से कौशल, निर्माण और कला में सफलता के लिए आते हैं।',
    timings: '6:00AM – 8:00PM',
    bestTime: 'विशेष पूजन और विश्वकर्मा जयंती',
    location: 'हरजी, जालोर जिला, राजस्थान',
    mapQuery: 'Vishwakarma+Temple+Harji+Jalor+Rajasthan',
    color: '#FFB74D',
    gradient:
      'linear-gradient(135deg, rgba(255,183,77,0.15), rgba(255,143,0,0.08))',
  },
  {
    id: 'guru-ravidass-temple-varanasi',
    name: 'श्री गुरु रविदास मंदिर',
    nameEn: 'Shri Guru Ravidass Temple',
    state: 'उत्तर प्रदेश',
    deity: 'श्री गुरु रविदास जी',
    type: 'Hindu Temple / Gurudwara',
    emoji: '🛕🙏',
    desc: 'वाराणसी में स्थित प्रमुख मंदिर, जो संत रविदास जी के जन्मस्थान (सीर गोवर्धनपुर) पर बना है।',
    history:
      'श्री गुरु रविदास मंदिर वाराणसी, उत्तर प्रदेश में स्थित है और इसे संत रविदास जी के सम्मान में स्थापित किया गया है। यहाँ भक्त उनकी भक्ति, शिक्षाओं और सामाजिक न्याय के संदेश के लिए आते हैं।',
    timings: '5:00AM – 8:00PM',
    bestTime: 'रविदास जयंती, विशेष धार्मिक अवसर',
    location: 'सीर गोवर्धनपुर, वाराणसी, उत्तर प्रदेश',
    mapQuery: 'Shri+Guru+Ravidass+Temple+Varanasi+UP',
    color: '#FFD54F',
    gradient:
      'linear-gradient(135deg, rgba(255,213,79,0.15), rgba(255,179,0,0.08))',
  },
  {
    id: 'mahavir-temple-patna',
    name: 'महावीर मंदिर',
    nameEn: 'Mahavir Temple',
    state: 'बिहार',
    deity: 'भगवान महावीर',
    type: 'Jain Temple',
    emoji: '🛕✡️',
    desc: 'पटना में स्थित प्रसिद्ध जैन मंदिर, जो भगवान महावीर को समर्पित है।',
    history:
      'महावीर मंदिर पटना, बिहार में स्थित है और यह जैन धर्म का प्रमुख केंद्र माना जाता है। यहाँ भक्त भगवान महावीर की पूजा और साधना के लिए आते हैं।',
    timings: '5:00AM – 9:00PM',
    bestTime: 'महावीर जयंती, नवरात्रि',
    location: 'पटना, बिहार',
    mapQuery: 'Mahavir+Temple+Patna+Bihar',
    color: '#FFB74D',
    gradient:
      'linear-gradient(135deg, rgba(255,183,77,0.15), rgba(255,143,0,0.08))',
  },
  {
    id: 'dwarka-temple',
    name: 'द्वारका मंदिर',
    nameEn: 'Dwarka Temple',
    state: 'गुजरात',
    deity: 'भगवान कृष्ण',
    type: 'Char Dham',
    emoji: '🛕🕉️',
    desc: 'गुजरात के द्वारका में स्थित प्रसिद्ध मंदिर, जो भगवान कृष्ण को समर्पित है।',
    history:
      'द्वारका मंदिर द्वारका, गुजरात में स्थित है और यह भगवान कृष्ण की पूजा का प्राचीन स्थल माना जाता है। इसे चार धामों में से एक के रूप में विशेष महत्व प्राप्त है। यहाँ भक्त राधा-कृष्ण भक्ति और दर्शन के लिए आते हैं।',
    timings: '5:00AM – 9:00PM',
    bestTime: 'जन्माष्टमी, विशेष उत्सव',
    location: 'द्वारका, गुजरात',
    mapQuery: 'Dwarka+Temple+Gujarat',
    color: '#4DB6AC',
    gradient:
      'linear-gradient(135deg, rgba(77,182,172,0.15), rgba(0,105,92,0.08))',
  },
  {
    id: 'mahakaleshwar-jyotirlinga',
    name: 'महाकालेश्वर ज्योतिर्लिंग',
    nameEn: 'Mahakaleshwar Jyotirlinga',
    state: 'मध्य प्रदेश',
    deity: 'भगवान शिव',
    type: 'Jyotirlinga',
    emoji: '🕉️',
    desc: 'उज्जैन में स्थित प्राचीन ज्योतिर्लिंग, जो भगवान शिव को समर्पित है।',
    history:
      'महाकालेश्वर ज्योतिर्लिंग उज्जैन, मध्य प्रदेश में स्थित है और यह भारत के 12 ज्योतिर्लिंगों में से एक माना जाता है। यह मंदिर भोलेनाथ की महाशक्ति और काल स्वरूप पूजा का प्रमुख केंद्र है।',
    timings: '5:00AM – 10:00PM',
    bestTime: 'महाशिवरात्रि, श्रावण मास',
    location: 'उज्जैन, मध्य प्रदेश',
    mapQuery: 'Mahakaleshwar+Jyotirlinga+Ujjain+Madhya+Pradesh',
    color: '#4DB6AC',
    gradient:
      'linear-gradient(135deg, rgba(77,182,172,0.15), rgba(0,105,92,0.08))',
  },
  {
    id: 'brihaspati-dham-temple',
    name: 'बृहस्पति धाम मंदिर',
    nameEn: 'Brihaspati Dham Temple',
    state: 'उत्तर प्रदेश',
    deity: 'बृहस्पति देव (गुरु ग्रह)',
    type: 'Hindu Temple',
    emoji: '🛕🪐',
    desc: 'बृहस्पति देव को समर्पित प्रसिद्ध मंदिर, जहाँ गुरु ग्रह की पूजा की जाती है।',
    history:
      'बृहस्पति धाम मंदिर उत्तर प्रदेश में स्थित है और यह देवगुरु बृहस्पति को समर्पित है। श्रद्धालु यहाँ विशेष रूप से गुरु दोष शांति, ज्ञान और समृद्धि की कामना से पूजा-अर्चना करने आते हैं।',
    timings: '6:00AM – 8:00PM',
    bestTime: 'गुरुवार, विशेष गुरु पूजा',
    location: 'उत्तर प्रदेश, भारत',
    mapQuery: 'Brihaspati+Dham+Temple+Uttar+Pradesh',
    color: '#FFD54F',
    gradient:
      'linear-gradient(135deg, rgba(255,213,79,0.15), rgba(255,179,0,0.08))',
  },
  {
    id: 'brihaspateeshwar-temple',
    name: 'बृहस्पतेश्वर मंदिर',
    nameEn: 'Brihaspateeshwar Temple',
    state: 'महाराष्ट्र',
    deity: 'भगवान शिव (बृहस्पतेश्वर रूप)',
    type: 'Hindu Temple',
    emoji: '🛕🕉️',
    desc: 'महाराष्ट्र में स्थित प्राचीन मंदिर, जहाँ भगवान शिव के बृहस्पतेश्वर रूप की पूजा की जाती है।',
    history:
      'बृहस्पतेश्वर मंदिर महाराष्ट्र में स्थित है और यह भगवान शिव के विशेष रूप बृहस्पतेश्वर को समर्पित है। यहाँ श्रद्धालु विशेष रूप से गुरु ग्रह से संबंधित दोषों की शांति और आध्यात्मिक उन्नति के लिए पूजा करने आते हैं।',
    timings: '6:00AM – 8:00PM',
    bestTime: 'गुरुवार, महाशिवरात्रि',
    location: 'महाराष्ट्र, भारत',
    mapQuery: 'Brihaspateeshwar+Temple+Maharashtra',
    color: '#90CAF9',
    gradient:
      'linear-gradient(135deg, rgba(144,202,249,0.15), rgba(25,118,210,0.08))',
  },
  {
    id: 'alangudi-guru-bhagavan-temple',
    name: 'आलंगुडी गुरु भगवान मंदिर',
    nameEn: 'Alangudi Guru Bhagavan Temple',
    state: 'तमिलनाडु',
    deity: 'गुरु भगवान (बृहस्पति)',
    type: 'Hindu Temple',
    emoji: '🛕🪐',
    desc: 'तमिलनाडु के आलंगुडी में स्थित प्रसिद्ध मंदिर, जो गुरु ग्रह (बृहस्पति) को समर्पित है।',
    history:
      'आलंगुडी गुरु भगवान मंदिर तमिलनाडु में स्थित है और यह नवग्रह मंदिरों में से एक प्रमुख मंदिर माना जाता है। यहाँ श्रद्धालु विशेष रूप से गुरु ग्रह की कृपा प्राप्त करने और गुरु दोष की शांति के लिए पूजा-अर्चना करते हैं।',
    timings: '6:00AM – 8:30PM',
    bestTime: 'गुरुवार, गुरु परिवर्तन, नवग्रह पूजा',
    location: 'आलंगुडी, तंजावुर जिला, तमिलनाडु',
    mapQuery: 'Alangudi+Guru+Bhagavan+Temple+Tamil+Nadu',
    color: '#FFD54F',
    gradient:
      'linear-gradient(135deg, rgba(255,213,79,0.15), rgba(255,179,0,0.08))',
  },
];
