// ============ DATA ============
const deities = {
  ganesh: {
    name: 'श्री गणेश',
    english: 'Shri Ganesh',
    emoji: '🐘',
    color: '#FF6B00',
    desc: 'विघ्नहर्ता, प्रथम पूजनीय',
    img: 'icons/ganesh.webp',
  },
  shiva: {
    name: 'श्री शिव',
    english: 'Shri Shiv',
    emoji: '🔱',
    color: '#4169E1',
    desc: 'महादेव, भोलेनाथ, संहारक',
    img: 'icons/shiv.webp',
  },
  parvati: {
    name: 'श्री पार्वतीदेवी',
    english: 'Shri Parvati',
    emoji: '🪷',
    color: '#AD1457',
    desc: 'शिवांची अर्धांगिनी, शक्ती आणि मातृत्वाची देवी',
    img: 'icons/parvati.webp',
  },
  vishnu: {
    name: 'श्री विष्णु',
    english: 'Shri Vishnu',
    emoji: '✨',
    color: '#0080FF',
    desc: 'पालनकर्ता, नारायण, जगाचा पोषणकर्ता',
    img: 'icons/vishnu.webp',
  },
  lakshmi: {
    name: 'श्री लक्ष्मी',
    english: 'Shri Lakshmi',
    emoji: '🪷',
    color: '#FFD700',
    desc: 'धनदेवी, कमलवासिनी, समृद्धीची देवी',
    img: 'icons/lakshmi.webp',
  },
  durga: {
    name: 'श्री दुर्गा',
    english: 'Shri Durga',
    emoji: '🌸',
    color: '#FF1493',
    desc: 'आदिशक्ती, महामाया, सिंहवाहिनी',
    img: 'icons/durga.webp',
  },
  kali: {
    name: 'श्री काली',
    english: 'Shri Kali',
    emoji: '⚡',
    color: '#800080',
    desc: 'महाकाली, तारा, आद्यशक्तीचे उग्र रूप',
    img: 'icons/kali.webp',
  },
  ram: {
    name: 'श्री राम',
    english: 'Shri Ram',
    emoji: '🏹',
    color: '#00AA00',
    desc: 'मर्यादा पुरुषोत्तम, रघुकुलाचे भूषण',
    img: 'icons/ram.webp',
  },
  hanuman: {
    name: 'श्री हनुमान',
    english: 'Shri Hanuman',
    emoji: '🙏',
    color: '#FF4500',
    desc: 'पवनपुत्र, बजरंगबली, रामभक्त शिरोमणी',
    img: 'icons/hanuman.webp',
  },
  balaji: {
    name: 'श्री बालाजी',
    english: 'Shri Balaji',
    emoji: '🏹',
    color: '#8D6E63',
    desc: 'संकटमोचक, पूज्य स्वरूप',
    img: 'icons/balaji.webp',
  },
  pretraj_sarkar: {
    name: 'श्री प्रेतराज सरकार',
    english: 'Shri Pretraj Sarkar',
    emoji: '🔥',
    color: '#4E342E',
    desc: 'नकारात्मक बाधा दूर करणारा',
    img: 'icons/pretraj_sarkar.webp',
  },
  krishna: {
    name: 'श्री कृष्ण',
    english: 'Shri Krishna',
    emoji: '🪈',
    color: '#0000CD',
    desc: 'गोविंद, मुरलीमनोहर, ब्रजबिहारी',
    img: 'icons/krishna.webp',
    geeta: typeof geetaData !== 'undefined' ? geetaData.krishna : null,
  },
  khatu_shyam: {
    name: 'श्री खाटू श्याम',
    english: 'Shri Khatu Shyam',
    emoji: '🏹',
    color: '#FF4500',
    desc: 'पराभूतांचा आधार, मोरवीनंदन, कलियुगातील अवतारी',
    img: 'icons/khatu_shyam.webp',
  },
  tirupati_balaji: {
    name: 'श्री तिरुपती बालाजी',
    english: 'Tirupati Bala Ji',
    emoji: '🌟',
    color: '#FFD54F',
    desc: 'श्री वेंकटेश्वर, विष्णूचे पूज्य रूप',
    img: 'icons/tirupati_balaji.webp',
  },
  jagannath: {
    name: 'श्री जगन्नाथ',
    english: 'Jagannath',
    emoji: '🕉️',
    color: '#4CAF50',
    desc: 'पुरीचे प्रसिद्ध देवता, भगवान विष्णूचे रूप आणि भक्तीचे प्रतीक',
    img: 'icons/jagannath.webp',
  },
  gopal: {
    name: 'श्री गोपाल',
    english: 'Shri Gopal',
    emoji: '🐄',
    color: '#5C6BC0',
    desc: 'बालगोविंद, गोपालक, करुणामय',
    img: 'icons/gopal.webp',
  },
  surya: {
    name: 'श्री सूर्य',
    english: 'Shri Surya',
    emoji: '☀️',
    color: '#FF8C00',
    desc: 'प्रत्यक्ष देव, जगाचे नेत्र, ऊर्जेचा स्रोत',
    img: 'icons/surya.webp',
  },
  shani: {
    name: 'श्री शनी देव',
    english: 'Shri Shani Dev',
    emoji: '⚖️',
    color: '#1a1a1a',
    desc: 'कर्मफलदाता, सूर्यपुत्र, न्यायाचे देवता',
    img: 'icons/shani.webp',
  },
  brihaspati: {
    name: 'श्री बृहस्पती देव',
    english: 'Shri Brihaspati Dev',
    emoji: '📜',
    color: '#EF6C00',
    desc: 'वेदज्ञ, गुरु, न्यायाचे देवता',
    img: 'icons/brihaspati.webp',
  },
  brahma: {
    name: 'श्री ब्रह्मा',
    english: 'Shri Brahma',
    emoji: '📜',
    color: '#EF6C00',
    desc: 'सृष्टिकर्ता, वेदज्ञ, चतुर्मुख',
    img: 'icons/brahma.webp',
  },
  saraswati: {
    name: 'श्री सरस्वती',
    english: 'Shri Saraswati',
    emoji: '🎵',
    color: '#FFFFFF',
    desc: 'विद्यादायिनी, वागदेवी, वीणावादिनी',
    img: 'icons/saraswati.webp',
  },
  bhairav: {
    name: 'श्री भैरव',
    english: 'Shri Bhairav',
    emoji: '🐕',
    color: '#37474F',
    desc: 'क्षेत्रपाल, रक्षक, उग्र करुणामय',
    img: 'icons/bhairav.webp',
  },
  batuk_bhairav: {
    name: 'श्री बटुक भैरव',
    english: 'Shri Batuk Bhairav',
    emoji: '🛡️',
    color: '#455A64',
    desc: 'बाल भैरव, तत्काळ रक्षक',
    img: 'icons/batuk_bhairav.webp',
  },
  parshuram: {
    name: 'श्री परशुराम',
    english: 'Shri Parshuram',
    emoji: '🪓',
    color: '#5D4037',
    desc: 'विष्णू अवतार, धर्मरक्षक',
    img: 'icons/parshuram.webp',
  },
  giriraj: {
    name: 'श्री गिरिराज',
    english: 'Shri Giriraj',
    emoji: '⛰️',
    color: '#7CB342',
    desc: 'गोवर्धन स्वरूप, शरणदाता',
    img: 'icons/giriraj.webp',
  },
  navgrah: {
    name: 'श्री नवग्रह',
    english: 'Shri Navgrah',
    emoji: '🪐',
    color: '#546E7A',
    desc: 'नऊ ग्रहांचे सामूहिक पूजन',
    img: 'icons/navgrah.webp',
  },
  vishwakarma: {
    name: 'श्री विश्वकर्मा',
    english: 'Shri Vishwakarma',
    emoji: '🛠️',
    color: '#6D4C41',
    desc: 'देवशिल्पी, निर्माणदेव',
    img: 'icons/vishwakarma.webp',
  },
  sai: {
    name: 'श्री साईं',
    english: 'Shri Sai',
    emoji: '🕯️',
    color: '#9E9D24',
    desc: 'श्रद्धा आणि सबुरीचे प्रतीक',
    img: 'icons/sai.webp',
  },
  mahavir: {
    name: 'श्री महावीर',
    english: 'Shri Mahavir',
    emoji: '🪷',
    color: '#26A69A',
    desc: 'अहिंसा, तप आणि सत्याचे आदर्श',
    img: 'icons/mahavir.webp',
  },
  pitar: {
    name: 'श्री पितृदेव',
    english: 'Shri Pitar',
    emoji: '🕯',
    color: '#6D4C41',
    desc: 'पूर्वजपूजन, कुळाचे आशीर्वाद',
    img: 'icons/pitar.webp',
  },
  vaishno_devi: {
    name: 'श्री वैष्णो देवी',
    english: 'Shri Vaishno Devi',
    emoji: '🛕',
    color: '#C2185B',
    desc: 'त्रिकुटावासिनी, शक्तिस्वरूपा',
    img: 'icons/vaishno_devi.webp',
  },
  sheetla: {
    name: 'श्री शीतला',
    english: 'Shri Sheetla',
    emoji: '🧺',
    color: '#00ACC1',
    desc: 'आरोग्यदायिनी माता',
    img: 'icons/sheetla.webp',
  },
  mahakali: {
    name: 'श्री महाकाली',
    english: 'Shri Mahakali',
    emoji: '⚔️',
    color: '#283593',
    desc: 'काळविनाशिनी, अदम्य शक्ती',
    img: 'icons/mahakali.webp',
  },
  baglamukhi: {
    name: 'श्री बगलामुखी',
    english: 'Shri Baglamukhi',
    emoji: '🟡',
    color: '#FBC02D',
    desc: 'दशमहाविद्या, स्तंभन शक्ती',
    img: 'icons/baglamukhi.webp',
  },
  mahalakshmi: {
    name: 'श्री महालक्ष्मी',
    english: 'Shri Mahalakshmi',
    emoji: '💰',
    color: '#F9A825',
    desc: 'ऐश्वर्य, सौभाग्य, मंगलमयी',
    img: 'icons/mahalakshmi.webp',
  },
  gayatri: {
    name: 'श्री गायत्री',
    english: 'Shri Gayatri',
    emoji: '📿',
    color: '#FF7043',
    desc: 'वेदमाता, बुद्धी प्रदान करणारी',
    img: 'icons/gayatri.webp',
  },
  sharda: {
    name: 'श्री शारदा',
    english: 'Shri Sharda',
    emoji: '📖',
    color: '#5E35B1',
    desc: 'ज्ञान आणि वाणीचे स्वरूप',
    img: 'icons/sharda.webp',
  },
  radha: {
    name: 'श्री राधा',
    english: 'Shri Radha',
    emoji: '🌸',
    color: '#EC407A',
    desc: 'भक्ती आणि प्रेमाची अधिष्ठात्री',
    img: 'icons/radha.webp',
  },
  santoshi_maa: {
    name: 'श्री संतोषी माता',
    english: 'Shri Santoshi Maa',
    emoji: '🍚',
    color: '#F06292',
    desc: 'संतोष, सुख आणि साधी भक्ती',
    img: 'icons/santoshi_maa.webp',
  },
  vindhyeshwari: {
    name: 'श्री विंध्येश्वरी',
    english: 'Shri Vindhyeshwari',
    emoji: '🌺',
    color: '#D81B60',
    desc: 'विंध्यवासिनी मातेचे स्वरूप',
    img: 'icons/vindhyeshwari.webp',
  },
  annapurna: {
    name: 'श्री अन्नपूर्णा',
    english: 'Shri Annapurna',
    emoji: '🍲',
    color: '#FF8F00',
    desc: 'अन्न, पोषण आणि करुणेची देवी',
    img: 'icons/annapurna.webp',
  },
  tulsi: {
    name: 'श्री तुलसी',
    english: 'Shri Tulsi',
    emoji: '🌿',
    color: '#43A047',
    desc: 'पवित्रता, भक्ती आणि संरक्षण',
    img: 'icons/tulsi.webp',
  },
  ganga: {
    name: 'श्री गंगा',
    english: 'Shri Ganga',
    emoji: '🌊',
    color: '#1E88E5',
    desc: 'पवित्र नदी, मोक्षदायिनी',
    img: 'icons/ganga.webp',
  },
  narmada: {
    name: 'श्री नर्मदा',
    english: 'Shri Narmada',
    emoji: '💧',
    color: '#039BE5',
    desc: 'रेवा माता, पुण्यदायिनी',
    img: 'icons/narmada.webp',
  },
  shakambhari: {
    name: 'श्री शाकंभरी',
    english: 'Shri Shakambhari',
    emoji: '🥬',
    color: '#7CB342',
    desc: 'अन्न आणि वनस्पतींची पोषक देवी',
    img: 'icons/shakambhari.webp',
  },
  lalita_shakambhari: {
    name: 'श्री ललिता शाकंभरी',
    english: 'Shri Lalita Shakambhari',
    emoji: '🌼',
    color: '#8BC34A',
    desc: 'ललिता आणि शाकंभरीचे संयुक्त रूप',
    img: 'icons/lalita_shakambhari.webp',
  },
  rani_sati: {
    name: 'श्री राणी सती',
    english: 'Shri Rani Sati',
    emoji: '🏵️',
    color: '#8E24AA',
    desc: 'लोकआस्थेची पूज्य मातृशक्ती',
    img: 'icons/rani_sati.webp',
  },
  ravidas: {
    name: 'श्री रविदास',
    english: 'Shri Ravidas',
    emoji: '🙏',
    color: '#8D6E63',
    desc: 'भक्तिसंत, समतेचा संदेश',
    img: 'icons/ravidas.webp',
  },
  baba_gangaram: {
    name: 'श्री बाबा गंगाराम',
    english: 'Shri Baba Gangaram',
    emoji: '🛕',
    color: '#6A1B9A',
    desc: 'लोकश्रद्धेचे पूज्य संत',
    img: 'icons/baba_gangaram.webp',
  },
  ramdev: {
    name: 'श्री रामदेव',
    english: 'Shri Ramdev',
    emoji: '🐎',
    color: '#8E24AA',
    desc: 'लोकदेव, जनकल्याणकारी',
    img: 'icons/ramdev.webp',
  },
  jaharveer: {
    name: 'श्री जाहरवीर',
    english: 'Shri Jaharveer',
    emoji: '🏇',
    color: '#795548',
    desc: 'लोकरक्षक, वीरदेव',
    img: 'icons/jaharveer.webp',
  },
  gorakh_nath: {
    name: 'श्री गोरखनाथ',
    english: 'Shri Gorakh Nath',
    emoji: '🧘',
    color: '#607D8B',
    desc: 'नाथयोग परंपरेचे आचार्य',
    img: 'icons/gorakh_nath.webp',
  },
};
