// Custom deity URL aliases mapped to canonical deity keys in `deities`.
// Example: /mahakal/about -> /shiva/about
window.deityAliases = {
  ganesh: ['ganesha', 'ganpati', 'ganapati', 'vinayak', 'vighnaharta', 'गणेश', 'गणेशा', 'गणपति', 'विनायक', 'विघ्नहर्ता'],
  shiva: ['shiv', 'mahadev', 'mahakal', 'shankar', 'shambhu', 'bholenath', 'bhole', 'neelkanth', 'रुद्र', 'शिव', 'शंकर', 'शम्भु', 'भोले', 'भोलेनाथ', 'महादेव', 'महाकाल', 'नीलकंठ'],
  durga: ['maa durga', 'durga maa', 'jagdambe', 'jagdamba', 'दुर्गा', 'मां दुर्गा', 'माता दुर्गा', 'जगदम्बा', 'जगदंबा'],
  lakshmi: ['laxmi', 'mahalaxmi', 'maha lakshmi', 'shri lakshmi', 'लक्ष्मी', 'महालक्ष्मी', 'श्री लक्ष्मी'],
  saraswati: ['sarasvati', 'maa saraswati', 'vidya devi', 'सरस्वती', 'सरस्वति', 'मां सरस्वती', 'विद्या देवी'],
  vishnu: ['narayan', 'narayana', 'hari', 'vishan', 'विष्णु', 'नारायण', 'हरि'],
  ram: ['rama', 'shri ram', 'lord ram', 'raghunath', 'सीताराम', 'राम', 'श्री राम', 'रघुनाथ'],
  krishna: ['krishn', 'kanha', 'kanhaiya', 'govind', 'gopal', 'murlidhar', 'madhav', 'कृष्ण', 'कान्हा', 'कन्हैया', 'गोविंद', 'मुरलीधर', 'माधव'],
  hanuman: ['bajrangbali', 'pavanputra', 'anjaneya', 'maruti', 'sankatmochan', 'हनुमान', 'बजरंगबली', 'पवनपुत्र', 'मारुति', 'संकटमोचन'],
  surya: ['sun god', 'aditya', 'bhaskar', 'dinakar', 'सूर्य', 'आदित्य', 'भास्कर', 'दिनकर'],
  kali: ['kaali', 'maa kali', 'dakshina kali', 'काली', 'काळी', 'मां काली'],
  khatu_shyam: ['khatu shyamji', 'shyam baba', 'hare ka sahara', 'khatu', 'खाटू श्याम', 'खाटूश्याम', 'श्याम बाबा', 'हारे का सहारा'],
  shani: ['shanidev', 'shani dev', 'शनिदेव', 'शनि देव', 'शनि'],
  gopal: ['bal gopal', 'laddu gopal', 'गोपाल', 'बाल गोपाल', 'लड्डू गोपाल'],
  brahma: ['brahmaji', 'ब्रह्मा', 'ब्रह्माजी'],
  bhairav: ['kal bhairav', 'kaal bhairav', 'भैरव', 'काल भैरव', 'कालभैरव'],
  batuk_bhairav: ['batuk bhairav', 'batuk', 'बटुक भैरव', 'बटुकभैरव'],
  navgrah: ['navgraha', 'navagraha', 'nau grah', 'nav grah', 'नवग्रह', 'नौ ग्रह'],
  vishwakarma: ['vishvakarma', 'विश्वकर्मा', 'विश्वकर्मा जी'],
  ravidas: ['raidas', 'guru ravidas', 'रविदास', 'रैदास', 'गुरु रविदास'],
  gorakh_nath: ['gorakhnath', 'gorakh', 'नाथ', 'गोरखनाथ', 'गोरख नाथ'],
  jaharveer: ['jahar veer', 'gogaji', 'goga ji', 'जाहरवीर', 'जाहर वीर', 'गोगाजी', 'गोगा जी'],
  pretraj_sarkar: ['pretraj', 'pret raj', 'प्रेतराज', 'प्रेत राज', 'प्रेतराज सरकार'],
  balaji: ['salasar balaji', 'mehandipur balaji', 'बालाजी', 'सालासर बालाजी', 'मेहंदीपुर बालाजी'],
  tirupati_balaji: ['tirupati balaji', 'tirupati bala ji', 'venkateswara', 'venkateshwar', 'वेंकटेश्वर', 'तिरुपति बालाजी', 'तिरुपति बाला जी'],
  sai: ['saibaba', 'sai baba', 'shirdi sai', 'शिरडी साईं', 'साईं', 'साई', 'साईंबाबा', 'साईं बाबा'],
  giriraj: ['giriraj ji', 'govardhan', 'giriraj maharaj', 'गिरिराज', 'गिरिराज जी', 'गोवर्धन', 'गिरिराज महाराज'],
  mahavir: ['mahaveer', 'vardhaman', 'महावीर', 'महावीर स्वामी', 'वर्धमान'],
  parshuram: ['parashuram', 'bhargava ram', 'परशुराम', 'परशु राम'],
  ramdev: ['ramdevji', 'baba ramdev', 'रामदेव', 'रामदेवजी', 'बाबा रामदेव'],
  pitar: ['pitra', 'pitru', 'pitra dev', 'pitr dev', 'पितर', 'पितृ', 'पितृ देव', 'पितर देव'],
  baba_gangaram: ['gangaram', 'baba ganga ram', 'बाबा गंगाराम', 'गंगाराम'],
  vindhyeshwari: ['vindhyavasini', 'maa vindhyavasini', 'विन्ध्येश्वरी', 'विंध्येश्वरी', 'विंध्यवासिनी', 'मां विंध्यवासिनी'],
  mahalakshmi: ['maha lakshmi', 'mahalaxmi', 'महालक्ष्मी', 'महालक्ष्मी माता'],
  gayatri: ['gaytri', 'maa gayatri', 'गायत्री', 'गायत्री माता', 'मां गायत्री'],
  mahakali: ['maha kali', 'mahakaali', 'महाकाली', 'महा काली'],
  sheetla: ['sheetla mata', 'shitala', 'shitala mata', 'शीतला', 'शीतला माता'],
  radha: ['radharani', 'radha rani', 'राधा', 'राधारानी', 'राधा रानी'],
  tulsi: ['tulasi', 'vrinda', 'तुलसी', 'तुलसी माता', 'वृंदा'],
  vaishno_devi: ['vaishnodevi', 'mata rani', 'vaishno mata', 'वैष्णो देवी', 'वैष्णोदेवी', 'माता रानी', 'वैष्णो माता'],
  santoshi_maa: ['santoshi maa', 'santoshi mata', 'संतोषी मां', 'संतोषी माता', 'सन्तोषी माता'],
  annapurna: ['annpoorna', 'maa annapurna', 'अन्नपूर्णा', 'मां अन्नपूर्णा'],
  parvati: ['parvathi', 'maa parvati', 'gauri', 'पार्वती', 'पार्वती माता', 'गौरी'],
  baglamukhi: ['bagla mukhi', 'baglamukhi mata', 'बगलामुखी', 'बगला मुखी', 'बगलामुखी माता'],
  ganga: ['ganga maiya', 'ganga mata', 'गंगा', 'गंगा मैया', 'गंगा माता'],
  narmada: ['narmada maiya', 'rewa', 'नर्मदा', 'नर्मदा मैया', 'रेवा'],
  sharda: ['sharada', 'maa sharda', 'सरदा', 'शारदा', 'मां शारदा'],
  shakambhari: ['shakumbhari', 'shakambhari mata', 'शाकम्भरी', 'शाकंभरी', 'शाकम्भरी माता'],
  lalita_shakambhari: ['lalita shakambhari', 'lalita', 'ललिता शाकम्भरी', 'ललिता शाकंभरी', 'ललिता'],
  rani_sati: ['rani sati dadi', 'dadiji', 'रानी सती', 'रानी सती दादी', 'दादीजी'],
};
