// ============ DATA ============
const deities = {
  ganesh: {
    name: 'శ్రీ గణేశ్',
    english: 'Shri Ganesh',
    emoji: '🐘',
    color: '#FF6B00',
    desc: 'విఘ్నహర్త, ప్రథమ పూజ్యుడు',
    img: 'icons/ganesh.webp',
  },
  shiva: {
    name: 'శ్రీ శివుడు',
    english: 'Shri Shiv',
    emoji: '🔱',
    color: '#4169E1',
    desc: 'మహాదేవుడు, భోలేనాథ్, సంహారకుడు',
    img: 'icons/shiv.webp',
  },
  parvati: {
    name: 'శ్రీ పార్వతీ దేవి',
    english: 'Shri Parvati',
    emoji: '🪷',
    color: '#AD1457',
    desc: 'శివుని అర్ధాంగి, శక్తి మరియు మాతృత్వ దేవి',
    img: 'icons/parvati.webp',
  },
  vishnu: {
    name: 'శ్రీ విష్ణు',
    english: 'Shri Vishnu',
    emoji: '✨',
    color: '#0080FF',
    desc: 'పాలకుడు, నారాయణుడు, జగత్తు రక్షకుడు',
    img: 'icons/vishnu.webp',
  },
  lakshmi: {
    name: 'శ్రీ లక్ష్మీ',
    english: 'Shri Lakshmi',
    emoji: '🪷',
    color: '#FFD700',
    desc: 'ధనదాయిని, కమలవాసిని, సమృద్ధి దేవి',
    img: 'icons/lakshmi.webp',
  },
  durga: {
    name: 'శ్రీ దుర్గ',
    english: 'Shri Durga',
    emoji: '🌸',
    color: '#FF1493',
    desc: 'ఆదిశక్తి, మహామాయ, సింహవాహిని',
    img: 'icons/durga.webp',
  },
  kali: {
    name: 'శ్రీ కాళి',
    english: 'Shri Kali',
    emoji: '⚡',
    color: '#800080',
    desc: 'మహాకాళి, తారా, ఆదిశక్తి యొక్క ఉగ్ర రూపం',
    img: 'icons/kali.webp',
  },
  ram: {
    name: 'శ్రీ రాముడు',
    english: 'Shri Ram',
    emoji: '🏹',
    color: '#00AA00',
    desc: 'మర్యాదా పురుషోత్తముడు, రఘుకుల భూషణుడు',
    img: 'icons/ram.webp',
  },
  hanuman: {
    name: 'శ్రీ హనుమాన్',
    english: 'Shri Hanuman',
    emoji: '🙏',
    color: '#FF4500',
    desc: 'పవనపుత్రుడు, బజరంగబలి, రామభక్త శిరోమణి',
    img: 'icons/hanuman.webp',
  },
  balaji: {
    name: 'శ్రీ బాలాజీ',
    english: 'Shri Balaji',
    emoji: '🏹',
    color: '#8D6E63',
    desc: 'సంకటమోచక, పూజ్య స్వరూపం',
    img: 'icons/balaji.webp',
  },
  pretraj_sarkar: {
    name: 'శ్రీ ప్రేతరాజ్ సర్కార్',
    english: 'Shri Pretraj Sarkar',
    emoji: '🔥',
    color: '#4E342E',
    desc: 'ప్రతికూల అడ్డంకులను తొలగించేవారు',
    img: 'icons/pretraj_sarkar.webp',
  },
  krishna: {
    name: 'శ్రీ కృష్ణుడు',
    english: 'Shri Krishna',
    emoji: '🪈',
    color: '#0000CD',
    desc: 'గోవిందుడు, మురళీమనోహరుడు, బ్రజవిహారి',
    img: 'icons/krishna.webp',
    geeta: typeof geetaData !== 'undefined' ? geetaData.krishna : null,
  },
  khatu_shyam: {
    name: 'శ్రీ ఖాటూ శ్యామ్',
    english: 'Shri Khatu Shyam',
    emoji: '🏹',
    color: '#FF4500',
    desc: 'ఓడిపోయినవారికి ఆశ్రయం, మోర్వీ నందన, కలియుగ అవతారుడు',
    img: 'icons/khatu_shyam.webp',
  },
  tirupati_balaji: {
    name: 'శ్రీ తిరుపతి బాలాజీ',
    english: 'Tirupati Bala Ji',
    emoji: '🌟',
    color: '#FFD54F',
    desc: 'శ్రీ వెంకటేశ్వరుడు, విష్ణువు యొక్క పూజ్య రూపం',
    img: 'icons/tirupati_balaji.webp',
  },
  jagannath: {
    name: 'శ్రీ జగన్నాథుడు',
    english: 'Jagannath',
    emoji: '🕉️',
    color: '#4CAF50',
    desc: 'పురి ప్రసిద్ధ దేవుడు, భగవాన్ విష్ణువు రూపం మరియు భక్తి ప్రతీక',
    img: 'icons/jagannath.webp',
  },
  gopal: {
    name: 'శ్రీ గోపాల్',
    english: 'Shri Gopal',
    emoji: '🐄',
    color: '#5C6BC0',
    desc: 'బాల గోవిందుడు, గోపాలకుడు, కరుణామయుడు',
    img: 'icons/gopal.webp',
  },
  surya: {
    name: 'శ్రీ సూర్యుడు',
    english: 'Shri Surya',
    emoji: '☀️',
    color: '#FF8C00',
    desc: 'ప్రత్యక్ష దేవుడు, జగత్తు నేత్రం, శక్తి మూలం',
    img: 'icons/surya.webp',
  },
  shani: {
    name: 'శ్రీ శని దేవుడు',
    english: 'Shri Shani Dev',
    emoji: '⚖️',
    color: '#1a1a1a',
    desc: 'కర్మఫల దాత, సూర్య పుత్రుడు, న్యాయదేవుడు',
    img: 'icons/shani.webp',
  },
  brihaspati: {
    name: 'శ్రీ బృహస్పతి దేవుడు',
    english: 'Shri Brihaspati Dev',
    emoji: '📜',
    color: '#EF6C00',
    desc: 'వేదజ్ఞుడు, గురువు, న్యాయదేవుడు',
    img: 'icons/brihaspati.webp',
  },
  brahma: {
    name: 'శ్రీ బ్రహ్మ',
    english: 'Shri Brahma',
    emoji: '📜',
    color: '#EF6C00',
    desc: 'సృష్టికర్త, వేదజ్ఞుడు, చతుర్ముఖుడు',
    img: 'icons/brahma.webp',
  },
  saraswati: {
    name: 'శ్రీ సరస్వతి',
    english: 'Shri Saraswati',
    emoji: '🎵',
    color: '#FFFFFF',
    desc: 'విద్యాదాయిని, వాగ్దేవి, వీణావాదిని',
    img: 'icons/saraswati.webp',
  },
  bhairav: {
    name: 'శ్రీ భైరవుడు',
    english: 'Shri Bhairav',
    emoji: '🐕',
    color: '#37474F',
    desc: 'క్షేత్రపాలకుడు, రక్షకుడు, ఉగ్ర కరుణామయుడు',
    img: 'icons/bhairav.webp',
  },
  batuk_bhairav: {
    name: 'శ్రీ బటుక భైరవుడు',
    english: 'Shri Batuk Bhairav',
    emoji: '🛡️',
    color: '#455A64',
    desc: 'బాల భైరవుడు, తక్షణ రక్షకుడు',
    img: 'icons/batuk_bhairav.webp',
  },
  parshuram: {
    name: 'శ్రీ పరశురాముడు',
    english: 'Shri Parshuram',
    emoji: '🪓',
    color: '#5D4037',
    desc: 'విష్ణు అవతారం, ధర్మ రక్షకుడు',
    img: 'icons/parshuram.webp',
  },
  giriraj: {
    name: 'శ్రీ గిరిరాజ్',
    english: 'Shri Giriraj',
    emoji: '⛰️',
    color: '#7CB342',
    desc: 'గోవర్ధన స్వరూపం, శరణదాత',
    img: 'icons/giriraj.webp',
  },
  navgrah: {
    name: 'శ్రీ నవగ్రహాలు',
    english: 'Shri Navgrah',
    emoji: '🪐',
    color: '#546E7A',
    desc: 'తొమ్మిది గ్రహాల సమష్టి పూజ',
    img: 'icons/navgrah.webp',
  },
  vishwakarma: {
    name: 'శ్రీ విశ్వకర్మ',
    english: 'Shri Vishwakarma',
    emoji: '🛠️',
    color: '#6D4C41',
    desc: 'దేవ శిల్పి, నిర్మాణ దేవుడు',
    img: 'icons/vishwakarma.webp',
  },
  sai: {
    name: 'శ్రీ సాయి',
    english: 'Shri Sai',
    emoji: '🕯️',
    color: '#9E9D24',
    desc: 'శ్రద్ధ మరియు సబూరి యొక్క ప్రతీక',
    img: 'icons/sai.webp',
  },
  mahavir: {
    name: 'శ్రీ మహావీర్',
    english: 'Shri Mahavir',
    emoji: '🪷',
    color: '#26A69A',
    desc: 'అహింస, తపస్సు మరియు సత్యానికి ఆదర్శం',
    img: 'icons/mahavir.webp',
  },
  pitar: {
    name: 'శ్రీ పితృదేవుడు',
    english: 'Shri Pitar',
    emoji: '🕯',
    color: '#6D4C41',
    desc: 'పూర్వజ పూజ, కుటుంబ ఆశీర్వాదం',
    img: 'icons/pitar.webp',
  },
  vaishno_devi: {
    name: 'శ్రీ వైష్ణో దేవి',
    english: 'Shri Vaishno Devi',
    emoji: '🛕',
    color: '#C2185B',
    desc: 'త్రికూట వాసిని, శక్తిస్వరూపిణి',
    img: 'icons/vaishno_devi.webp',
  },
  sheetla: {
    name: 'శ్రీ శీతలా',
    english: 'Shri Sheetla',
    emoji: '🧺',
    color: '#00ACC1',
    desc: 'ఆరోగ్యాన్ని ప్రసాదించే తల్లి',
    img: 'icons/sheetla.webp',
  },
  mahakali: {
    name: 'శ్రీ మహాకాళి',
    english: 'Shri Mahakali',
    emoji: '⚔️',
    color: '#283593',
    desc: 'కాలాన్ని నశింపజేసే, అజేయ శక్తి',
    img: 'icons/mahakali.webp',
  },
  baglamukhi: {
    name: 'శ్రీ బగలాముఖి',
    english: 'Shri Baglamukhi',
    emoji: '🟡',
    color: '#FBC02D',
    desc: 'దశమహావిద్య, స్తంభన శక్తి',
    img: 'icons/baglamukhi.webp',
  },
  mahalakshmi: {
    name: 'శ్రీ మహాలక్ష్మి',
    english: 'Shri Mahalakshmi',
    emoji: '💰',
    color: '#F9A825',
    desc: 'ఐశ్వర్యం, సౌభాగ్యం, మంగళమయి',
    img: 'icons/mahalakshmi.webp',
  },
  gayatri: {
    name: 'శ్రీ గాయత్రి',
    english: 'Shri Gayatri',
    emoji: '📿',
    color: '#FF7043',
    desc: 'వేదమాత, బుద్ధిని ప్రసాదించే దేవి',
    img: 'icons/gayatri.webp',
  },
  sharda: {
    name: 'శ్రీ శారద',
    english: 'Shri Sharda',
    emoji: '📖',
    color: '#5E35B1',
    desc: 'జ్ఞాన మరియు వాణి స్వరూపం',
    img: 'icons/sharda.webp',
  },
  radha: {
    name: 'శ్రీ రాధ',
    english: 'Shri Radha',
    emoji: '🌸',
    color: '#EC407A',
    desc: 'భక్తి మరియు ప్రేమ యొక్క అధిష్ఠాత్రి',
    img: 'icons/radha.webp',
  },
  santoshi_maa: {
    name: 'శ్రీ సంతోషి మాత',
    english: 'Shri Santoshi Maa',
    emoji: '🍚',
    color: '#F06292',
    desc: 'సంతృప్తి, సుఖం మరియు సరళ భక్తి',
    img: 'icons/santoshi_maa.webp',
  },
  vindhyeshwari: {
    name: 'శ్రీ వింధ్యేశ్వరి',
    english: 'Shri Vindhyeshwari',
    emoji: '🌺',
    color: '#D81B60',
    desc: 'వింధ్యవాసిని మాత స్వరూపం',
    img: 'icons/vindhyeshwari.webp',
  },
  annapurna: {
    name: 'శ్రీ అన్నపూర్ణ',
    english: 'Shri Annapurna',
    emoji: '🍲',
    color: '#FF8F00',
    desc: 'అన్నం, పోషణ మరియు కరుణ దేవి',
    img: 'icons/annapurna.webp',
  },
  tulsi: {
    name: 'శ్రీ తులసి',
    english: 'Shri Tulsi',
    emoji: '🌿',
    color: '#43A047',
    desc: 'పవిత్రత, భక్తి మరియు రక్షణ',
    img: 'icons/tulsi.webp',
  },
  ganga: {
    name: 'శ్రీ గంగా',
    english: 'Shri Ganga',
    emoji: '🌊',
    color: '#1E88E5',
    desc: 'పవిత్ర నది, మోక్షదాయిని',
    img: 'icons/ganga.webp',
  },
  narmada: {
    name: 'శ్రీ నర్మద',
    english: 'Shri Narmada',
    emoji: '💧',
    color: '#039BE5',
    desc: 'రేవా మాత, పుణ్యదాయిని',
    img: 'icons/narmada.webp',
  },
  shakambhari: {
    name: 'శ్రీ శాకంభరి',
    english: 'Shri Shakambhari',
    emoji: '🥬',
    color: '#7CB342',
    desc: 'అన్నం మరియు వృక్షాలను పోషించే దేవి',
    img: 'icons/shakambhari.webp',
  },
  lalita_shakambhari: {
    name: 'శ్రీ లలిత శాకంభరి',
    english: 'Shri Lalita Shakambhari',
    emoji: '🌼',
    color: '#8BC34A',
    desc: 'లలిత మరియు శాకంభరి యొక్క సమిష్టి రూపం',
    img: 'icons/lalita_shakambhari.webp',
  },
  rani_sati: {
    name: 'శ్రీ రాణి సతి',
    english: 'Shri Rani Sati',
    emoji: '🏵️',
    color: '#8E24AA',
    desc: 'జనఆస్థకు పూజ్య మాతృశక్తి',
    img: 'icons/rani_sati.webp',
  },
  ravidas: {
    name: 'శ్రీ రవిదాస్',
    english: 'Shri Ravidas',
    emoji: '🙏',
    color: '#8D6E63',
    desc: 'భక్తి సంత్, సమత్వ సందేశం',
    img: 'icons/ravidas.webp',
  },
  baba_gangaram: {
    name: 'శ్రీ బాబా గంగారాం',
    english: 'Shri Baba Gangaram',
    emoji: '🛕',
    color: '#6A1B9A',
    desc: 'జనభక్తిలో పూజ్య సంత్',
    img: 'icons/baba_gangaram.webp',
  },
  ramdev: {
    name: 'శ్రీ రామదేవ్',
    english: 'Shri Ramdev',
    emoji: '🐎',
    color: '#8E24AA',
    desc: 'లోకదేవుడు, ప్రజాహితకారి',
    img: 'icons/ramdev.webp',
  },
  jaharveer: {
    name: 'శ్రీ జహర్వీర్',
    english: 'Shri Jaharveer',
    emoji: '🏇',
    color: '#795548',
    desc: 'లోక రక్షకుడు, వీర దేవుడు',
    img: 'icons/jaharveer.webp',
  },
  gorakh_nath: {
    name: 'శ్రీ గోరఖనాథ్',
    english: 'Shri Gorakh Nath',
    emoji: '🧘',
    color: '#607D8B',
    desc: 'నాథ యోగ పరంపర ఆచార్యుడు',
    img: 'icons/gorakh_nath.webp',
  },
};
