// ============ DATA ============
const deities = {
  ganesh: {
    name: 'ஸ்ரீ கணேஷ்',
    english: 'Shri Ganesh',
    emoji: '🐘',
    color: '#FF6B00',
    desc: 'விநாயகத் தெய்வம், முதலில் வழிபடப்படுபவர்',
    img: 'ganesh.webp',
  },
  shiva: {
    name: 'ஸ்ரீ சிவன்',
    english: 'Shri Shiv',
    emoji: '🔱',
    color: '#4169E1',
    desc: 'மகாதேவர், போளேநாத், அழிப்பவர்',
    img: 'shiv.webp',
  },
  parvati: {
    name: 'ஸ்ரீ பார்வதி தேவி',
    english: 'Shri Parvati',
    emoji: '🪷',
    color: '#AD1457',
    desc: 'சிவனின் அர்த்தாங்கினி, சக்தி மற்றும் தாய்மையின் தேவி',
    img: 'parvati.webp',
  },
  vishnu: {
    name: 'ஸ்ரீ விஷ்ணு',
    english: 'Shri Vishnu',
    emoji: '✨',
    color: '#0080FF',
    desc: 'பாலனாளர், நாராயணன், உலகைக் காப்பவர்',
    img: 'vishnu.webp',
  },
  lakshmi: {
    name: 'ஸ்ரீ லட்சுமி',
    english: 'Shri Lakshmi',
    emoji: '🪷',
    color: '#FFD700',
    desc: 'செல்வம் அருள்பவள், தாமரை வாசினி, செழிப்பின் தேவி',
    img: 'lakshmi.webp',
  },
  durga: {
    name: 'ஸ்ரீ துர்கை',
    english: 'Shri Durga',
    emoji: '🌸',
    color: '#FF1493',
    desc: 'ஆதிசக்தி, மகாமாயா, சிம்மவாகினி',
    img: 'durga.webp',
  },
  kali: {
    name: 'ஸ்ரீ காளி',
    english: 'Shri Kali',
    emoji: '⚡',
    color: '#800080',
    desc: 'மகாகாளி, தாரா, ஆதிசக்தியின் உக்கிர வடிவு',
    img: 'kali.webp',
  },
  ram: {
    name: 'ஸ்ரீ ராமர்',
    english: 'Shri Ram',
    emoji: '🏹',
    color: '#00AA00',
    desc: 'மர்யாதை புருஷோத்தமர், ரகு குலத்தின் பெருமை',
    img: 'ram.webp',
  },
  hanuman: {
    name: 'ஸ்ரீ ஹனுமான்',
    english: 'Shri Hanuman',
    emoji: '🙏',
    color: '#FF4500',
    desc: 'பவனபுத்ரர், பஜரங்கபலி, ராம பக்தர்களின் சிரோமணி',
    img: 'hanuman.webp',
  },
  balaji: {
    name: 'ஸ்ரீ பாலாஜி',
    english: 'Shri Balaji',
    emoji: '🏹',
    color: '#8D6E63',
    desc: 'சங்கடம் நீக்கும் வணங்கத்தக்க வடிவு',
    img: 'balaji.webp',
  },
  pretraj_sarkar: {
    name: 'ஸ்ரீ பிரேதராஜ் சர்கார்',
    english: 'Shri Pretraj Sarkar',
    emoji: '🔥',
    color: '#4E342E',
    desc: 'எதிர்மறை தடைகளை நீக்குபவர்',
    img: 'pretraj_sarkar.webp',
  },
  krishna: {
    name: 'ஸ்ரீ கிருஷ்ணர்',
    english: 'Shri Krishna',
    emoji: '🪈',
    color: '#0000CD',
    desc: 'கோவிந்தன், முரளி மோகனன், பிரஜவிஹாரி',
    img: 'krishna.webp',
    geeta: typeof geetaData !== 'undefined' ? geetaData.krishna : null,
  },
  khatu_shyam: {
    name: 'ஸ்ரீ காட்டு ஷ்யாம்',
    english: 'Shri Khatu Shyam',
    emoji: '🏹',
    color: '#FF4500',
    desc: 'தோல்வியுற்றவர்களுக்கு ஆதரவு, மோர்வி நந்தன், கலியுக அவதாரம்',
    img: 'khatu_shyam.webp',
  },
  tirupati_balaji: {
    name: 'ஸ்ரீ திருப்பதி பாலாஜி',
    english: 'Tirupati Bala Ji',
    emoji: '🌟',
    color: '#FFD54F',
    desc: 'ஸ்ரீ வெங்கடேஸ்வரர், விஷ்ணுவின் புனித வடிவு',
    img: 'tirupati_balaji.webp',
  },
  jagannath: {
    name: 'ஸ்ரீ ஜகந்நாதர்',
    english: 'Jagannath',
    emoji: '🕉️',
    color: '#4CAF50',
    desc: 'புரியின் புகழ்பெற்ற தெய்வம், பகவான் விஷ்ணுவின் வடிவு மற்றும் பக்தியின் சின்னம்',
    img: 'jagannath.webp',
  },
  gopal: {
    name: 'ஸ்ரீ கோபால்',
    english: 'Shri Gopal',
    emoji: '🐄',
    color: '#5C6BC0',
    desc: 'பால கோவிந்தன், கோபாலன், கருணைமிகு',
    img: 'gopal.webp',
  },
  balarama: {
    name: 'ஸ்ரீ பலராமர்',
    english: 'Shri Balarama',
    emoji: '🙏',
    color: '#F5F5DC',
    desc: 'ஸ்ரீ கிருஷ்ணரின் மூத்த சகோதரர், ஆதிசேஷனின் அவதாரம், வலிமை மற்றும் தர்மத்தின் அடையாளம்',
    img: 'balarama.webp',
  },
  narasimha: {
    name: 'ஸ்ரீ நரசிம்மர்',
    english: 'Shri Narasimha',
    emoji: '🙏',
    color: '#D84315',
    desc: 'திருமாலின் உக்கிர அவதாரம், பக்த பிரகலாதனின் பாதுகாவலர் மற்றும் அதர்மத்தை அழிப்பவர்',
    img: 'narasimha.webp',
  },
  vamana: {
    name: 'ஸ்ரீ வாமனர்',
    english: 'Shri Vamana',
    emoji: '🙏',
    color: '#6D4C41',
    desc: 'திருமாலின் ஐந்தாவது அவதாரம், தர்மத்தை நிலைநாட்டியவர் மற்றும் மகாபலி மன்னரின் அருளாளன்',
    img: 'vamana.webp',
  },
  varaha: {
    name: 'ஸ்ரீ வராகர்',
    english: 'Shri Varaha',
    emoji: '🙏',
    color: '#795548',
    desc: 'திருமாலின் மூன்றாவது அவதாரம், பூமாதேவியை மீட்டெடுத்தவர் மற்றும் அதர்மத்தை அழிப்பவர்',
    img: 'varaha.webp',
  },
  matsya: {
    name: 'ஸ்ரீ மத்ஸ்யர்',
    english: 'Shri Matsya',
    emoji: '🙏',
    color: '#0277BD',
    desc: 'திருமாலின் முதல் அவதாரம், வேதங்களின் பாதுகாவலர் மற்றும் பிரளயத்திலிருந்து உயிர்களைக் காப்பவர்',
    img: 'matsya.webp',
  },
  kurma: {
    name: 'ஸ்ரீ கூர்மர்',
    english: 'Shri Kurma',
    emoji: '🙏',
    color: '#5D4037',
    desc: 'திருமாலின் இரண்டாவது அவதாரம், பாற்கடல் கடையும்போது மந்தர மலையைத் தாங்கியவர்',
    img: 'kurma.webp',
  },
  hayagriva: {
    name: 'ஸ்ரீ ஹயக்ரீவர்',
    english: 'Shri Hayagriva',
    emoji: '🙏',
    color: '#1565C0',
    desc: 'திருமாலின் தெய்வீக குதிரைமுக வடிவம், ஞானம், கல்வி மற்றும் வேதங்களின் அதிபதி',
    img: 'hayagriva.webp',
  },
  vitthal: {
    name: 'ஸ்ரீ விட்டலர்',
    english: 'Shri Vitthal',
    emoji: '🙏',
    color: '#1565C0',
    desc: 'திருமாலின் பக்தர்களை அருளும் வடிவம், பண்டர்பூரின் வழிபடு தெய்வம் மற்றும் பக்தியின் அடையாளம்',
    img: 'vitthal.webp',
  },
  ranganatha: {
    name: 'ஸ்ரீ ரங்கநாதர்',
    english: 'Shri Ranganatha',
    emoji: '🙏',
    color: '#1565C0',
    desc: 'திருமாலின் பள்ளிகொண்ட திருக்கோலம், ஸ்ரீரங்கத்தின் ஆராதனைத் தெய்வம் மற்றும் பக்தர்களின் பாதுகாவலர்',
    img: 'ranganatha.webp',
  },
  dhanvantari: {
    name: 'ஸ்ரீ தன்வந்திரி',
    english: 'Shri Dhanvantari',
    emoji: '🙏',
    color: '#2E7D32',
    desc: 'திருமாலின் தெய்வீக அவதாரம், ஆயுர்வேதம் மற்றும் ஆரோக்கியத்தின் அதிபதி',
    img: 'dhanvantari.webp',
  },
  kartikeya: {
    name: 'ஸ்ரீ கார்த்திகேயர்',
    english: 'Shri Kartikeya',
    emoji: '🙏',
    color: '#E65100',
    desc: 'தேவசேனாதிபதி, சிவபார்வதியின் மகன், போர் மற்றும் வெற்றியின் கடவுள்',
    img: 'kartikeya.webp',
  },
  ayyappa: {
    name: 'ஸ்ரீ ஐயப்பன்',
    english: 'Shri Ayyappa',
    emoji: '🙏',
    color: '#5D4037',
    desc: 'ஹரிஹரபுத்திரர், தர்மசாஸ்தா, பக்தி மற்றும் தர்மத்தின் கடவுள்',
    img: 'ayyappa.webp',
  },
  ardhanarishvara: {
    name: 'அர்த்தநாரீஸ்வரர்',
    english: 'Ardhanarishvara',
    emoji: '🙏',
    color: '#7B1FA2',
    desc: 'சிவனும் சக்தியும் இணைந்த தெய்வீக வடிவம், ஆண் மற்றும் இயற்கையின் ஒற்றுமையின் அடையாளம்',
    img: 'ardhanarishvara.webp',
  },
  surya: {
    name: 'ஸ்ரீ சூரியன்',
    english: 'Shri Surya',
    emoji: '☀️',
    color: '#FF8C00',
    desc: 'நேரில் காணப்படும் தெய்வம், உலகின் கண்கள், ஆற்றலின் மூலம்',
    img: 'surya.webp',
  },
  shani: {
    name: 'ஸ்ரீ சனி பகவான்',
    english: 'Shri Shani Dev',
    emoji: '⚖️',
    color: '#1a1a1a',
    desc: 'கர்மபலத்தை அளிப்பவர், சூரிய புத்திரர், நீதியின் தெய்வம்',
    img: 'shani.webp',
  },
  brihaspati: {
    name: 'ஸ்ரீ ப்ருஹஸ்பதி தேவர்',
    english: 'Shri Brihaspati Dev',
    emoji: '📜',
    color: '#EF6C00',
    desc: 'வேதஞானி, குரு, நீதியின் தெய்வம்',
    img: 'brihaspati.webp',
  },
  brahma: {
    name: 'ஸ்ரீ பிரம்மா',
    english: 'Shri Brahma',
    emoji: '📜',
    color: '#EF6C00',
    desc: 'படைக்கும் தெய்வம், வேதஞானி, நான்முகன்',
    img: 'brahma.webp',
  },
  saraswati: {
    name: 'ஸ்ரீ சரஸ்வதி',
    english: 'Shri Saraswati',
    emoji: '🎵',
    color: '#FFFFFF',
    desc: 'கல்வி அருள்பவள், வாக்தேவி, வீணை வாசிப்பவள்',
    img: 'saraswati.webp',
  },
  bhairav: {
    name: 'ஸ்ரீ பைரவர்',
    english: 'Shri Bhairav',
    emoji: '🐕',
    color: '#37474F',
    desc: 'க்ஷேத்திரபாலகர், காப்பாளர், உக்கிர கருணையுடையவர்',
    img: 'bhairav.webp',
  },
  batuk_bhairav: {
    name: 'ஸ்ரீ படுக் பைரவர்',
    english: 'Shri Batuk Bhairav',
    emoji: '🛡️',
    color: '#455A64',
    desc: 'பால பைரவர், விரைவு காப்பாளர்',
    img: 'batuk_bhairav.webp',
  },
  veerabhadra: {
    name: 'ஸ்ரீ வீரபத்திரர்',
    english: 'Shri Veerabhadra',
    emoji: '🙏',
    color: '#8B0000',
    desc: 'சிவபெருமானின் உக்கிர வடிவம், தர்மம் மற்றும் நீதியின் காவலர்',
    img: 'veerabhadra.webp',
  },
  parshuram: {
    name: 'ஸ்ரீ பரசுராமர்',
    english: 'Shri Parshuram',
    emoji: '🪓',
    color: '#5D4037',
    desc: 'விஷ்ணுவின் அவதாரம், தர்மத்தை காப்பவர்',
    img: 'parshuram.webp',
  },
  giriraj: {
    name: 'ஸ்ரீ கிரிராஜ்',
    english: 'Shri Giriraj',
    emoji: '⛰️',
    color: '#7CB342',
    desc: 'கோவர்தன வடிவு, சரணடைபவர்க்கு ஆதரவு',
    img: 'giriraj.webp',
  },
  navgrah: {
    name: 'ஸ்ரீ நவகிரகம்',
    english: 'Shri Navgrah',
    emoji: '🪐',
    color: '#546E7A',
    desc: 'ஒன்பது கிரகங்களின் கூட்டுப் பூஜை',
    img: 'navgrah.webp',
  },
  vishwakarma: {
    name: 'ஸ்ரீ விஸ்வகர்மா',
    english: 'Shri Vishwakarma',
    emoji: '🛠️',
    color: '#6D4C41',
    desc: 'தெய்வ சிற்பி, கட்டுமானத்தின் தெய்வம்',
    img: 'vishwakarma.webp',
  },
  sai: {
    name: 'ஸ்ரீ சாய்',
    english: 'Shri Sai',
    emoji: '🕯️',
    color: '#9E9D24',
    desc: 'நம்பிக்கை மற்றும் பொறுமையின் சின்னம்',
    img: 'sai.webp',
  },
  mahavir: {
    name: 'ஸ்ரீ மகாவீர்',
    english: 'Shri Mahavir',
    emoji: '🪷',
    color: '#26A69A',
    desc: 'அஹிம்சை, தவம் மற்றும் சத்தியத்தின் முன்மாதிரி',
    img: 'mahavir.webp',
  },
  pitar: {
    name: 'ஸ்ரீ பித்ரு தேவன்',
    english: 'Shri Pitar',
    emoji: '🕯',
    color: '#6D4C41',
    desc: 'முன்னோர்கள் வழிபாடு, குல ஆசீர்வாதம்',
    img: 'pitar.webp',
  },
  vaishno_devi: {
    name: 'ஸ்ரீ வைஷ்ணோ தேவி',
    english: 'Shri Vaishno Devi',
    emoji: '🛕',
    color: '#C2185B',
    desc: 'திரிகூட வாசினி, சக்தி வடிவு',
    img: 'vaishno_devi.webp',
  },
  sheetla: {
    name: 'ஸ்ரீ ஷீதளா',
    english: 'Shri Sheetla',
    emoji: '🧺',
    color: '#00ACC1',
    desc: 'ஆரோக்கியம் அருளும் தாய்',
    img: 'sheetla.webp',
  },
  mahakali: {
    name: 'ஸ்ரீ மகாகாளி',
    english: 'Shri Mahakali',
    emoji: '⚔️',
    color: '#283593',
    desc: 'காலத்தை அழிப்பவள், அடங்காத சக்தி',
    img: 'mahakali.webp',
  },
  baglamukhi: {
    name: 'ஸ்ரீ பகலாமுகி',
    english: 'Shri Baglamukhi',
    emoji: '🟡',
    color: '#FBC02D',
    desc: 'தசமஹாவித்யை, ஸ்தம்பன சக்தி',
    img: 'baglamukhi.webp',
  },
  mahalakshmi: {
    name: 'ஸ்ரீ மகாலட்சுமி',
    english: 'Shri Mahalakshmi',
    emoji: '💰',
    color: '#F9A825',
    desc: 'ஐச்வரியம், சுபம், மங்களமயி',
    img: 'mahalakshmi.webp',
  },
  gayatri: {
    name: 'ஸ்ரீ காயத்ரீ',
    english: 'Shri Gayatri',
    emoji: '📿',
    color: '#FF7043',
    desc: 'வேதமாதா, அறிவை அருள்பவள்',
    img: 'gayatri.webp',
  },
  sharda: {
    name: 'ஸ்ரீ சாரதா',
    english: 'Shri Sharda',
    emoji: '📖',
    color: '#5E35B1',
    desc: 'அறிவும் வாணியும் ஆகிய வடிவு',
    img: 'sharda.webp',
  },
  radha: {
    name: 'ஸ்ரீ ராதா',
    english: 'Shri Radha',
    emoji: '🌸',
    color: '#EC407A',
    desc: 'பக்தி மற்றும் அன்பின் அதிஷ்டாத்ரி',
    img: 'radha.webp',
  },
  santoshi_maa: {
    name: 'ஸ்ரீ சந்தோஷி மாதா',
    english: 'Shri Santoshi Maa',
    emoji: '🍚',
    color: '#F06292',
    desc: 'திருப்தி, மகிழ்ச்சி, எளிய பக்தி',
    img: 'santoshi_maa.webp',
  },
  vindhyeshwari: {
    name: 'ஸ்ரீ விந்த்யேஸ்வரி',
    english: 'Shri Vindhyeshwari',
    emoji: '🌺',
    color: '#D81B60',
    desc: 'விந்த்யவாசினி தாயின் வடிவு',
    img: 'vindhyeshwari.webp',
  },
  annapurna: {
    name: 'ஸ்ரீ அன்னபூர்ணா',
    english: 'Shri Annapurna',
    emoji: '🍲',
    color: '#FF8F00',
    desc: 'அன்னம், ஊட்டம், கருணையின் தேவி',
    img: 'annapurna.webp',
  },
  chhathi_maiya: {
    name: 'சட்டீ மையா',
    english: 'Chhathi Maiya',
    emoji: '🌅',
    color: '#FF6F00',
    desc: 'சூரிய வழிபாடு, குழந்தைப் பேறு மற்றும் செழிப்பின் தெய்வம்',
    img: 'chhathi_maiya.webp',
  },
  tulsi: {
    name: 'ஸ்ரீ துளசி',
    english: 'Shri Tulsi',
    emoji: '🌿',
    color: '#43A047',
    desc: 'பரிசுத்தம், பக்தி, பாதுகாப்பு',
    img: 'tulsi.webp',
  },
  ganga: {
    name: 'ஸ்ரீ கங்கை',
    english: 'Shri Ganga',
    emoji: '🌊',
    color: '#1E88E5',
    desc: 'புனித நதி, முக்தி அருள்பவள்',
    img: 'ganga.webp',
  },
  narmada: {
    name: 'ஸ்ரீ நர்மதா',
    english: 'Shri Narmada',
    emoji: '💧',
    color: '#039BE5',
    desc: 'ரேவா தாய், புண்ணியம் அருள்பவள்',
    img: 'narmada.webp',
  },
  shakambhari: {
    name: 'ஸ்ரீ ஷாகம்பரி',
    english: 'Shri Shakambhari',
    emoji: '🥬',
    color: '#7CB342',
    desc: 'அன்னம் மற்றும் தாவரங்களைப் பேணும் தேவி',
    img: 'shakambhari.webp',
  },
  lalita_shakambhari: {
    name: 'ஸ்ரீ லலிதா ஷாகம்பரி',
    english: 'Shri Lalita Shakambhari',
    emoji: '🌼',
    color: '#8BC34A',
    desc: 'லலிதா மற்றும் ஷாகம்பரியின் இணைந்த வடிவு',
    img: 'lalita_shakambhari.webp',
  },
  rani_sati: {
    name: 'ஸ்ரீ ராணி சதி',
    english: 'Shri Rani Sati',
    emoji: '🏵️',
    color: '#8E24AA',
    desc: 'மக்கள் நம்பிக்கையின் பூஜ்ய மாதர் சக்தி',
    img: 'rani_sati.webp',
  },
  neem_karoli_baba: {
    name: 'நீம் கரோலி பாபா',
    english: 'Neem Karoli Baba',
    emoji: '🙏',
    color: '#FF9800',
    desc: 'பக்தி, சேவை மற்றும் அன்பின் துறவி',
    img: 'neem_karoli_baba.webp',
  },
  ravidas: {
    name: 'ஸ்ரீ ரவிதாஸ்',
    english: 'Shri Ravidas',
    emoji: '🙏',
    color: '#8D6E63',
    desc: 'பக்தி சாது, சமத்துவத்தின் செய்தி',
    img: 'ravidas.webp',
  },
  baba_gangaram: {
    name: 'ஸ்ரீ பாபா கங்காராம்',
    english: 'Shri Baba Gangaram',
    emoji: '🛕',
    color: '#6A1B9A',
    desc: 'மக்கள் பக்தியில் வணங்கப்படும் சாது',
    img: 'baba_gangaram.webp',
  },
  ramdev: {
    name: 'ஸ்ரீ ராம்தேவ்',
    english: 'Shri Ramdev',
    emoji: '🐎',
    color: '#8E24AA',
    desc: 'மக்கள் தெய்வம், பொதுநலன் காக்கும்வர்',
    img: 'ramdev.webp',
  },
  jaharveer: {
    name: 'ஸ்ரீ ஜஹர்வீர்',
    english: 'Shri Jaharveer',
    emoji: '🏇',
    color: '#795548',
    desc: 'மக்கள் காப்பாளர், வீர தெய்வம்',
    img: 'jaharveer.webp',
  },
  gorakh_nath: {
    name: 'ஸ்ரீ கோரக்நாத்',
    english: 'Shri Gorakh Nath',
    emoji: '🧘',
    color: '#607D8B',
    desc: 'நாத யோக மரபின் ஆசான்',
    img: 'gorakh_nath.webp',
  },
};
