// ============ DATA ============
const deities = {
  ganesh: {
    name: 'ஸ்ரீ கணேஷ்',
    english: 'Shri Ganesh',
    emoji: '🐘',
    color: '#FF6B00',
    desc: 'விநாயகத் தெய்வம், முதலில் வழிபடப்படுபவர்',
    img: 'icons/ganesh.webp',
  },
  shiva: {
    name: 'ஸ்ரீ சிவன்',
    english: 'Shri Shiv',
    emoji: '🔱',
    color: '#4169E1',
    desc: 'மகாதேவர், போளேநாத், அழிப்பவர்',
    img: 'icons/shiv.webp',
  },
  parvati: {
    name: 'ஸ்ரீ பார்வதி தேவி',
    english: 'Shri Parvati',
    emoji: '🪷',
    color: '#AD1457',
    desc: 'சிவனின் அர்த்தாங்கினி, சக்தி மற்றும் தாய்மையின் தேவி',
    img: 'icons/parvati.webp',
  },
  vishnu: {
    name: 'ஸ்ரீ விஷ்ணு',
    english: 'Shri Vishnu',
    emoji: '✨',
    color: '#0080FF',
    desc: 'பாலனாளர், நாராயணன், உலகைக் காப்பவர்',
    img: 'icons/vishnu.webp',
  },
  lakshmi: {
    name: 'ஸ்ரீ லட்சுமி',
    english: 'Shri Lakshmi',
    emoji: '🪷',
    color: '#FFD700',
    desc: 'செல்வம் அருள்பவள், தாமரை வாசினி, செழிப்பின் தேவி',
    img: 'icons/lakshmi.webp',
  },
  durga: {
    name: 'ஸ்ரீ துர்கை',
    english: 'Shri Durga',
    emoji: '🌸',
    color: '#FF1493',
    desc: 'ஆதிசக்தி, மகாமாயா, சிம்மவாகினி',
    img: 'icons/durga.webp',
  },
  kali: {
    name: 'ஸ்ரீ காளி',
    english: 'Shri Kali',
    emoji: '⚡',
    color: '#800080',
    desc: 'மகாகாளி, தாரா, ஆதிசக்தியின் உக்கிர வடிவு',
    img: 'icons/kali.webp',
  },
  ram: {
    name: 'ஸ்ரீ ராமர்',
    english: 'Shri Ram',
    emoji: '🏹',
    color: '#00AA00',
    desc: 'மர்யாதை புருஷோத்தமர், ரகு குலத்தின் பெருமை',
    img: 'icons/ram.webp',
  },
  hanuman: {
    name: 'ஸ்ரீ ஹனுமான்',
    english: 'Shri Hanuman',
    emoji: '🙏',
    color: '#FF4500',
    desc: 'பவனபுத்ரர், பஜரங்கபலி, ராம பக்தர்களின் சிரோமணி',
    img: 'icons/hanuman.webp',
  },
  balaji: {
    name: 'ஸ்ரீ பாலாஜி',
    english: 'Shri Balaji',
    emoji: '🏹',
    color: '#8D6E63',
    desc: 'சங்கடம் நீக்கும் வணங்கத்தக்க வடிவு',
    img: 'icons/balaji.webp',
  },
  pretraj_sarkar: {
    name: 'ஸ்ரீ பிரேதராஜ் சர்கார்',
    english: 'Shri Pretraj Sarkar',
    emoji: '🔥',
    color: '#4E342E',
    desc: 'எதிர்மறை தடைகளை நீக்குபவர்',
    img: 'icons/pretraj_sarkar.webp',
  },
  krishna: {
    name: 'ஸ்ரீ கிருஷ்ணர்',
    english: 'Shri Krishna',
    emoji: '🪈',
    color: '#0000CD',
    desc: 'கோவிந்தன், முரளி மோகனன், பிரஜவிஹாரி',
    img: 'icons/krishna.webp',
    geeta: typeof geetaData !== 'undefined' ? geetaData.krishna : null,
  },
  khatu_shyam: {
    name: 'ஸ்ரீ காட்டு ஷ்யாம்',
    english: 'Shri Khatu Shyam',
    emoji: '🏹',
    color: '#FF4500',
    desc: 'தோல்வியுற்றவர்களுக்கு ஆதரவு, மோர்வி நந்தன், கலியுக அவதாரம்',
    img: 'icons/khatu_shyam.webp',
  },
  tirupati_balaji: {
    name: 'ஸ்ரீ திருப்பதி பாலாஜி',
    english: 'Tirupati Bala Ji',
    emoji: '🌟',
    color: '#FFD54F',
    desc: 'ஸ்ரீ வெங்கடேஸ்வரர், விஷ்ணுவின் புனித வடிவு',
    img: 'icons/tirupati_balaji.webp',
  },
  jagannath: {
    name: 'ஸ்ரீ ஜகந்நாதர்',
    english: 'Jagannath',
    emoji: '🕉️',
    color: '#4CAF50',
    desc: 'புரியின் புகழ்பெற்ற தெய்வம், பகவான் விஷ்ணுவின் வடிவு மற்றும் பக்தியின் சின்னம்',
    img: 'icons/jagannath.webp',
  },
  gopal: {
    name: 'ஸ்ரீ கோபால்',
    english: 'Shri Gopal',
    emoji: '🐄',
    color: '#5C6BC0',
    desc: 'பால கோவிந்தன், கோபாலன், கருணைமிகு',
    img: 'icons/gopal.webp',
  },
  surya: {
    name: 'ஸ்ரீ சூரியன்',
    english: 'Shri Surya',
    emoji: '☀️',
    color: '#FF8C00',
    desc: 'நேரில் காணப்படும் தெய்வம், உலகின் கண்கள், ஆற்றலின் மூலம்',
    img: 'icons/surya.webp',
  },
  shani: {
    name: 'ஸ்ரீ சனி பகவான்',
    english: 'Shri Shani Dev',
    emoji: '⚖️',
    color: '#1a1a1a',
    desc: 'கர்மபலத்தை அளிப்பவர், சூரிய புத்திரர், நீதியின் தெய்வம்',
    img: 'icons/shani.webp',
  },
  brihaspati: {
    name: 'ஸ்ரீ ப்ருஹஸ்பதி தேவர்',
    english: 'Shri Brihaspati Dev',
    emoji: '📜',
    color: '#EF6C00',
    desc: 'வேதஞானி, குரு, நீதியின் தெய்வம்',
    img: 'icons/brihaspati.webp',
  },
  brahma: {
    name: 'ஸ்ரீ பிரம்மா',
    english: 'Shri Brahma',
    emoji: '📜',
    color: '#EF6C00',
    desc: 'படைக்கும் தெய்வம், வேதஞானி, நான்முகன்',
    img: 'icons/brahma.webp',
  },
  saraswati: {
    name: 'ஸ்ரீ சரஸ்வதி',
    english: 'Shri Saraswati',
    emoji: '🎵',
    color: '#FFFFFF',
    desc: 'கல்வி அருள்பவள், வாக்தேவி, வீணை வாசிப்பவள்',
    img: 'icons/saraswati.webp',
  },
  bhairav: {
    name: 'ஸ்ரீ பைரவர்',
    english: 'Shri Bhairav',
    emoji: '🐕',
    color: '#37474F',
    desc: 'க்ஷேத்திரபாலகர், காப்பாளர், உக்கிர கருணையுடையவர்',
    img: 'icons/bhairav.webp',
  },
  batuk_bhairav: {
    name: 'ஸ்ரீ படுக் பைரவர்',
    english: 'Shri Batuk Bhairav',
    emoji: '🛡️',
    color: '#455A64',
    desc: 'பால பைரவர், விரைவு காப்பாளர்',
    img: 'icons/batuk_bhairav.webp',
  },
  parshuram: {
    name: 'ஸ்ரீ பரசுராமர்',
    english: 'Shri Parshuram',
    emoji: '🪓',
    color: '#5D4037',
    desc: 'விஷ்ணுவின் அவதாரம், தர்மத்தை காப்பவர்',
    img: 'icons/parshuram.webp',
  },
  giriraj: {
    name: 'ஸ்ரீ கிரிராஜ்',
    english: 'Shri Giriraj',
    emoji: '⛰️',
    color: '#7CB342',
    desc: 'கோவர்தன வடிவு, சரணடைபவர்க்கு ஆதரவு',
    img: 'icons/giriraj.webp',
  },
  navgrah: {
    name: 'ஸ்ரீ நவகிரகம்',
    english: 'Shri Navgrah',
    emoji: '🪐',
    color: '#546E7A',
    desc: 'ஒன்பது கிரகங்களின் கூட்டுப் பூஜை',
    img: 'icons/navgrah.webp',
  },
  vishwakarma: {
    name: 'ஸ்ரீ விஸ்வகர்மா',
    english: 'Shri Vishwakarma',
    emoji: '🛠️',
    color: '#6D4C41',
    desc: 'தெய்வ சிற்பி, கட்டுமானத்தின் தெய்வம்',
    img: 'icons/vishwakarma.webp',
  },
  sai: {
    name: 'ஸ்ரீ சாய்',
    english: 'Shri Sai',
    emoji: '🕯️',
    color: '#9E9D24',
    desc: 'நம்பிக்கை மற்றும் பொறுமையின் சின்னம்',
    img: 'icons/sai.webp',
  },
  mahavir: {
    name: 'ஸ்ரீ மகாவீர்',
    english: 'Shri Mahavir',
    emoji: '🪷',
    color: '#26A69A',
    desc: 'அஹிம்சை, தவம் மற்றும் சத்தியத்தின் முன்மாதிரி',
    img: 'icons/mahavir.webp',
  },
  pitar: {
    name: 'ஸ்ரீ பித்ரு தேவன்',
    english: 'Shri Pitar',
    emoji: '🕯',
    color: '#6D4C41',
    desc: 'முன்னோர்கள் வழிபாடு, குல ஆசீர்வாதம்',
    img: 'icons/pitar.webp',
  },
  vaishno_devi: {
    name: 'ஸ்ரீ வைஷ்ணோ தேவி',
    english: 'Shri Vaishno Devi',
    emoji: '🛕',
    color: '#C2185B',
    desc: 'திரிகூட வாசினி, சக்தி வடிவு',
    img: 'icons/vaishno_devi.webp',
  },
  sheetla: {
    name: 'ஸ்ரீ ஷீதளா',
    english: 'Shri Sheetla',
    emoji: '🧺',
    color: '#00ACC1',
    desc: 'ஆரோக்கியம் அருளும் தாய்',
    img: 'icons/sheetla.webp',
  },
  mahakali: {
    name: 'ஸ்ரீ மகாகாளி',
    english: 'Shri Mahakali',
    emoji: '⚔️',
    color: '#283593',
    desc: 'காலத்தை அழிப்பவள், அடங்காத சக்தி',
    img: 'icons/mahakali.webp',
  },
  baglamukhi: {
    name: 'ஸ்ரீ பகலாமுகி',
    english: 'Shri Baglamukhi',
    emoji: '🟡',
    color: '#FBC02D',
    desc: 'தசமஹாவித்யை, ஸ்தம்பன சக்தி',
    img: 'icons/baglamukhi.webp',
  },
  mahalakshmi: {
    name: 'ஸ்ரீ மகாலட்சுமி',
    english: 'Shri Mahalakshmi',
    emoji: '💰',
    color: '#F9A825',
    desc: 'ஐச்வரியம், சுபம், மங்களமயி',
    img: 'icons/mahalakshmi.webp',
  },
  gayatri: {
    name: 'ஸ்ரீ காயத்ரீ',
    english: 'Shri Gayatri',
    emoji: '📿',
    color: '#FF7043',
    desc: 'வேதமாதா, அறிவை அருள்பவள்',
    img: 'icons/gayatri.webp',
  },
  sharda: {
    name: 'ஸ்ரீ சாரதா',
    english: 'Shri Sharda',
    emoji: '📖',
    color: '#5E35B1',
    desc: 'அறிவும் வாணியும் ஆகிய வடிவு',
    img: 'icons/sharda.webp',
  },
  radha: {
    name: 'ஸ்ரீ ராதா',
    english: 'Shri Radha',
    emoji: '🌸',
    color: '#EC407A',
    desc: 'பக்தி மற்றும் அன்பின் அதிஷ்டாத்ரி',
    img: 'icons/radha.webp',
  },
  santoshi_maa: {
    name: 'ஸ்ரீ சந்தோஷி மாதா',
    english: 'Shri Santoshi Maa',
    emoji: '🍚',
    color: '#F06292',
    desc: 'திருப்தி, மகிழ்ச்சி, எளிய பக்தி',
    img: 'icons/santoshi_maa.webp',
  },
  vindhyeshwari: {
    name: 'ஸ்ரீ விந்த்யேஸ்வரி',
    english: 'Shri Vindhyeshwari',
    emoji: '🌺',
    color: '#D81B60',
    desc: 'விந்த்யவாசினி தாயின் வடிவு',
    img: 'icons/vindhyeshwari.webp',
  },
  annapurna: {
    name: 'ஸ்ரீ அன்னபூர்ணா',
    english: 'Shri Annapurna',
    emoji: '🍲',
    color: '#FF8F00',
    desc: 'அன்னம், ஊட்டம், கருணையின் தேவி',
    img: 'icons/annapurna.webp',
  },
  tulsi: {
    name: 'ஸ்ரீ துளசி',
    english: 'Shri Tulsi',
    emoji: '🌿',
    color: '#43A047',
    desc: 'பரிசுத்தம், பக்தி, பாதுகாப்பு',
    img: 'icons/tulsi.webp',
  },
  ganga: {
    name: 'ஸ்ரீ கங்கை',
    english: 'Shri Ganga',
    emoji: '🌊',
    color: '#1E88E5',
    desc: 'புனித நதி, முக்தி அருள்பவள்',
    img: 'icons/ganga.webp',
  },
  narmada: {
    name: 'ஸ்ரீ நர்மதா',
    english: 'Shri Narmada',
    emoji: '💧',
    color: '#039BE5',
    desc: 'ரேவா தாய், புண்ணியம் அருள்பவள்',
    img: 'icons/narmada.webp',
  },
  shakambhari: {
    name: 'ஸ்ரீ ஷாகம்பரி',
    english: 'Shri Shakambhari',
    emoji: '🥬',
    color: '#7CB342',
    desc: 'அன்னம் மற்றும் தாவரங்களைப் பேணும் தேவி',
    img: 'icons/shakambhari.webp',
  },
  lalita_shakambhari: {
    name: 'ஸ்ரீ லலிதா ஷாகம்பரி',
    english: 'Shri Lalita Shakambhari',
    emoji: '🌼',
    color: '#8BC34A',
    desc: 'லலிதா மற்றும் ஷாகம்பரியின் இணைந்த வடிவு',
    img: 'icons/lalita_shakambhari.webp',
  },
  rani_sati: {
    name: 'ஸ்ரீ ராணி சதி',
    english: 'Shri Rani Sati',
    emoji: '🏵️',
    color: '#8E24AA',
    desc: 'மக்கள் நம்பிக்கையின் பூஜ்ய மாதர் சக்தி',
    img: 'icons/rani_sati.webp',
  },
  ravidas: {
    name: 'ஸ்ரீ ரவிதாஸ்',
    english: 'Shri Ravidas',
    emoji: '🙏',
    color: '#8D6E63',
    desc: 'பக்தி சாது, சமத்துவத்தின் செய்தி',
    img: 'icons/ravidas.webp',
  },
  baba_gangaram: {
    name: 'ஸ்ரீ பாபா கங்காராம்',
    english: 'Shri Baba Gangaram',
    emoji: '🛕',
    color: '#6A1B9A',
    desc: 'மக்கள் பக்தியில் வணங்கப்படும் சாது',
    img: 'icons/baba_gangaram.webp',
  },
  ramdev: {
    name: 'ஸ்ரீ ராம்தேவ்',
    english: 'Shri Ramdev',
    emoji: '🐎',
    color: '#8E24AA',
    desc: 'மக்கள் தெய்வம், பொதுநலன் காக்கும்வர்',
    img: 'icons/ramdev.webp',
  },
  jaharveer: {
    name: 'ஸ்ரீ ஜஹர்வீர்',
    english: 'Shri Jaharveer',
    emoji: '🏇',
    color: '#795548',
    desc: 'மக்கள் காப்பாளர், வீர தெய்வம்',
    img: 'icons/jaharveer.webp',
  },
  gorakh_nath: {
    name: 'ஸ்ரீ கோரக்நாத்',
    english: 'Shri Gorakh Nath',
    emoji: '🧘',
    color: '#607D8B',
    desc: 'நாத யோக மரபின் ஆசான்',
    img: 'icons/gorakh_nath.webp',
  },
};
